### PR TITLE
Issue #19589 Rename Chinese localization files

### LINKED ISSUE #19589: Rename Chinese localization files
I suggest that DBeaver rename the following two `bundle_xxx.properties` into:

* `bundle_zh.properties` -> `bundle_zh_CN.properties`
* `bundle_tw.properties` -> `bundle_zh_TW.properites` (at least modify these files)

Otherwise, the Resource Bundle of IntelliJ will identify `bundle_tw.properties` as `特威文` instead of `中文/台灣`.

image

_Originally posted by @hwhsu1231 in https://github.com/dbeaver/dbeaver/issues/19574#issuecomment-1493834426_

### PR DESCRIPTION
**Pull request by GusRiffel**
#19589 

Hi,

This is my first time participating in OSS.
I renamed the bundle_xxx.properties files as requested by @E1izabeth 
Now the files correctly display Chinese/China and Chinese/Taiwan in their names.
I built the project and it seems to be working normally.

Screenshot from 2023-06-21 20-23-47
Screenshot from 2023-06-21 22-23-31

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution.
Why did you renamed only one file? According to the issue it's supposed to rename all property files.

**Comment by GusRiffel** [comment]
Hello,

Sorry I was mislead by the part "rename the following two" in the issue description.
All files are now renamed accordingly.
Thanks

**Comment by E1izabeth** [comment]
Thank you for corrections.

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
@GusRiffel could you update the branch and resolve conflicts?

**Comment by GusRiffel** [comment]
@E1izabeth I am trying to figure out why my push has added all of the previous commits to the branch and not only my 2 diffs and the conflict resolved.

I updated my local branch by doing the following commands:
- git remote add upstream https://github.com/dbeaver/dbeaver.git
- git fetch upstream

Then before pushing I resolved the conflict by rebasing the project and accepting the modification made on the file I renamed.

That's my first time syncing a forked project, please let me know if there is anything wrong and if possible how I could fix it.

--- Update:
Fixed it. Thanks

**Comment by E1izabeth** [comment]
Thank you.

**Comment by E1izabeth** [comment]
Unfortunately, we can't accept it due to the [mentioned reason](https://github.com/dbeaver/dbeaver/issues/19589#issuecomment-1630755502). Seems we can't do this stuff as it broke localization for some users (we don't have translation for all Chinese locales).

We appreciate your contribution.

**Pull request closed without merging**
