### PR TITLE
#9526 Add support for GeoPackage geometry data

### PR DESCRIPTION
**Pull request by ShadelessFox**

### CODE REVIEW

**Comment by mbernasocchi** [comment]
@ShadelessFox do I see correctly that the support is for DML only? or did I miss something and DDL statements (like adding a geometry column) should be supported as well?

**Comment by ShadelessFox** [comment]
It's not related to DML/DDL. In SQLite, you can specify any column time even if it's not supported by SQLite.

Regarding geometry data, editing is not supported.

**Comment by mbernasocchi** [comment]
> In SQLite, you can specify any column time even if it's not supported by SQLite.

ah, thanks a lot for the quick answer I got confused by the dropdown showing only "standard" types
image

so you can basically just type `MULTIPOLYGON` in the type column and then manually run the SQL to add metadata into gpkg_contents (with meaningful numbers for min and max x and y):
`insert into gpkg_contents values ('column1', 'features','some description','sample_attribute_with_geometry','2019-02-19T10:49:06.022Z',74572.400000,6631280.000000,732294.000000,7774890.000000,3856);`

and add the column metadata into gpkg_geometry_columns

`insert into gpkg_geometry_columns values ('column1','geometry','MULTIPOLYGON',3856, 0, 0 )`

is there any plans to make this automatically for geopackages? (I looked the issue queue but could find only #9526 )

**Comment by ShadelessFox** [comment]
Besides metadata, there's data. GeoPackage uses a special binary storage format; you can't simply insert strings like `POINT(1 2)`.

In #9526, only a read-only data view was implemented. Adding editing support is a difficult task, and perhaps it's something DBeaver is not supposed to support.

**Pull request merged**
