### PR TITLE
#16408 SQL Formatting settings are not applied correctly

### PR DESCRIPTION
**Pull request by Tazhio**
Adding the feature of SQL formatting on SQL Editor.

Now it still requires the user to reopen the file.

### CODE REVIEW

**Comment by Tazhio** [comment]
Trying to fix [deaver#16408](https://github.com/dbeaver/dbeaver/issues/16408)

**Comment by E1izabeth** [comment]
Please, remove `System.out.println` and commented out code parts from your PR

**Comment by Tazhio** [comment]
> Please, remove `System.out.println` and commented out code parts from your PR

I'll do this now!

**Comment by uslss** [comment]
Query disappears after changing font or keyword case. Also, association with the database disappears after changes
dbeaver_MkY9Zr6A77

**Comment by Tazhio** [comment]
I would like to furthur working on this problem, but this bug does not appear on MacOS side. I think this feature does behave differently on different Operating Systems. 

https://user-images.githubusercontent.com/39872036/170817872-a705702d-07a6-469f-8147-02375f7976c3.mp4




> Query disappears after changing font or keyword case. Also, association with the database disappears after changes
> [ ](https://user-images.githubusercontent.com/31996417/170681746-717bc5bf-621b-4990-99fe-a48441b3a488.gif) dbeaver_MkY9Zr6A77

**Pull request closed without merging**
