### PR TITLE
Icon for JKISS in About Eclipse IDE is too small/not good

### LINKED ISSUE #18608: Add images for all Eclipse DBeaver extensions
### Description

Icon for JKISS in About Eclipse IDE is too small/not good :

image

### DBeaver Version

All

### Operating System

_No response_

### Database and driver

_No response_

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RoiSoleil**
Fix : https://github.com/dbeaver/dbeaver/issues/18608

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution.

**Comment by Matvey16** [comment]
This changes the icon only for the office extension, maybe redo it for all extensions including the base DBeaver plugin?

**Comment by RoiSoleil** [comment]
I didn't saw any other image size bug.

**Review by Destrolaric — APPROVED** [review]

**Comment by RoiSoleil** [comment]
Merge ?

**Comment by LonwoLonwo** [comment]
Hello @RoiSoleil 

Thanks for the contribution.
But we decided to use other icons for DBeaver and its extensions for the "About" dialog, current Office extension icon looks not so good. In size * 2 too. So I'm closing this PR and adding the original ticket to our planning list.

**Pull request closed without merging**
