### PR TITLE
dbeaver/pro#2082 context variables

### PR DESCRIPTION
**Pull request by serge-rider**

### CODE REVIEW

**Comment by DariaMarkaryan** [comment]
Verified

**Comment by E1izabeth** [comment]
This case doesn't work #18998

**Comment by E1izabeth** [comment]
Case sensitivity is also broken. Here I expect to get `select * from foo` query.
image

**Comment by DariaMarkaryan** [comment]
> This case doesn't work #18998

checked this case one more time - it works for me .-. checked in both CE and EE

**Comment by E1izabeth** [comment]
@DariaMarkaryan yes, you're right. I rechecked and it works for me too. Maybe I did something wrong last time.

**Pull request merged**
