### PR TITLE
#18571 Fix name completion containing struct separator (`.`)

### LINKED ISSUE #18571: Autocomplete deletes schema name
### Description

If auto-complete is used to finish fully qualified name with a name of a quoted table that has dots in it's name, the schema name gets deleted

### DBeaver Version

22.3.1

### Operating System

Any

### Database and driver

Postgres 12

### Steps to reproduce

1. Start typing a query with database name and schema name
2. Select a table with dot(s) in it's name from the proposed tables

**Expected:** Table name looks like `db_name.schema_name."TaBle.Name"`
**Actual:** Table name absorbs schema name `db_name."TaBle.Name"`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ShadelessFox**

### CODE REVIEW

**Review by LonwoLonwo — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
Still reproducible on our Postgres 12 database with table `dvdrental.public."11.24.324FFd"`

**Comment by ShadelessFox** [comment]
Can't reproduce:


https://user-images.githubusercontent.com/35821147/209829186-b6d50b32-82db-4719-a058-ef191aa0a121.mp4

**Comment by Matvey16** [comment]
Change this setting from `N/A` to any other option and it will reproduce

image

**Review by LonwoLonwo — APPROVED** [review]

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
