### PR TITLE
Add resource leak detection

### PR DESCRIPTION
**Pull request by bt90**
Register a resource leak detector via [Resource.setNonDisposeHandler(Consumer<Error>)](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fswt%2Fgraphics%2FResource.html)

Any fonts, images, etc. that aren't disposed of will trigger a warning in the log with a stack trace showing where they were originally created.

### CODE REVIEW

**Comment by bt90** [comment]
This should help in finding the culprit for issues such as #35392 or #18197.

**Comment by ask9** [comment]
This one also: #35493
Here is a full list of similar issues:
https://github.com/dbeaver/dbeaver/issues?q=is%3Aissue+is%3Aopen+No+more+handles+sort%3Aupdated-desc

**Comment by E1izabeth** [comment]
Thank you for contribution

**Comment by E1izabeth** [comment]
As far as I know, a similar behavior can be reached by adding the `-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true` flag when starting DBeaver.

**Comment by bt90** [comment]
This would also result in a Consumer being registered, but with the drawback that it doesn't use any kind of logging framework and will only print to stderr.

The overhead of having this enabled by default is limited to creating `Error` instances for each resource. I doubt that this has any measurable effect in production, while giving users a clear log message to create an issue for.

**Review by ShadelessFox — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
