### PR TITLE
#18309 Hint for certificate exception resolution on drivers download 

### LINKED ISSUE #18309: Can't install PostgreSQL drivers after clean Windows 10 reinstallation
### Description

This is first time I encounter such a problem. I installed DBeaver many times and never seen this before. 
It's Windows 10 clean install with just a couple of tools including Docker and DBeaver. After configuring some quick connection to local PostgreSQL DB, DBeaver was unable to fetch PostgreSQL drivers:

```
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

изображение

 
Network is absolutely fine, it's working, all other applications work normally. Tried with and without VPN.

dbeaver.ini:
```
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=exe
```

### DBeaver Version

Community Edition 22.2.5.202211202223

### Operating System

Windows 10 22H2

### Database and driver

PostgreSQL

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by E1izabeth**
This hint message is shown before an error message

image

### CODE REVIEW

**Review by ShadelessFox — COMMENTED** [review]
Maybe it should be an error dialog instead?

**Review by LonwoLonwo — APPROVED** [review]

**Comment by E1izabeth** [comment]
The error dialog appears right after this one. Do you think it's ok to show two error dialogs in a row? I thought about it and I'm not sure >_<

**Comment by ShadelessFox** [comment]
Maybe we can wrap the exception with this message and throw it further? This way, we will show just a single dialog that will contain both the hint and the error message.

**Review by ShadelessFox — APPROVED** [review]

**Comment by E1izabeth** [comment]
image

image

**Comment by uslss** [comment]
verified

**Pull request merged**
