### PR TITLE
#12746 Allow copying coordinates under cursor

### PR DESCRIPTION
**Pull request by ShadelessFox**
xgXwX2R1fI

### CODE REVIEW

**Comment by mkgrgis** [comment]
There is a similar instrument on http://retromap.ru/0519961_z16_55.751933,37.671840 with some useful functions.

**Comment by ShadelessFox** [comment]
Hello @mkgrgis,

We definitely don't want to draw a cross over the entire screen, but I like the idea of displaying address under the cursor.
It can be achieved with https://wiki.openstreetmap.org/wiki/Nominatim.

Or perhaps you wanted to point at some specific thing?

**Comment by mkgrgis** [comment]
Thanks for answer, @ShadelessFox ! I think copying of coordinates isn't about drawing, of course. Nominatim is really useful for special string near map, activated by a button or for leaflet `Popup`. It's hard to compose good ergonomics for me.
On [osm.org](osm.org) there is complex simple location service, not only Nominatim, see net queries by button 
изображение
and result of this queries.

**Comment by ShadelessFox** [comment]
As long as there's an open-source API for gathering such information we can implement that. The real question is do we really need such features? DBeaver is not a geologically-specialized tool, I'm not even sure if I spelled this word correctly :)
Of course small features like copying coordinates would be cool, but something else is an overkill IMO.

**Comment by mkgrgis** [comment]
I think at this moment it's important to implement simple and fast web application [with full geoJSON data model](https://github.com/dbeaver/dbeaver/issues/12244) Then it will be not a problem to add a functions like we discussed. It will be easy for me to propose implementation of some features via `leaflet.js` incl. Nominatim.

**Pull request merged**
