### PR TITLE
#35010 [CUBRID] Fixing Incorrect Drop SQL of Index

### LINKED ISSUE #35010: [CUBRID] Drop SQL of Index displays incorrectly
### Description

Since Cubrid has different syntax from Generic. So we will implement our own syntax.

Expected SQL:  `DROP INDEX test2_column1_idx ON DBA.test2;`

Actual SQL: `DROP INDEX DBA.test2_column1_idx;`

### DBeaver Version

DBeaver version 24.1.3

### Operating System

Window 10

### Database and driver

1. Database Name and Version: CUBRID 11.2
2. Driver Name and Version: CUBRID JDBC Driver 11.2

### Steps to reproduce

1. Go to navigator
2. Click on Schemas
3. Click on Indexes folder
4. Right click on one of index
5. Click on Delete

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by longhaseng52**
Since Cubrid has different syntax from Generic. So we will implement our own syntax.

Expected SQL: `DROP INDEX test2_column1_idx ON DBA.test2;`

Actual SQL: `DROP INDEX DBA.test2_column1_idx;`

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution!

**Review by E1izabeth — APPROVED** [review]

**Review by Destrolaric — APPROVED** [review]

**Comment by E1izabeth** [comment]
We passed your PR to our QA team for testing

**Comment by Matvey16** [comment]
That doesn't seem to be fixed


https://github.com/user-attachments/assets/ef056ad5-db93-4387-81e0-1e6c2f590fa5

**Comment by longhaseng52** [comment]
> That doesn't seem to be fixed
> 
>  dbeaver_01AEva8oXo.mp4

I have tested it several times on my local computer. It works well as expected. Could you please recheck it again? Thanks!

image

**Comment by E1izabeth** [comment]
We're investigating, why the build doesn't contain the required changes. The issue is in our build process

**Comment by serge-rider** [comment]
Unfortunately I had to revert the commit.
Because of 
```
<manager class="org.jkiss.dbeaver.ext.cubrid.edit.CubridIndexManager" objectType="org.jkiss.dbeaver.ext.generic.model.GenericTableIndex"/>
```

It broke all generic drivers because you mapped Cubrid-specific index manager to all generic indexes.
You need to create class CubridTableIndex (extend GenericTableIndex) and remap manager onto it.

**Comment by longhaseng52** [comment]
> Unfortunately I had to revert the commit. Because of
> 
> ```
> <manager class="org.jkiss.dbeaver.ext.cubrid.edit.CubridIndexManager" objectType="org.jkiss.dbeaver.ext.generic.model.GenericTableIndex"/>
> ```
> 
> It broke all generic drivers because you mapped Cubrid-specific index manager to all generic indexes. You need to create class CubridTableIndex (extend GenericTableIndex) and remap manager onto it.

Thank you for your comment. I will get it fix.

**Pull request merged**
