### PR TITLE
dbeaver/pro#1463 read notifications jaws

### PR DESCRIPTION
**Pull request by serjiokov**
Provided accessibility for read notifications by JAWs

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
So, will the focus now be on the notification after operation by default?

**Review by E1izabeth — APPROVED** [review]
If it's not possible without setting a focus, than ok. But I hope it's possible to stop notification reading and return focus back with Esc

**Comment by serjiokov** [comment]
The main idea is in by default the focus will not switch to notification, it is only possible when screen reader support enabled.

**Review by ShadelessFox — APPROVED** [review]

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
