### PR TITLE
#20499 activeResultsTab out of sync with resultTabs.getSelection()

### PR DESCRIPTION
**Pull request by hawthorne3341**
https://github.com/dbeaver/dbeaver/issues/20499

### CODE REVIEW

**Review by ShadelessFox — CHANGES_REQUESTED** [review]
Thanks for the contribution!

It would make more sense to fix the issue's core, not the consequence.

Take a look at where the `activeResultsTab` field is updated.

**Comment by ShadelessFox** [comment]
Please address the requested changes before this PR can be merged.

The PR will be considered stale if there will be no updates made within the month.

**Comment by hawthorne3341** [comment]
Hi @ShadelessFox my plan is to revise this pr over the weekend

**Review by ShadelessFox — CHANGES_REQUESTED** [review]
I appreciate your effort, but the issue can be fixed with two lines of code: one for updating the `activeResultsTab` when the selection changes and the second one for updating the `activeResultsTab` when a tab gets pinned/unpinned.

No need to overcomplicate things.

**Comment by hawthorne3341** [comment]
Darn, didn't make that connection. Will try to have this revised as soon as I can, hopefully third time's a charm!

**Comment by ShadelessFox** [comment]
This PR looks stale. Are you still willing to work on this PR in the near future? @hawthorne3341

**Comment by hawthorne3341** [comment]
Hi @ShadelessFox I will try to get to this before next week and will let you know if I dont have capacity to make the required fix

**Comment by hawthorne3341** [comment]
@ShadelessFox I am going to own this, stuck on some pesky build issues but going to get you the revised changes as soon as my schedule permits

**Comment by ShadelessFox** [comment]
This PR looks stale and has merge conflicts. Please finalize your changes in a new PR.

**Pull request closed without merging**
