### PR TITLE
Simple InterSystems IRIS support

### PR DESCRIPTION
**Pull request by daimor**
Resolves the issue #6289

Replaced Cache driver with IRIS, as it's compatible.
InterSystems replaced Caché with a new product IRIS Data Platform.

### CODE REVIEW

**Comment by serge-rider** [comment]
I don't think that replacing existing driver is a good idea. 
People may have existing connection configurations, they may be broken by such replacement.
I thin we just need to add the new IRIS driver.

BTW are you aware of any Maven-like repository for driver jars? We can live with direct link but it is not good in general (it doesn't allow users to upgrade driver version by themselves).

**Comment by daimor** [comment]
I've checked the replacement of cache to iris, and it works well, so I did it, and it have backward compatibility, and fortunately dbeaver uses uri, which just can be replaced. Cache will not receive any new version any way.

Unfortunately, I'm not responsible for publishing to maven, but we are working on it, and as soon as it will be published there, I'll do a new PR with the fix.

**Comment by daimor** [comment]
May it have replacement and cache driver definition at the same time?

**Comment by serge-rider** [comment]
Big number of people know Cache as Cache though. They will search for Cache, not for IRIS. 
Thus we can't just remove this old driver.

Also, we can use the same icons for both drivers.

Note: adding some Cache reference in IRIS driver description will let users to find both drivers by using quick search.

**Comment by daimor** [comment]
@serge-rider so, I've returned back Cache

**Comment by serge-rider** [comment]
Great!
Please let know when some Maven repository will be available.

**Pull request merged**
