### PR TITLE
#146 No limit on queries for update

### PR DESCRIPTION
**Pull request by codebling**

### CODE REVIEW

**Comment by codebling** [comment]
Actually I am not sure that this is the right fix for issue #146. 

This fix prevents `LIMIT` from being appended to the query string run by DBeaver, but DBeaver will still run `SET SQL_SELECT_LIMIT=x` with this fix applied. 

This will have unintended side effects for the user if the total number of rows selected by the user's query is greater than the number of rows that DBeaver wants to display (in that all of the rows > than the number of rows that DBeaver wants to display will **not** be locked). 

Probably in the case of a `FOR UPDATE`, the limiting should be disabled in `org.jkiss.dbeaver.model.DBUtils#prepareStatement`. 

What do you think?  I can make this change.

**Comment by codebling** [comment]
There are a few other cases where limiting should be disabled for `SELECT`. 

Here is the complete list: 

* `SELECT...PROCEDURE`
* `SELECT...INTO`
* `SELECT...FOR UPDATE`
* `SELECT...LOCK IN SHARED MODE`

**Comment by serge-rider** [comment]
This seems to a valid fix, thanks!

**Comment by serge-rider** [comment]
Now SELECT INTO, SELECT FOR UPDATE and LOCK IN SHARED MODE are covered by plain select detector.
Could you give me an example of SELECT...PROCEDURE query?

**Comment by codebling** [comment]
Those statement types do seem to be picked up by Jsqlparser, but when testing my fix, I found that (at least for the MySQL plugin) it still generated `SET SQL_SELECT_LIMIT=x` before the query. I think that this still affects these (`...PROCEDURE`, `...INTO`, `...FOR UPDATE`, `...LOCK IN SHARED MODE`) queries, doesn't it?  In that case it would be necessary to bypass the `SET SQL_SELECT_LIMIT=x` statement and I haven't looked into that yet. 

I have not used `SELECT...PROCEDURE` (I have tried but I've been getting an error), but it is supported by both [MySQL](http://dev.mysql.com/doc/refman/5.7/en/select.html) and [Oracle](https://docs.oracle.com/cd/E17952_01/refman-5.0-en/select.html). I haven't been able to confirm its status in the SQL standard. 

MySQL documentation states that "A PROCEDURE clause names a procedure that should process the data in the result set." 

The PROCEDURE clause is supposed to come after LIMIT
```
SELECT
...
    [LIMIT {[offset,] row_count | row_count OFFSET offset}]
    [PROCEDURE procedure_name(argument_list)]
    [INTO OUTFILE 'file_name'
        [CHARACTER SET charset_name]
        export_options
      | INTO DUMPFILE 'file_name'
      | INTO var_name [, var_name]]
    [FOR UPDATE | LOCK IN SHARE MODE]]
```

My understanding is that it should be applicable to any SELECT statement. It will simply take the results of the SELECT and send them to the named PROCEDURE, but I am not sure how this works with the PROCEDURE ins and outs. I will have to do more research.

**Pull request merged**
