### PR TITLE
dbeaver/pro#1488 Show "View Diagram" for table container nodes

### PR DESCRIPTION
**Pull request by ShadelessFox**
image

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Waiting for the UI test.

**Comment by ShadelessFox** [comment]
@LonwoLonwo

https://user-images.githubusercontent.com/35821147/236800080-a5d18ae0-d6da-47bc-b6e3-4d03ff36c8ee.mp4

**Comment by LonwoLonwo** [comment]
Ok, let's create a meeting one more time to discuss it 🙄

**Review by E1izabeth — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
