### PR TITLE
Added some new italian localizations

### PR DESCRIPTION
**Pull request by capitanfuturo**

### CODE REVIEW

**Comment by serge-rider** [comment]
Thank you for the contribution 👍

**Comment by E1izabeth** [comment]
Hi, @capitanfuturo! Could you, please, remove from `^M` at the end of lines?

**Comment by capitanfuturo** [comment]
Hi @[E1izabeth](https://github.com/E1izabeth) no problem! Thank you

**Comment by serge-rider** [comment]
Also please remove changes in `DBeaver.product.launch` as it is unrelated to localization

**Comment by DariaMarkaryan** [comment]
Verified

**Pull request merged**
