### PR TITLE
Add CrateDB variant of PostgreServer to improve compatibility

### PR DESCRIPTION
**Pull request by proddata**
Hi D🦫 Team,

We traditionally recommended to used the standard PostgreSQL driver for CrateDB due to its increasing compatibility. However, we have been made aware that some [recent changes in DBeaver have impacted this compatibility.](https://github.com/crate/crate/issues/14395)

To remedy this and improve user experience, we are proposing a new pull request for the addition of a CrateDB variant to the PostgreSQL connector.

This PR provides the base implementation, designed to adjust to CrateDB features while retaining essential PostgreSQL driver functionalities. Also this moves the generic CrateDB connector using the CrateDB specific JDBC Driver to legacy, as with recent CrateDB versions the default recommendations is to use the standard PostgreSQL JDBC Driver.

Best,
Georg from Crate.io

**Screenshots**:

image

image

image

### CODE REVIEW

**Review by ShadelessFox — COMMENTED** [review]
Thanks for the contribution!

I expect white icons to be practically invisible on a light theme.

Please add a contrasting background or border.

**Comment by proddata** [comment]
> I expect white icons to be practically invisible on a light theme.
> 
> Please add a contrasting background or border.

Thanks for the feedback. I didn't think about light teams initially.
Changed the icons to standard CrateDB blue, which should work with both light and dark themes.

Dark
image
image

---

Light
image
image

image

**Review by ShadelessFox — APPROVED** [review]
👍🏻

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Looks nice. Thanks for the contibution!

**Review by E1izabeth — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Hello @proddata 

We have a question now. Do we need to keep the Legacy CrateDB version? Any specific reason for that?

**Comment by proddata** [comment]
> Hello @proddata
> 
> We have a question now. Do we need to keep the Legacy CrateDB version? Any specific reason for that?

Only with CrateDB 5.x (Released on 2022-07-11) and up the PostgreSQL compatibility imho was good enough to use it with the standard PG connection. We still see many 4.x and 3.x clusters around. While those versions are not officially supported anymore one would cut out those users.

So optimally one would keep it around for a few more months (maybe end year) and then sunsets the legacy version. However I would also understand if you would want to remove it right away.

**Comment by LonwoLonwo** [comment]
Ok. Thanks. Can we also use a new icon image for the old driver?

**Comment by proddata** [comment]
> Ok. Thanks. Can we also use a new icon image for the old driver?

Sure, should they be copied to the generic folder or referenced?

**Comment by LonwoLonwo** [comment]
Yes, please change the icon (not the logo) in the generic bundle, and in the postgres bundle use:

```
icon="platform:/plugin/org.jkiss.dbeaver.ext.generic/icons/cratedb_icon.png"
iconBig="platform:/plugin/org.jkiss.dbeaver.ext.generic/icons/cratedb_icon_big.png"
```

**Comment by proddata** [comment]
> Yes, please change the icon (not the logo) in the generic bundle, and in the postgres bundle use:

done ✅ 

image
image

**Comment by LonwoLonwo** [comment]
M. No. The point was to avoid od duplicating images in DBeaver. 
So, You need to remove icons in the PG bundle and change the path to icons like in the example

**Comment by proddata** [comment]
> M. No. The point was to avoid od duplicating images in DBeaver. So, You need to remove icons in the PG bundle and change the path to icons like in the example

Ah, sorry for the misunderstanding 🙈  
Should be fixed now.

**Comment by LonwoLonwo** [comment]
Yes, that's better, thanks!

**Comment by uslss** [comment]
verified

**Pull request merged**
