### PR TITLE
dbeaver/dbeaver#22383 Virtual entity edit dialog fix

### LINKED ISSUE #22383: 23.3.2 custom unique key no response
### Description

Today morning, I just updated my DBeaver from [23.3.1] to [23.3.2], and I was operating a new table. I did not set an unique key, so when I tried to save my edits, it failed and remind me set an unique key. When I click the button "custom unique key", it is no response. Even though I set it using SQL command in console, it still was not effective. After I downgraded into [23.3.1], everything worked fine.

### DBeaver Version

Community Edition 23.3.2

### Operating System

macOS Sonoma 14.0 (23A344)

### Database and driver

1. Database name and version: PostgreSQL 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
2. Driver name and version: PostgreSQL 14.10 (Homebrew)

### Steps to reproduce

1. create a new table
2. edit some data
3. try to save
4. it will pop up a window remindering you to set a unique key, just click it and nothing will happen

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by serge-rider**

### CODE REVIEW

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Maybe it is better to fix the issue with "select all" button in this PR. Clicking on it still leaves "OK" button unclickable even though columns are selected

https://github.com/dbeaver/dbeaver/assets/82543000/244b9c88-9e8b-4133-814a-2fcc9d4c2598

**Comment by serge-rider** [comment]
In this dialog we don't want to disable OK button. Because it is a valid behavior if user want's to leave virtual PK empty.
But change some settings in other tabs.

**Comment by ShadelessFox** [comment]
Please also test https://github.com/dbeaver/pro/issues/2337

**Comment by ShadelessFox** [comment]
Please also test https://github.com/dbeaver/pro/issues/2337

**Comment by Matvey16** [comment]
Verified for both cases

**Pull request merged**
