### PR TITLE
support HANA proactive and forced password change (#15617,#22206)

### LINKED ISSUE #15617: Allow password change on login if forced
#### System information: 
- Windows
- DBeaver Community Version 21.3.4.202202051448

#### Connection specification:
- SAP HANA 2
- JDBC

#### Describe the problem you're observing:
If password is required to be reset due to password expire, this cannot be done by DBeaver because initial login is not possible .

#### Steps to reproduce, if exist:
As an admin, reset the password for a certain user. When the user now tries to login, he is required to reset the password. This cannot be done via DBeaver. I have to log in via SAP HANA Studio.

### LINKED ISSUE #22206: Support force password set on login for SAP HANA
A user can be forced to set a new password on login e.g. when password has been reset by support or if password expired. In case of such a situation DBeaver let you no longer login to the SAP HANA database and shows following error message.

`SAP DBTech JDBC: [414]: user is forced to change password: alter password required for user`

image

Instead of the error message, a dialog should be shown to set a new password. 

As a work around I need to login using SAP HANA Studio and set a new password. Then I can go back to DBeaver. Would be fantastic if DBeaver could support password set during login, so that I don't need to work with SAP HANA Studio anymore.

### PR DESCRIPTION
**Pull request by kai-morich**

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution!

**Review by E1izabeth — APPROVED** [review]

**Comment by kai-morich** [comment]
If you would like to test you could do:

```sql
CREATE usergroup day1 SET PARAMETER 'minimal_password_length'='6','last_used_passwords'='0','minimum_password_lifetime'='0','maximum_password_lifetime'='1','password_expire_warning_time'='0';
CREATE usergroup day2 SET PARAMETER 'minimal_password_length'='6','last_used_passwords'='0','minimum_password_lifetime'='0','maximum_password_lifetime'='2','password_expire_warning_time'='1';

CREATE USER test1 password Abc123 SET usergroup day1;
CREATE USER test2 password Abc123 SET usergroup day2;

-- create connections for above users
-- initial password change handled by DBeaver

ALTER USER <user_name> FORCE PASSWORD CHANGE

-- forced password change handled by DBeaver

-- wait a day

-- expired password handled by DBeaver
-- expire warning shown by DBeaver
```

**Review by ShadelessFox — APPROVED** [review]

**Comment by ShadelessFox** [comment]
We passed the PR to our QA team for further testing.

**Comment by kai-morich** [comment]
Any update?

**Comment by ShadelessFox** [comment]
I'm sorry it's taking so long. We currently have an overwhelming number of tickets waiting for our QA team to be reviewed.

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
