### PR TITLE
#15858 find routine by id and change it name to full name

### LINKED ISSUE #15858: error in priviliges describe. Priviliges on procedure
Postgresql 12
Dbeaver 22.0.0

1. added any symbols 

_209868
_29481
...
to the end of procedure name

image

2.
dbeaver generated this priviliges script

image

but 'backups.del_proc_get_notice_statistics' it is not a function!!
image

it is procedure. Script is wrong.

### PR DESCRIPTION
**Pull request by LonwoLonwo**
in permissions role tab

2022-08-02 08_53_59-DBeaver Ultimate 22 1 4 - pg_monitor

! Please check Redshift and Greenplum

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
EE PR https://github.com/dbeaver/dbeaver-ee/pull/1829

**Comment by uslss** [comment]
procedure is mentioned as function in role ddl
image

**Comment by uslss** [comment]
also permission isn't shown for user in Redshift
image

**Comment by uslss** [comment]
verified

**Pull request merged**
