### PR TITLE
#22489 Add smart mode for blank line is a statement delimiter setting

### LINKED ISSUE #22489: Blank line as statement delimiter ambiguity
**Is your feature request related to a problem? Please describe.**
I saw the other day a blog post of a guy who broke his database because on how dbveaber delimits queries when pressing ctrl + enter
[https://zaidesanton.substack.com/p/how-i-destroyed-the-companys-db](https://zaidesanton.substack.com/p/how-i-destroyed-the-companys-db)

He had a code like this:
**UPDATE orders**
**SET is_deleted = true**

**WHERE id in (1,23)**

And he pressed ctrl + enter on the first line, so the "where" clause was not taken into account, the result was updating the whole table.

**Describe the solution you'd like**
When we hit ctrl + enter, blank lines should not be a delimiter to see where the query ends, I think that it should be ";" that is the standard of the sql syntax.

**Describe alternatives you've considered**
If we still want to use blank line as delimiter, the UI should ask to resolve the ambiguity if it detects that you are about to run more than one query or make a preview of what is about to be executed when it is not clear.

**Additional context**
These are the comments on reddit about this guy, it is interesting to read: [https://old.reddit.com/r/programming/comments/18vdmq5/how_i_destroyed_the_companys_db_stupid_sql_mistake/](https://old.reddit.com/r/programming/comments/18vdmq5/how_i_destroyed_the_companys_db_stupid_sql_mistake/)

### PR DESCRIPTION
**Pull request by E1izabeth**
image

### CODE REVIEW

**Comment by MashaKorax** [comment]
Looks like Smart mode is not working (tested on SQLite)
iScreen Shoter - DBeaver Community - 240402143423
iScreen Shoter - DBeaver Community - 240402143501

**Comment by E1izabeth** [comment]
I can't reproduce. It works for me
image

Please provide more details and logs

**Comment by MashaKorax** [comment]
Mac issue

**Comment by E1izabeth** [comment]
It's not intended to inspect the text before the active query - only after. So, if you put the cursor to the end of the WHERE statement and separated this where statement with a blank lines, we will not try considering to check if this WHERE could be added to something that goes before - we check only after.

**Comment by MashaKorax** [comment]
Option **Never** is not working

iScreen Shoter - 20240410124536405

**Comment by MashaKorax** [comment]
verified

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
