### PR TITLE
#17763 add special condition before displaying the statistics tab

### LINKED ISSUE #17763: Statistics tab always becomes active when running a SQL script
### Description

This is related to a previously closed ticket  https://github.com/dbeaver/dbeaver/issues/7704.

The issue had resurfaced in the past 3 releases, still happening in the current 22.2.1 release.  Whenever one executes a script having a variable (or more than SQL statements), the Statistics tab will be displayed first.  One has to click on the Result tab to actually see the result.  And to make it worse, if one has to scroll down in the data editor and fetch more rows, it would jump back to the Statistics tab every time more rows are retrieved, very annoying.  Would appreciate it greatly if this can be fixed soon.  Thanks!

### DBeaver Version

Community edition 22.2.1 (and previous 2 releases)

### Operating System

Windows 10 Pro.

### Database and driver

Oracle ojdbc8 and orai18n.

### Steps to reproduce

@set myvar='foo'
select * from my_table
where name= :myvar
order by id;

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LonwoLonwo**
2022-11-30 22_54_49-DBeaver Ultimate 22 3 0 - _postgres_ Script-86

2022-11-30 23_02_20-DBeaver Ultimate 22 3 0 - _postgres_ Script-86

Also, please check 

- [ ] some different types of queries, 
- [ ] as a script, 
- [ ] as opening in the new tab, 
- [ ] with variable, 
- [ ] selects, 
- [ ] updates, 
- [ ] creates.
- [ ]  And check the #16605 ticket, if it still works well.
- [ ] And this case: https://github.com/dbeaver/dbeaver/issues/17763#issuecomment-1261512513

### CODE REVIEW

**Comment by E1izabeth** [comment]
Does it solve the issue shown in this video https://github.com/dbeaver/dbeaver/issues/17763#issuecomment-1261512513 ?

**Comment by LonwoLonwo** [comment]
I'm definitely sure that logic is like this here:

2022-11-30 22_54_49-DBeaver Ultimate 22 3 0 - _postgres_ Script-86

But I will add it to the cases list

**Review by E1izabeth — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Review by Destrolaric — APPROVED** [review]

**Comment by DariaMarkaryan** [comment]
Verified

**Comment by briandhuff** [comment]
Still happening to me on scripts that do not have a results tab to display.
BUT only on the second + time the script is run.
First time works as expected

Version 22.3.1.202212251901
DB: MS SQL Server

Steps to recreate:

Open New Script
Connect to DB connection if needed
Add to script:    PRINT 'statistics tab will show'

Run script the first time, Statistics and Output window show with Output as the tab in focus

Run script again, Statistics will now be the tab in focus and will continue to be on all other script execution

**Pull request merged**
