### PR TITLE
3085 sql completion performance

### PR DESCRIPTION
**Pull request by serge-rider**

### CODE REVIEW

**Comment by E1izabeth** [comment]
Please check New completion engine too

**Comment by E1izabeth** [comment]
How to test:

0. Open Query Manager
1. Type `select * from `
2. Continue typing the name of the table, that doesn't exist in the database, for example, `qpeieqiqri`
4. Observe, that every new key pressed cause DBeaver to send query to the database

If you can't reproduce, try some database without schemas.

**Comment by E1izabeth** [comment]
On typing in SQLite
image

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
