### PR TITLE
dbeaver#35815 Add execute time in statistics result

### LINKED ISSUE #35815: Statistics result - add elapsed time
Hi, 
My suggestion is for the statistics result when ran a SQL , multiples SQLs , procedures, etc is add the elapsed time. 
Today they show only the start / finish time , however if want to know in seconds / minutes / hour how much time took the execution need to manually calculate theses finish / start time.. 

image

### PR DESCRIPTION
**Pull request by tlm365**
Closes #35815.

*minor: harmonize stats result between single and multi-statement.

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]
Thank you for contribution!

**Review by ShadelessFox — APPROVED** [review]

**Comment by ShadelessFox** [comment]
Thanks for the contribution! Passing the PR to our QA team now.

**Comment by ShadelessFox** [comment]
Why did you close it? Unfortunately, we have a lot of tickets. Your changes would have been tested and merged eventually.

**Comment by tlm365** [comment]
> Why did you close it? Unfortunately, we have a lot of tickets. Your changes would have been tested and merged eventually.

Oops, apologies for the error during the fork repository cleanup. I have reopened it. TYSM.

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
