### PR TITLE
Added support for SQream DB via the generic JDBC connector.

### PR DESCRIPTION
**Pull request by arnons1**
Added support for SQream DB via the generic JDBC connector implement.

Added JDBC template, JDBC download URL, and icons.

Compiled and tested.

### CODE REVIEW

**Comment by serge-rider** [comment]
This looks good, thanks.

However plain http link on the driver jar is dangerous. We don't use any plain http links on drivers anymore as it can be used to hack end-user machine and get access to end-user data.

Is there any https link on the driver? 
Public Maven repository would be even better as it lets to upgrade driver version transparently.

**Comment by arnons1** [comment]
I'm still waiting on the Maven repos. Do you want to wait until that's done to merge this? It could be a couple of more weeks.

Side note: Any site can be be compromised and have files replaced. HTTPS isn't necessarily going to help with that. That's just the "MITM" aspect of it :)

**Comment by serge-rider** [comment]
Yeah, we can wait.
Maven repo is not a strict requirement but https is.

Agreed about sites compromising, but MITM is so popular and easy that we can't take this risk. It compromises all sites and all users, that's why we have this rule.

**Comment by arnons1** [comment]
Hey @serge-rider - I updated the URL to resolve from Maven.

It resolves fine and finds the driver

**Comment by serge-rider** [comment]
Great. It will be added in 7.1.1 (as 7.1 branch is already frozen)

**Comment by serge-rider** [comment]
@arnons1  Small icons (16x16 and 32x32 are completely unreadable). Do you have any small icons adoptation?

**Comment by arnons1** [comment]
I can try to replace the icons. Should I open a new PR for that?

**Comment by serge-rider** [comment]
Yes, new PR will be perfect.

**Comment by kseniiaguzeeva** [comment]
@arnons1 Have you had a possibility to try to improve the icons view? It would be perfect to have them in the next release.

Thank you in advance,

**Comment by arnons1** [comment]
> @arnons1 Have you had a possibility to try to improve the icons view? It would be perfect to have them in the next release.

Created a new PR - #9007.

**Comment by kseniiaguzeeva** [comment]
Checked

**Pull request merged**
