### PR TITLE
#9444 NPE fixed

### PR DESCRIPTION
**Pull request by plotn**
Unfortunally, there appeared NPE during refactoring. Now it is ok.

### CODE REVIEW

**Comment by plotn** [comment]
@serge-rider , merge please, because devel is unstable when objects in tree searched

**Comment by E1izabeth** [comment]
Please provide NPE stack trace, which you are trying to fix.

**Comment by serge-rider** [comment]
It happens every time you type a dot after a schema name. Somehow we missed this issue.
@plotn thanks for the fix

**Comment by plotn** [comment]
thank you collegues, and I am sorry for this

**Pull request merged**
