### PR TITLE
Issue 1089 work in progress version of adding a new menu item

### PR DESCRIPTION
**Pull request by halitanildonmez**
Hello! I have been working on this issue: https://github.com/dbeaver/dbeaver/issues/1089

I managed to add a basic functionality yet I am not sure at the moment if I am following the guidelines to add such a thing properly. 

Though here is a WIP of the feature. Note that it is not done but I wanted to share the current work and get some feedback and hopefully amend my mistakes sooner than later.

Also the https://github.com/dbeaver/dbeaver/blob/devel/.github/CONTRIBUTING.md file seems to be empty.

### CODE REVIEW

**Comment by halitanildonmez** [comment]
I have fixed the styling issues and this is no longer WIP (I hope 😄 ) 

@serge-rider will you be proceeding with this PR ? Should some one else test it ? 

Is google the default search engine ? Should that be a property user can modify ? 

If you do not want to continue with this or something else I can close this PR since it has been open for a long time 😄

**Comment by serge-rider** [comment]
Thanks for the contribution!
I like the idea, it can be very handy.

What I don't like:
- It is in the core plugin. It'd be better in org.jkiss.dbeaver.ui.editors.sql
- The action is contributed in the SQL editor context menu. Which is already too heavy. Perhaps we need some sub-menu with SQL tools. And put all tools there. Like this one or UUID generator or text formatter/morpher.

**Comment by halitanildonmez** [comment]
I can absolutely do those! 

This was my first swing with dbeaver code so apologies for the silly mistakes 😄 

Yet if you like it I can update the code.

Question about sub-menu with SQL tools: do you mean creating a new package ? I am going to investigate but if you already have an opinion I can do that! 

Thanks again for the input!

**Comment by halitanildonmez** [comment]
I have moved the plugin from core, it should fix the first point, 

going to investigate the second point as I am still not sure what I have to do 😄

**Comment by serge-rider** [comment]
Unfortunately it doesn't compile now.
See https://github.com/dbeaver/dbeaver/pull/9100/checks?check_run_id=1227939790

**Comment by halitanildonmez** [comment]
@serge-rider Thanks for looking! 

It was a strange thing, I have java 11 in the path and that was the problem. 

It looks better now though 😄 Let me know if there is something else I need to fix!

**Comment by serge-rider** [comment]
Now it looks much better 👍 
A few other notes:
- Use https protocol for google links
- Trim selected text
- Use UIUtils.launchProgram(URL) instead of native Java AWT utility.

**Comment by halitanildonmez** [comment]
@serge-rider thanks again! Hope this looks better now ?

**Comment by serge-rider** [comment]
We'll include it in 7.2.5 version. 
Thank you!

**Pull request merged**
