### PR TITLE
Update timescale branding

### PR DESCRIPTION
**Pull request by mathisve**
Timescale did a rebrand last month in which their logo changed. This PR reflects those changes to the logo. [Here](https://www.timescale.com/blog/announcing-the-new-timescale/) is a link to the official Timescale website announcing the rebrand.

I have sized the images to be the exact same dimensions as the previous ones. Except for the `timescale_logo.png`, the dimension ratio changed slightly which causes the height to be a couple pixels more.

Thank you.

### CODE REVIEW

**Comment by ShadelessFox** [comment]
I expect the readability of these icons to be bad on the dark theme. A tiny border around every icon can improve the situation.

**Comment by mathisve** [comment]
That's a good point!
The logo is transparent, so should the background be white in addition to the white border?

**Comment by ShadelessFox** [comment]
Yes, I think so. You can play with variations to see which fits best.

**Comment by mathisve** [comment]
Hi, sorry for the immense delay!

I have added a white background to the transparent Timescale logos!

As for the banner since it is only shown (to my knowledge) in the db configuration tab, it looks great even without a border.

**Review by ShadelessFox — APPROVED** [review]
Indeed, the banner looks okay as-is. 👍🏻

**Review by E1izabeth — APPROVED** [review]

**Comment by uslss** [comment]
verified

**Pull request merged**
