### PR TITLE
update dameng driver version,add categories

### PR DESCRIPTION
**Pull request by Stkai**
Update to the latest  dameng driver.add categories

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Hello @Stkai 

What do we need to test with the latest Dameng driver version? Maybe some changes? Are some bugs fixed or?

**Comment by Stkai** [comment]
> Hello @Stkai
> 
> What do we need to test with the latest Dameng driver version? Maybe some changes? Are some bugs fixed or?

It is not necessary to update the driver. Previously, the Dameng driver did not have a category and could not be found in the category.

**Comment by LonwoLonwo** [comment]
> It is not necessary to update the driver.

I'm talking about this update that you made: `8.1.3.62`.
Do we need to check something related to the updated driver?

**Comment by Stkai** [comment]
> > It is not necessary to update the driver.
> 
> I'm talking about this update that you made: `8.1.3.62`. Do we need to check something related to the updated driver?

Sorry. I misunderstood, No testing required

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
