### PR TITLE
#17326 try execute recover for generators

### LINKED ISSUE #17326: Automatic reconnect does not work for menu functionality (such as Generate DDL)
### Description

When a script window loses connectivity, it will automatically reconnect when I execute a new statement. However, when a connection has timed out and I select Generate SQL => DDL from a database object's context menu, an error message will pop up saying that the connection is invalid:
image
When I close it with clicking ok, an empty window pops up:
image
There is no point in showing an empty window when the connection fails.

I'd expect the connection to automatically be restored or at least the empty window not to pop up.

### DBeaver Version

22.1.4

### Operating System

Windows 10 x64

### Database and driver

Azure SQL

### Steps to reproduce

Connect to a DB
Expand the table tree view
let the connection time out
right click a table => Generate SQL => DDL
error message will pop up
empty window will pop up

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Destrolaric**
Closes #17326 
Acceptance:
When connection lost generator dialog will try to revalidate datasource until try limit or success reached

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
DDL is generated but error log still continues to be populated with errors saying "This connection has been closed"

**Comment by Destrolaric** [comment]
The issue with connection invalidation happens for other parts of DBeaver. Unfortunately, several still unresolved tickets describe the issue @Matvey16 mentioned. For additional information, https://github.com/dbeaver/dbeaver/issues/6903 and https://github.com/dbeaver/dbeaver/issues/12559 could be looked

**Comment by serge-rider** [comment]
Why do you think that #6903 has the same nature? Any ideas how to fix it?

**Comment by Destrolaric** [comment]
> Why do you think that #6903 has the same nature? Any ideas how to fix it?

The issue was reproduced for Oracle by @Matvey16, and it has the same problematic behaviour as Postgre, the issue, for example, is not reproducable for Maria and MySQL. I previously have tried to fix Postgre issues, but unfortunately have no idea where to look.

**Comment by Matvey16** [comment]
I'm not sure that it is connected with #6903 too.
My idea is that the issue in #12559 is causing the current bug in this fix for postgres. And we were not able to consistetly reproduce that issue previously, but now we can, because I see a problem in the fact that DBeaver somehow continues to try reusing already lost connection even after reconnect.
I think that even if we can fix current issue in this PR with some crutches it is better to fix the main problem in #12559 while it is possible to reproduce it

**Comment by Destrolaric** [comment]
@Matvey16 As discussed, I am returning this for QA, the bugs related to sockets are unfortunately DBeaver wide and this ticket unfortunately also affected by them.

**Comment by E1izabeth** [comment]
IMHO we can't accept this PR in the current state. That bug should be fixed first then.

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
