### PR TITLE
Fix:  SQL Server: Source tab is empty in the index properties #13529

### LINKED ISSUE #13529: SQL Server: Source tab is empty in the index properties
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.5 EA

#### Connection specification:
- Database name and version: SQL Server Azure
#### Steps to reproduce, if exist:
Open a table clustered index in Metadata Editor

**Expected**: Source tab has Index DDL
**Actual result**: the Source tab is empty.
dbeaver_wuaK5Era1S

### PR DESCRIPTION
**Pull request by HansenChristoffer**
dbeaver/dbeaver#13529

### CODE REVIEW

**Comment by HansenChristoffer** [comment]
After change:
image

**Comment by LonwoLonwo** [comment]
Hello @HansenChristoffer 

Thanks for your contribution.

We will take a look at it.

**Comment by LonwoLonwo** [comment]
For QA Team:
Please check different index types: unique/non-unique, primary/non-primary, columnstore etc.
Azure and SQL Server

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
