### PR TITLE
Added option to skip bind values during multi-row insert

### PR DESCRIPTION
**Pull request by deepaksenthilkumar**
Has changes for the below feature request
https://github.com/dbeaver/dbeaver/issues/13498

Thanks, @ShadelessFox for providing the approach. I have implemented the same.

### CODE REVIEW

**Comment by deepaksenthilkumar** [comment]
Hi @LonwoLonwo 

I noticed @akilovich mentioned in another OceanBase plugin thread that he would be on a vacation.

Do you know tentatively when you would be able to review this PR and which release this can be target to be released on? 

It will be a huge performance improvement for our end users who are using DBeaver to access Redshift.

**Comment by serge-rider** [comment]
Generally looks good. I think that we may enable this parameter by default for some drivers (like Redshift).

I'll review it in details later this week.

**Comment by deepaksenthilkumar** [comment]
@serge-rider  Thanks.

**Comment by serge-rider** [comment]
Let's merge it. We can improve UIX later.

**Pull request merged**
