### PR TITLE
#9826 - add missing French translation 

### LINKED ISSUE #9826: i18n panels not fully translated
#### System information: 
- Windows (not tested on other platforms but might be the same)
- 7.2
- Additional extensions

#### Connection specification:
- PostgreSQL but not relevant

#### Describe the problem you're observing:
In French versions, many terms remain in English. I can not find in which bundles terms are defined

examples hereafter (English terms are highlighted)
image

Can help if needed.
Thanks

### PR DESCRIPTION
**Pull request by KawtharAlakri**
Fixing #9826

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution.
We will review your PR and let you know if some corrections are needed.

**Review by E1izabeth — CHANGES_REQUESTED** [review]
Please remove unintended changes to pom.xml and DBeaver.product.launch

**Comment by KawtharAlakri** [comment]
> Please remove unintended changes to pom.xml and DBeaver.product.launch

done !

**Review by ShadelessFox — APPROVED** [review]

**Comment by ShadelessFox** [comment]
@KawtharAlakri you have conflicts in your PR. Please fix them.

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
We passed your PR to our QA team for testing

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
