### PR TITLE
#19208 BLOB value read/export fix

### LINKED ISSUE #19208: Cell value becomes NULL after BLOB export
### Description

**Note: export settings Selected row only and Selected column only should be checked.**

https://user-images.githubusercontent.com/28875055/221645793-c00814bb-8868-4528-bf43-136cf418b499.mp4

### DBeaver Version

DBeaver 22.3.5

### Database
Oracle 12

### PR DESCRIPTION
**Pull request by serge-rider**

### CODE REVIEW

**Comment by uslss** [comment]
still reproducible
https://user-images.githubusercontent.com/31996417/221832678-cbe01084-f94a-46d3-a8e9-563c14a37372.mp4

**Comment by serge-rider** [comment]
Is there anything in log file?

**Comment by uslss** [comment]
seems it is nothing in log
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10850647/dbeaver-debug.log)
reproducible only with the "selected column/row only" options checked

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Pull request merged**
