### PR TITLE
Issue 9306: Fixed object parser to support multi-dimensional array for viewer

### PR DESCRIPTION
**Pull request by llama90**
#9306  

query panel

query result panel

### CODE REVIEW

**Comment by serge-rider** [comment]
Thanks!

We'll to add unit tests for PG structs/arrays parser. It become too complicated.

**Comment by hsseo0501** [comment]
Hi, @serge-rider This issue will be resolved by yourself? 

if that is right, I will try to find other issues for contribution.

**Comment by serge-rider** [comment]
I'll merge this PR after we'll add several unit tests. And then close #9306

**Comment by hsseo0501** [comment]
@serge-rider Thank you for your reply.

**Comment by serge-rider** [comment]
We did it in a bit different way in #9398

**Pull request closed without merging**
