### PR TITLE
#19541 add data types from dialect (with aliases) to local data types

### LINKED ISSUE #19541: Unable to select "bigint" as column target type when using data import to create a new table.
### Description

When using "Import Data" to auto-create a new table, if you try to change the target column type, "bigint" is not an option.

image

### DBeaver Version

Community Edition 23.0.1.202303250535

### Operating System

Windows 10

### Database and driver

PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1)
PostgreSQL JDBC Driver 42.5.0

### Steps to reproduce

Right click a schema name -> Import Data
Select a file to import -> Next
On "Tables mapping" screen, select "Configure", and under "Target Type", **bigint** will not be an option.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LonwoLonwo**
2023-04-26 15_08_19-Configure metadata structure

### CODE REVIEW

**Comment by MashaKorax** [comment]
In Db2 database this error occured when I do import data from CSV file and configure column to bigint
`com.ibm.db2.jcc.am.SqlSyntaxErrorException: An unexpected token "BIGINT" was found following "(50), 
 PRODUCTCOUNT".  Expected tokens may include:  "BINARY".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.31.10
	at com.ibm.db2.jcc.am.b7.a(b7.java:810)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k_.c(k_.java:2844)
	at com.ibm.db2.jcc.am.k_.d(k_.java:2828)
	at com.ibm.db2.jcc.am.k_.b(k_.java:2188)
	at com.ibm.db2.jcc.t4.ab.k(ab.java:444)
	at com.ibm.db2.jcc.t4.ab.c(ab.java:102)
	at com.ibm.db2.jcc.t4.p.b(p.java:38)
	at com.ibm.db2.jcc.t4.av.h(av.java:124)
	at com.ibm.db2.jcc.am.k_.ak(k_.java:2183)
	at com.ibm.db2.jcc.am.k_.a(k_.java:3387)
	at com.ibm.db2.jcc.am.k_.e(k_.java:1135)
	at com.ibm.db2.jcc.am.k_.execute(k_.java:1114)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistAction(DBExecUtils.java:357)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistActions(DBExecUtils.java:339)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferUtils.executeDDL(DatabaseTransferUtils.java:477)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetTable(DatabaseTransferConsumer.java:689)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetDatabaseObjects(DatabaseTransferConsumer.java:650)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.startTransfer(DatabaseTransferConsumer.java:617)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.lambda$1(DTTaskHandlerTransfer.java:123)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)`

**Comment by LonwoLonwo** [comment]
Can't reproduce with BIGINT type (or int8) from PostgreSQL to DB2 - target type doesn't have precision by default.

2023-05-02 14_44_56-Configure metadata structure

2023-05-02 14_45_05-Configure metadata structure

2023-05-02 14_45_28-DBeaver Asya  23 0 4 - NUMERICS_INT_TEST

**Comment by LonwoLonwo** [comment]
BIGINT and other default types were removed from the attributes mapping list for Oracle, SQL Server, SQLite and DB2

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
