### PR TITLE
Add ability to use byte length instead of a string length for column length as an Yes/No option in import

### PR DESCRIPTION
**Pull request by deepaksenthilkumar**
Fix for #13611 

Made it generic!

### CODE REVIEW

**Comment by ShadelessFox** [comment]
But this fix only applies to CSV importer, what about other importers?

**Comment by deepaksenthilkumar** [comment]
What other importers are there? I didn’t look at them. But can add there as
well. I was going by usage of Column Length. Didn’t find those constants
used elsewhere.--
SD

**Comment by ShadelessFox** [comment]
There's also XLSX, XML and data transfer from other table (the latter is the most interesting one, but I doubt we should select sample the data just to figure its max length).

**Comment by deepaksenthilkumar** [comment]
I didn’t realize you had xlsx import in the community edition. Do you have
it?

I will look into it.

**Comment by ShadelessFox** [comment]
Nope, we don't, sorry!

**Comment by deepaksenthilkumar** [comment]
So, only the csv data importer I suppose. And we wouldn’t check sample
length when we take it from another database.

**Comment by deepaksenthilkumar** [comment]
@ShadelessFox-Should I do anything else then?

**Comment by ShadelessFox** [comment]
I think that's it, then.

**Pull request merged**
