### PR TITLE
#15177 fix wrong variable preference

### LINKED ISSUE #15177: Disabling SQL parameters also disables SQL variables
#### Describe the issue you're observing:
In SQL Processing, we have two checkboxes, `Enable SQL parameters` and `Enable SQL variables`. If parameters are disabled, DBeaver stops parsing variables even if the second checkbox is ticked.

#### Steps to reproduce:
- Untick `Enable SQL parameters`
- Tick `Enable SQL variables.`
- Try to create a variable with ${}
- Variable is not parsed

### PR DESCRIPTION
**Pull request by Destrolaric**
Closes #15177

### CODE REVIEW

**Comment by E1izabeth** [comment]
Shouldn't we check for both options like `...&& (prefs.getBoolean(ModelPreferences.SQL_PARAMETERS_ENABLED) || prefs.getBoolean(ModelPreferences.SQL_VARIABLES_ENABLED))` instead removing the check for `prefs.getBoolean(ModelPreferences.SQL_PARAMETERS_ENABLED)`?

**Comment by Destrolaric** [comment]
> Shouldn't we check for both options like `...&& (prefs.getBoolean(ModelPreferences.SQL_PARAMETERS_ENABLED) || prefs.getBoolean(ModelPreferences.SQL_VARIABLES_ENABLED))` instead removing the check for `prefs.getBoolean(ModelPreferences.SQL_PARAMETERS_ENABLED)`?

I didn't remove it, I moved it inside the function itself.

**Comment by E1izabeth** [comment]
Do you mean this `if (syntaxManager.isParametersEnabled())`?

**Comment by Destrolaric** [comment]
> Do you mean this `if (syntaxManager.isParametersEnabled())`?

Yes

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
