### PR TITLE
dbeaver/pro#2574 Support nested rows in grid

### PR DESCRIPTION
**Pull request by ShadelessFox**
image

Nested values don't support editing.

### CODE REVIEW

**Review by E1izabeth — COMMENTED** [review]
I suppose, at least these cases should be tested to check that we don't break something

- [ ] #17467
- [ ] #17248
- [ ] #17031
- [ ] #18644
- [ ] #17016
- [ ] #15429
- [ ] #14594
- [ ] #14327

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
Now bottom level objects in arrays have expand button that doesn't do anything. Is it expected?

https://github.com/dbeaver/dbeaver/assets/82543000/90bf6f99-622b-486b-9782-504710037d1f

**Comment by Matvey16** [comment]
The expand button disappeared from the grid cells in Dynamo, now it is shown only near row numbers
image

**Comment by ShadelessFox** [comment]
Let's fix them in a separate ticket.

**Comment by Matvey16** [comment]
I hope we can fix them sooner than later because if feel like it's a regression
https://github.com/dbeaver/pro/issues/2871

**Pull request merged**
