### PR TITLE
Fix MapD/OmniSci plugin/configuration

### PR DESCRIPTION
**Pull request by randyzwitch**
(Background: I'm Senior Director of Community/Open Source at OmniSci)

Currently, the MapD configuration is out of date. MapD rebranded to OmniSci last year, and version 5 of the database has been released. This PR attempts to rebrand, add the maven jar location for the JDBC driver, and fix the port and connection details.

One thing that isn't accounted for is additional necessary jars. On creating a connection, the dialog box comes up asking if you want to download the additional jars referenced by `omnisci-jdbc`. If you would like me to add those jars to the configuration, so that users don't get hit with that message, I'm happy to.

It's also not clear to me right now whether any additional parameters need to be set per #4925. I have built dbeaver locally using `mvn package` and it seems to work fine, but would love any guidance here about setting other parameters.

### CODE REVIEW

**Comment by randyzwitch** [comment]
Here are the jars I am talking about:

image

**Review by maheshwarigagan — APPROVED** [review]

**Comment by serge-rider** [comment]
Hi, nice to meet you :)
Thanks for the PR. Most likely we'll include this configuration in the next version.

Extra jars are Maven artifact dependencies. DBeaver download them once along with main jar.
If dependencies are not really needed then you can add `ignore-dependencies="true"` parameter in artifact configuration.

I'll test this config and merge pr in next couple of days.

**Comment by serge-rider** [comment]
Icons 16x16 and 32x32 are unreadable :(

**Comment by randyzwitch** [comment]
@serge-rider unreadable in what way?

**Comment by serge-rider** [comment]
It is impossible to read the text them because of icons bad quality.

https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.generic/icons/omnisci_icon%402x.png

Perhaps text can be replaced with some image?

**Comment by randyzwitch** [comment]
Oh, okay. Yes, I'll submit a new PR with better icons

**Pull request merged**
