### PR TITLE
#20471 Fix projects load

### LINKED ISSUE #20471: Deleted project comes back after reopening DBeaver
### Description

If you try to delete a project without enabling the checkbox  "delete project contents on disk" it comes back after reopening DBeaver
dbeaver_tggDJRmTUq

### DBeaver Version

23.1.1

### Operating System

win 10

### Database and driver

_No response_

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ShadelessFox**
Might need to test project-related stuff from dbeaver/pro#1641 as well.

### CODE REVIEW

**Review by LonwoLonwo — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]
**Projects synchronization on creation, deletetion, renaming and editing may be broken. Please test carefully!**

**Comment by E1izabeth** [comment]
Probably the real way to solve the issue requires to check the exact way of deleted projects resurrection. Some comment here would be useful.

**Comment by MashaKorax** [comment]
STR:

1. Create project in te cloudbeaver
2. Open te Dbeaver and add connection into this new project folder
3. Open te cloudbeaver and pick new project there
Actual result - there is no connections in the new project
chrome_gS4HwNe1LI

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
