### PR TITLE
Update GaussDB JDBC driver package - Synchronize with Huawei Cloud official website.

### PR DESCRIPTION
**Pull request by GaussDB-Fans**
Update GaussDB JDBC driver package - Synchronize with Huawei Cloud official website.

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
Thank you for contribution

**Comment by E1izabeth** [comment]
Hi, @GaussDB-Fans! Why did you close it?

**Comment by E1izabeth** [comment]
Never mind. I see the new one https://github.com/dbeaver/dbeaver/pull/35119

**Comment by GaussDB-Fans** [comment]
> Hi, @GaussDB-Fans! Why did you close it?

Because the redundant submission information of this PR branch has not been deleted, it looks unclean.

**Pull request closed without merging**
