### PR TITLE
#16477 Connection settings + Readonly toolbar button

### LINKED ISSUE #16477: Connection Properties in inconsistent state after cancelling an operation from within the "edit connection" dialog
I found a bug:
 
1.	Create a read-only-connection
2.	Open SQL-Editor and type something.
3.	Edit the connection, and uncheck the read-only checkbox
4.	When the question pops up, click “Cancel”
image
5.	The connection is still read-only. However, if you open the connection tab using “edit connection” again, the checkbox is unchecked (but we are still using the read/only connection)

In general this happens whenever you cancel the pending “reconnect with changed settings” process.

### PR DESCRIPTION
**Pull request by E1izabeth**
- Change readonly and non-readonly connection icons
image
image
- Add confirmation to reconnect if there are active transactions
image
- Save changed settings for active connection only if reconnect is accepted to maintain consistent state

### CODE REVIEW

**Comment by uslss** [comment]
connection type doesn't change if the connection isn't connected
dbeaver_sPP2TSlsnM

**Comment by uslss** [comment]
commit transaction is asked even if there are no active transactions. And sometimes confirmation dialog for the one script is shown twice
dbeaver_lHqPRvCLbn

**Comment by E1izabeth** [comment]
I tried to reproduce the issue about confirmation with no active transactions and found that there is active transaction on the video. The asterisk near the editor tab name points to it. The behavior in this case is the same as on editor close.

**Comment by E1izabeth** [comment]
Issue about showing twice confirmation dialog exists for a long time. I guess we need to create a separate issue for this.
It happens on reconnect after connection settings changing when active transaction exists due to editor is dirty (dirty due to active transaction).

**Comment by uslss** [comment]
verified

**Pull request merged**
