### PR TITLE
dbeaver/dbeaver#19676 Added item - Read data in SQL console

### LINKED ISSUE #19676: Add a new item in context menu: "Read data in SQL console"
I want to open the SQL console from the context menu:

image

And it must automatically generate the SELECT query:

image

### PR DESCRIPTION
**Pull request by sayyidhussain**
Adding a new item to context menu - 'Read data in SQL console' 

image
image

### CODE REVIEW

**Review by ShadelessFox — CHANGES_REQUESTED** [review]
First of all, thanks for the contribution!

Changes that must be addressed before this PR can be merged:
1. Please don't localize until you know the language you're doing a translation in.
2. The `SQLEditorHandlerOpenConsoleRead` class is basically a copy-paste of the `SQLEditorHandlerOpenConsole` class. Don't do that. Use parameterized commands and pass a flag to the existing handler instead.

Take a look at a parameterized command:

https://github.com/dbeaver/dbeaver/blob/222cefa637d7365583856bb6f0ca7f13f58645ad/plugins/org.jkiss.dbeaver.ui.editors.data/plugin.xml#L272-L279

And here's to use it:

https://github.com/dbeaver/dbeaver/blob/85ca6582673a63c727e812ca4fa1e030484df449/plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerSwitchContentViewer.java#L46

**Comment by sayyidhussain** [comment]
Request changes are completed. Hoping the changes are as per the request

**Comment by E1izabeth** [comment]
The PR can't be merged until the following corrections are addressed https://github.com/dbeaver/dbeaver/issues/19676#issuecomment-1592653442

**Comment by LonwoLonwo** [comment]
Hello @sayyidhussain 

Thanks for the contribution. 
We thought about this conception of what you are proposing. But we want to avoid extra buttons in our context menu.

So, we decided to make these changes: https://github.com/dbeaver/dbeaver/issues/19676#issuecomment-1592653442

We will do it from our side, so I'm closing this PR.

**Pull request closed without merging**
