### PR TITLE
Htmlcopypaste

### PR DESCRIPTION
**Pull request by Arty68**
grafik

grafik

### CODE REVIEW

**Comment by serge-rider** [comment]
I don't think that we need a new feature (too many features make everything complicated). It would be better to include new plugin in org.jkiss.dbeaver.core.feature.

I don't really like OpenSpreadsheetHandler  which is copy-pasted from almost identical handler from Office plugin. Here is the same problem as in Outlook plugin. Let's just add new export format first and then we'll see how to make it easier to call. Adding all export formats in data editor toolbar doesn't look like a good idea (it is already too big).

Also copyright headers are a bit messy.
Header template is here - https://github.com/dbeaver/dbeaver/blob/devel/docs/license_header.txt
You probably should add yourself in copyright notice.

**Comment by Arty68** [comment]
As you want. But I think an htmlformat copy paste is really a cool feature to add to dbeaver. The dbeaver standard copy paste is realy not convenient.

**Comment by Arty68** [comment]
Ok I got it but then it would be better to add to copyHTML here :

image

**Comment by serge-rider** [comment]
Yeah, or maybe we need to add new menu "Open in" with list of supported formats. Excel, Outlook and html (web browser) will be a good starters.

Maybe we'll need some additional interface of flag in DataTransfer extension. I've created #4802 for that.

**Comment by Arty68** [comment]
> Yeah, or maybe we need to add new menu "Open in" with list of supported formats. Excel, Outlook and html (web browser) will be a good starters.
> 
> Maybe we'll need some additional interface of flag in DataTransfer extension. I've created #4802 for that.

Ok but I just don't know how to name  the DataExporterCopyHtml it's a bit same as your DataExporterHTML. Perhaps we just need to change the  DataExporterHTML to DataExporterCopyHtml  then otherwise we will have 2 models for HTML format.

**Comment by serge-rider** [comment]
Agreed. Let me think about this a bit..

**Comment by Arty68** [comment]
Or maybe no new button for copy and the standard "copy" button makes a  text copy and an html copy at the same time. Same as in MS Access for example that would be better.
I need to check if it's possible.

**Comment by serge-rider** [comment]
Yes, it is possible to copy text in any number of formats at once.
Need to think about that too (in some cases such behavior  causes problems)

**Comment by serge-rider** [comment]
Please check the latest version? Open With function is implemented there. It is qite easy to add any export format there and you don't need to re-implement open handler.
Just implement data exported and add appName and appFileExtension attributes in the configuration.

If this doesn't work by some reason - please let me know.

**Comment by Arty68** [comment]
Thanks für the new "feature" I will add outlook. But as I said before I would prefer a "copy as" for the htmlcopy

**Comment by serge-rider** [comment]
Its ok, I'm also having a holiday vacation at the moment so there may be response delays on this week :)
I think we can solve Outlook export task and than try to figure omething out with Cope As..

Also feel free to modify existing HTML exporter to make it more customizable/good-looking. Right now al styles are hard-coded, maybe we should use some CSS styling which can be configured by user...

**Comment by serge-rider** [comment]
I think we'll add Copy As in the similar fashion as Open With was done (just reuse existing data exporters). Thus it will be possible to assign a shortcut to some particular format.
Feel free to modify this PR or create a new one.

**Comment by Arty68** [comment]
Hi I tryed to get and compile the newest code from github.
But I wasn't able to compile it : 
grafik

Can you help me ?

Thanks

**Comment by Arty68** [comment]
I was able to compile it with mvn package after removing greeplum for plugin and feature pom.
But now I can't launch it from eclipse : 


!ENTRY org.eclipse.osgi 4 0 2019-01-24 13:55:56.624
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in org.jkiss.dbeaver.core.application was unable to load class org.jkiss.dbeaver.core.application.DBeaverApplication.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:200)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:182)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:194)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.lang.ClassNotFoundException: org.jkiss.dbeaver.core.application.DBeaverApplication cannot be found by org.jkiss.dbeaver.core.application_5.3.4.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:612)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:180)
	... 16 more
An error has occurred. See the log file
E:\newDbeaver\runtime-New_configuration\.metadata\.log.

**Comment by serge-rider** [comment]
This is a bit odd, it builds fine on my machine and on our build server.
Could you post exact error message (in the end of Maven error log)?

In some cases plugin versions mix happens (e.g. when I forget to update version of some plugin after release). This can be solved by deleting Maven cache (delete .m2 folder in your user home, or just org.jkiss.* artifacts from it - if you have huge cache for some other projects).

**Comment by serge-rider** [comment]
You may need to update from devel and recreate Eclipse workspace because of massive project reconfiguration.

Please write me on serge@jkiss.org if you have any issues building it.

**Comment by Arty68** [comment]
The org.jkiss.* removal from .m2 helped .
Now I can use Eclipse again.
And I found something very funny about the build error : 

grafik

How can I launch the mvn package in english ?
It's language conversion problem

**Comment by serge-rider** [comment]
Good. This is actually a bug in tests, thanks for finding it. 
Fix has been pushed.

**Comment by serge-rider** [comment]
I could try to adapt it by myself in the next version..

**Comment by Arty68** [comment]
Sorry I was a bit busy. What did you adapt ?

**Comment by serge-rider** [comment]
I didn't do anything about that yet. Perhaps will try to include in 6.0 CE release.

**Comment by serge-rider** [comment]
Closing this one (as we already have "open as html" feature). Perhaps will rework #4766 a bit and include in one of near versions.

**Comment by Arty68** [comment]
I've opened https://github.com/dbeaver/dbeaver/pull/6483 to change a little the DataExporterHTML.java but otherwise the feature open as html is fine

**Pull request closed without merging**
