### PR TITLE
add TDengine database driver support

### PR DESCRIPTION
**Pull request by sangshuduo**
verified with a local TDengine instance and a TDengine Cloud instance
image

### CODE REVIEW

**Comment by sangshuduo** [comment]
https://github.com/dbeaver/dbeaver/issues/20070

**Comment by LonwoLonwo** [comment]
You need to add small icons, also.

**Comment by sangshuduo** [comment]
> You need to add small icons, also.

I added a small icon. Now I can see the driver display with the icon thumbnail. However when I create a database connection, a big icon still appears on the head area with a blank rectangle. How can I fix it? 

Another question, I want to give the user only the option to input the URL for the TDengien Cloud driver since that will access the given URL only. Now it provides Host and URL options. I wish don't provide a host option to avoid confusing the user.

**Comment by LonwoLonwo** [comment]
About the second question.
Removing the "`sampleURL="jdbc:TAOS-RS://{host}?useSSL=true%26token={token}`" may help.

It will be as Azure Databricks connection page:

2023-06-02 10_26_13-Window

**Comment by LonwoLonwo** [comment]
About icons.
You can take a look at other plugins.

https://github.com/dbeaver/dbeaver/tree/devel/plugins/org.jkiss.dbeaver.ext.oracle/icons

Usually, we have:
- `database_name_icon.png` - 16*16 px
- `database_name_icon@2x.png` - 32*32 px
- `database_name_icon_big.png` - 64*64 px
- `database_name_icon_big@2x.png` - 128*128 px

**Comment by sangshuduo** [comment]
@LonwoLonwo  Thanks. I will fix it and resubmit. Thanks.

**Pull request closed without merging**
