### PR TITLE
#16340 allow null for calendar

### LINKED ISSUE #16340: Can't use calendar on fields with null value
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.3

#### Steps to reproduce, if exist:
1. Open open a table with a date/time column
2. Click on the field with null value
3. Make sure that value panel has text presentation
4. Change value panel to calendar

**Expected:** Calendar shows default value or at least opens with blank fields
**Actual:** Error appears

dbeaver_5xFe4OEhPj

### PR DESCRIPTION
**Pull request by Destrolaric**
Closes #16340

### CODE REVIEW

**Comment by serge-rider** [comment]
Let's use zero time (1970?) instead of current time for nulls

**Comment by Matvey16** [comment]
Broke value panel for text presentation of date/time

**Comment by Matvey16** [comment]
Still the same

**Comment by Matvey16** [comment]
Hint about current time doesn't appear when switching from text value

dbeaver_JKQFpyOHiD

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
