### PR TITLE
ISSUE: #23215 - TaskNativeUIMessages.properties, LINE 24 changed text…

### LINKED ISSUE #23215: Wording change on db export confirmation dialog (override -> overwrite)
### Description

In my opinion, the word "override" should be "overwrite" in the following confirmation dialog:

DBeaver-Wording-Change

(You get this dialog when dumping a MySQL database.)

Rationale: You override something when you leave it intact but substitute it for something else. However, when exporting the database, the confirmation dialog is confirming that it's okay to _overwrite_ an existing file (replace it completely).

### DBeaver Version

Community Edition 24.0.0.202403031740

### Operating System

Windows 11

### Database and driver

MySQL (where's the version???)

### Steps to reproduce

Right click on a MySQL database.
Tools > Dump database > Next > Start

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by varunteja007006**
Hi, I am just starting to contribute so I just picked the one that has label GOOD FIRST ISSUE. 
What made me contribute ? I really enjoyed using DBeaver to learn SQL from past few weeks 😁 . Thanks.

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
Thank you for contribution!

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
It looks like other localizations are ok.

**Comment by E1izabeth** [comment]
Passed to QA Team for testing

**Comment by uslss** [comment]
verified

**Comment by varunteja007006** [comment]
Thank you

**Pull request merged**
