### PR TITLE
Update plugin.xml

### PR DESCRIPTION
**Pull request by ghost**
Hi there, 

I've get the configuration changed with fixed driver config. Can you please make GitHub pull request? 
Thanks,

Machbase

### CODE REVIEW

**Comment by MACHBASE** [comment]
Hi Serge, 

 

Would it take some time? I don’t see Machbase in new connection type? 

 

 



 

sign

JK Kim  /  Global Marketing Manager of Technology Strategic Department 

 

Infiniflux Co.,Ltd.   

 

E109, 440N. Wolfe Rd., Sunnyvale, California 94085 

 

904 ACE Twin Tower II, 273 Digital-ro,  Guro-gu, Seoul, South Korea   08381

 

T. 82-2-2209-5606                              M . 82-10-3629-0662

 

E.jk.kim@machbase.com     H .  <http://www.machbase.com/> www.machbase.com

**Comment by serge-rider** [comment]
It will appear after new DBeaver version release (going to happen on this week)

**Comment by MACHBASE** [comment]
Thank you so much, Serge J

 

 

sign

JK Kim  /  Global Marketing Manager of Technology Strategic Department 

 

Infiniflux Co.,Ltd.   

 

E109, 440N. Wolfe Rd., Sunnyvale, California 94085 

 

904 ACE Twin Tower II, 273 Digital-ro,  Guro-gu, Seoul, South Korea   08381

 

T. 82-2-2209-5606                              M . 82-10-3629-0662

 

E.jk.kim@machbase.com     H .  <http://www.machbase.com/> www.machbase.com

**Comment by MACHBASE** [comment]
Hi Serge, 

 

I’ve noticed that is some mistake on configuration. Would you guide how to correct them? Thanks, 


JK



 

sign

JK Kim  /  Global Marketing Manager of Technology Strategic Department 

 

Infiniflux Co.,Ltd.   

 

E109, 440N. Wolfe Rd., Sunnyvale, California 94085 

 

904 ACE Twin Tower II, 273 Digital-ro,  Guro-gu, Seoul, South Korea   08381

 

T. 82-2-2209-5606                              M . 82-10-3629-0662

 

E.jk.kim@machbase.com     H .  <http://www.machbase.com/> www.machbase.com

 

From: JK KIM [mailto:jk.kim@machbase.com] 
Sent: Tuesday, July 18, 2017 6:17 PM
To: 'serge-rider/dbeaver'
Subject: RE: [serge-rider/dbeaver] Update plugin.xml (#1890)

 

Thank you so much, Serge J

 

 

sign

JK Kim  /  Global Marketing Manager of Technology Strategic Department 

 

Infiniflux Co.,Ltd.   

 

E109, 440N. Wolfe Rd., Sunnyvale, California 94085 

 

904 ACE Twin Tower II, 273 Digital-ro,  Guro-gu, Seoul, South Korea   08381

 

T. 82-2-2209-5606                              M . 82-10-3629-0662

 

E.jk.kim@machbase.com     H .  <http://www.machbase.com/> www.machbase.com

**Pull request merged**
