### PR TITLE
#34201 [CUBRID] Create and Edit Trigger using UI 

### LINKED ISSUE #34201: [CUBRID] Create and Edit Trigger using UI
Allow an alternative option for user to create and edit Trigger using UI.

### PR DESCRIPTION
**Pull request by longhaseng52**
- Redesign Trigger UI
- Allow an alternative option for user to create and edit Trigger using UI.

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution! We'll review your PR and let you know, if some changes are needed.

**Review by serjiokov — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
We passed your PR to our QA team for testing.

**Comment by E1izabeth** [comment]
@longhaseng52 
There are some build errors in your PR. Could you fix them?
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8:compile (default-compile) on project org.jkiss.dbeaver.ext.cubrid: Compilation failure: Compilation failure: 
[ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/edit/CubridTriggerManager.java:[45] 
[ERROR] 	protected CubridTrigger createDatabaseObject(
[ERROR]             DBRProgressMonitor monitor,
[ERROR]             DBECommandContext context,
[ERROR]             Object container,
[ERROR]             Object copyFrom,
[ERROR]             Map<String, Object> options) throws DBException {
[ERROR] 	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Name clash: The method createDatabaseObject(DBRProgressMonitor, DBECommandContext, Object, Object, Map<String,Object>) of type CubridTriggerManager has the same erasure as createDatabaseObject(DBRProgressMonitor, DBECommandContext, Object, Object, Map) of type GenericTriggerManager but does not override it
[ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/edit/CubridTriggerManager.java:[45] 
[ERROR] 	protected CubridTrigger createDatabaseObject(
[ERROR]             DBRProgressMonitor monitor,
[ERROR]             DBECommandContext context,
[ERROR]             Object container,
[ERROR]             Object copyFrom,
[ERROR]             Map<String, Object> options) throws DBException {
[ERROR] 	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method createDatabaseObject(DBRProgressMonitor, DBECommandContext, Object, Object, Map<String,Object>) of type CubridTriggerManager must override or implement a supertype method
[ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/edit/CubridTriggerManager.java:[81] 
[ERROR] 	protected void createOrReplaceTriggerQuery(
[ERROR]             DBRProgressMonitor monitor,
[ERROR]             DBCExecutionContext executionContext,
[ERROR]             List<DBEPersistAction> actions,
[ERROR]             GenericTrigger genericTrigger,
[ERROR]             boolean create) {
[ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Name clash: The method createOrReplaceTriggerQuery(DBRProgressMonitor, DBCExecutionContext, List<DBEPersistAction>, GenericTrigger, boolean) of type CubridTriggerManager has the same erasure as createOrReplaceTriggerQuery(DBRProgressMonitor, DBCExecutionContext, List, GenericTrigger, boolean) of type GenericTriggerManager but does not override it
[ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/edit/CubridTriggerManager.java:[81] 
[ERROR] 	protected void createOrReplaceTriggerQuery(
[ERROR]             DBRProgressMonitor monitor,
[ERROR]             DBCExecutionContext executionContext,
[ERROR]             List<DBEPersistAction> actions,
[ERROR]             GenericTrigger genericTrigger,
[ERROR]             boolean create) {
[ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method createOrReplaceTriggerQuery(DBRProgressMonitor, DBCExecutionContext, List<DBEPersistAction>, GenericTrigger, boolean) of type CubridTriggerManager must override or implement a supertype method
[ERROR] 4 problems (4 errors)
```

**Comment by longhaseng52** [comment]
> @longhaseng52 There are some build errors in your PR. Could you fix them?
> 
> ```
> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8:compile (default-compile) on project org.jkiss.dbeaver.ext.cubrid: Compilation failure: Compilation failure: 
> [ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/edit/CubridTriggerManager.java:[45] 
> [ERROR] 	protected CubridTrigger createDatabaseObject(
> [ERROR]             DBRProgressMonitor monitor,
> [ERROR]             DBECommandContext context,
> [ERROR]             Object container,
> [ERROR]             Object copyFrom,
> [ERROR]             Map<String, Object> options) throws DBException {
> [ERROR] 	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [ERROR] Name clash: The method createDatabaseObject(DBRProgressMonitor, DBECommandContext, Object, Object, Map<String,Object>) of type CubridTriggerManager has the same erasure as createDatabaseObject(DBRProgressMonitor, DBECommandContext, Object, Object, Map) of type GenericTriggerManager but does not override it
> [ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/edit/CubridTriggerManager.java:[45] 
> [ERROR] 	protected CubridTrigger createDatabaseObject(
> [ERROR]             DBRProgressMonitor monitor,
> [ERROR]             DBECommandContext context,
> [ERROR]             Object container,
> [ERROR]             Object copyFrom,
> [ERROR]             Map<String, Object> options) throws DBException {
> [ERROR] 	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [ERROR] The method createDatabaseObject(DBRProgressMonitor, DBECommandContext, Object, Object, Map<String,Object>) of type CubridTriggerManager must override or implement a supertype method
> [ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/edit/CubridTriggerManager.java:[81] 
> [ERROR] 	protected void createOrReplaceTriggerQuery(
> [ERROR]             DBRProgressMonitor monitor,
> [ERROR]             DBCExecutionContext executionContext,
> [ERROR]             List<DBEPersistAction> actions,
> [ERROR]             GenericTrigger genericTrigger,
> [ERROR]             boolean create) {
> [ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [ERROR] Name clash: The method createOrReplaceTriggerQuery(DBRProgressMonitor, DBCExecutionContext, List<DBEPersistAction>, GenericTrigger, boolean) of type CubridTriggerManager has the same erasure as createOrReplaceTriggerQuery(DBRProgressMonitor, DBCExecutionContext, List, GenericTrigger, boolean) of type GenericTriggerManager but does not override it
> [ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/edit/CubridTriggerManager.java:[81] 
> [ERROR] 	protected void createOrReplaceTriggerQuery(
> [ERROR]             DBRProgressMonitor monitor,
> [ERROR]             DBCExecutionContext executionContext,
> [ERROR]             List<DBEPersistAction> actions,
> [ERROR]             GenericTrigger genericTrigger,
> [ERROR]             boolean create) {
> [ERROR] 	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [ERROR] The method createOrReplaceTriggerQuery(DBRProgressMonitor, DBCExecutionContext, List<DBEPersistAction>, GenericTrigger, boolean) of type CubridTriggerManager must override or implement a supertype method
> [ERROR] 4 problems (4 errors)
> ```

@E1izabeth, 
Let me check and get back to you soon. Thanks

**Comment by longhaseng52** [comment]
Hi @E1izabeth,
I have fixed the error. Could you help check?
Thanks!

**Comment by E1izabeth** [comment]
@longhaseng52 it's fine now

**Comment by uslss** [comment]
@longhaseng52 , could you resolve conflicts in PR?
Thanks in advance

**Comment by longhaseng52** [comment]
Hi @uslss, I have just resolved the conflicts. Thank you.

**Comment by uslss** [comment]
@longhaseng52 unfortunately, I cannot find a way to create trigger using UI in this branch. Probably some special steps are needed?
image

**Comment by longhaseng52** [comment]
Hi @uslss,
Here is the demo video on how to create trigger using UI. Hope this video would help.
Let me know if you have other question. Thank you.

https://github.com/user-attachments/assets/fc0d9e49-4a37-4eb8-bc72-dc7534bcaeea

**Comment by uslss** [comment]
verified

**Pull request merged**
