### PR TITLE
feat: automatic row count

### PR DESCRIPTION
**Pull request by utsav1704**
feat: #22657
Automatic Row Count

https://github.com/dbeaver/dbeaver/assets/75378586/b1c163cf-3a40-454a-a6c5-bd2277926530

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Hello @utsav1704 
Thanks for your contribution.
We will take a look at it.

**Review by ShadelessFox — COMMENTED** [review]
Please demonstrate how it would work when fetching batches of data. The default fetch size is 200 rows. What if you have more than that? Will it show "200, 400, etc" or "200+, 400+, etc"?

**Comment by utsav1704** [comment]
If we have more rows than fetch size, it will show the exact number of rows.
As you can see in the video, I set the fetch size to 20, and I have 21 rows in the student table and 24 rows in the product table.

**Comment by ShadelessFox** [comment]
21 rows are not enough for testing, they all were loaded in the memory at the same time. Please test against a table with several hundreds rows at least.

**Comment by utsav1704** [comment]
I tried this changed code on the table, which has around 16000 rows and a default fetch size of 200. When I'm loading the table or refreshing the table, it shows the exact number of rows.

**Comment by ShadelessFox** [comment]
Ah, I see. It basically executes the "Row Count" action. This change means that:
1. This action is now redundant
2. This might be an expensive operation that will be called every time we fetch rows. We probably don't want that.

I'm going to discuss this change with my colleagues.

**Comment by ShadelessFox** [comment]
I'm sorry, we don't like this idea, even if there were an option to turn it on/off.

As noted, this might be a costly operation for some databases.

**Comment by utsav1704** [comment]
Okay. I try to see if we can do this one time while loading the table.

**Comment by ShadelessFox** [comment]
I've added some information to the original ticket. Please see https://github.com/dbeaver/dbeaver/issues/22657#issuecomment-1938736014

**Pull request closed without merging**
