### PR TITLE
i18n_pl add polish translations

### PR DESCRIPTION
**Pull request by Krzysztofz01**
The purpose of this pull-request is to add Polish user interface translations. At the time of opening this pull request, translations has been added to `org.jkiss.dbeaver.core`

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution!

**Comment by LonwoLonwo** [comment]
Hello @Krzysztofz01 

Thanks for your contribution.

Unfortunately, DBeaver doesn't support the Polish language for now.

I will repeat my answer as I did it here: https://github.com/dbeaver/dbeaver/pull/21768.

We can't add a new language with 1% localization.
I do not suggest translating all our bundles, but 10% of all, maybe?
You can use this PR to add more data.

Otherwise, your translation will be available only for those users who will change the .ini file manually.

**Comment by Krzysztofz01** [comment]
> Hello @Krzysztofz01 
> 
> Thanks for your contribution.
> 
> Unfortunately, DBeaver doesn't support the Polish language for now.
> 
> I will repeat my answer as I did it here: https://github.com/dbeaver/dbeaver/pull/21768.
> 
> We can't add a new language with 1% localization.
> I do not suggest translating all our bundles, but 10% of all, maybe?
> You can use this PR to add more data.
> 
> Otherwise, your translation will be available only for those users who will change the .ini file manually.

I plan to add a full translation of all packages. I opened this pull request with a single package just to indicate that such work is being done.

**Comment by LonwoLonwo** [comment]
That's great. We will wait for new translations then.

**Comment by E1izabeth** [comment]
@Krzysztofz01 hi, any update?

**Comment by Krzysztofz01** [comment]
> @Krzysztofz01 hi, any update?

Hi, I continue to introduce new translations locally. Due to other projects, unfortunately I am not able to devote more time. However, the work is ongoing.

**Comment by E1izabeth** [comment]
This PR is stale, so I'm closing it. Please let me know if you continue working on this, and we can reopen it.

**Pull request closed without merging**
