### PR TITLE
Materialize driver

### PR DESCRIPTION
**Pull request by bobbyiliev**
As discussed in #20514 adding the initial work for the Materialize driver.

dbeaver-materialize-driver-initial-work

### CODE REVIEW

**Review by ShadelessFox — COMMENTED** [review]
Thanks for the contribution!

Can padding on the icons and logo be reduced so they don't look small in the UI?

**Comment by bobbyiliev** [comment]
Thanks for that suggestion @ShadelessFox! Just pushed the updated logos!

**Review by ShadelessFox — APPROVED** [review]
👍🏻

**Review by LonwoLonwo — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by uslss** [comment]
verified

**Pull request merged**
