### PR TITLE
dbeaver/dbeaver#32927 Fix duckdb data in data grid

### LINKED ISSUE #32927: [DuckDB] Can't update data in data grid
### Description

Can't update data with error
```
org.jkiss.dbeaver.model.exec.DBCException: Object parameter [1] binding not supported
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.bindValueObject(DefaultValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.data.ExecuteInsertBatchImpl.bindStatement(ExecuteInsertBatchImpl.java:105)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:169)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:785)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$2(ResultSetPersister.java:707)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:706)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:644)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```
image

Also check that the data is being read correctly

### DBeaver Version

24.0.5

### Operating System

_No response_

### Database and driver

_No response_

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HocKu7**

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Comment by DariaMarkaryan** [comment]
Verified

**Review by ShadelessFox — APPROVED** [review]

**Comment by DariaMarkaryan** [comment]
verified

**Comment by DariaMarkaryan** [comment]
verified

**Comment by EvgeniaBzzz** [comment]
verified on CB

**Pull request merged**
