### PR TITLE
Fixing mistakes in the translation in the bundle_pt_BR.properties

### PR DESCRIPTION
**Pull request by RobertoCassio**
Fixed some more mistakes, and added translation in the lines that were in English.

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Thanks for your contribution @RobertoCassio

**Review by LonwoLonwo — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
@RobertoCassio Since you already made changes there, maybe you can fix this part in the same PR?
image

**Comment by RobertoCassio** [comment]
I'm not entirely sure if I did it correctly; I'm relatively new to this. Please let me know if there's anything I need to fix

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
