### PR TITLE
Add unit tests for org.jkiss.utils.BeanUtils

### PR DESCRIPTION
**Pull request by Braavos6**
I've analysed your codebase and noticed that `org.jkiss.utils.BeanUtils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

### CODE REVIEW

**Comment by serge-rider** [comment]
Unfortunately we can't use powermock because of Java 11 incompatibility.

**Comment by Braavos96** [comment]
Hi @serge-rider I have removed the powermock and implemented the interfaces :)

**Comment by serge-rider** [comment]
Thanks!
BTW I believe you should add yourself in the copyright section (on line 4, similarly to line 3)

**Comment by Braavos96** [comment]
Hi @serge-rider thank you. I added myself to the copyright section :)

**Pull request merged**
