### PR TITLE
#16886 Add Copy button for executed statements in Query Log

### LINKED ISSUE #16886: In query log add button Copy near of "Re-execute"
- [x] Add ability to copy executed query in Query Log
- [x] Use DDL label instead of Text icon for Generate DDL from Result Set action

### PR DESCRIPTION
**Pull request by E1izabeth**
Label instead of image for Generate DDL from result set

image

Copy button

image

### CODE REVIEW

**Review by ShadelessFox — COMMENTED** [review]
I would keep the icon along with the label, it looks goofy IMO

**Comment by E1izabeth** [comment]
Agreed

image

**Comment by uslss** [comment]
re-execute button isn't shown for now
image

**Comment by E1izabeth** [comment]
Re-execute button doesn't appear for embedded databases or when Open separate connection for each editor is disabled, because we can't split queries from different editors in this case. All queries for different editors for this db connection mess up in Execution Log and it becomes possible to execute query from script corresponding to another editor in active editor.

**Comment by uslss** [comment]
verified

**Pull request merged**
