### PR TITLE
Show copy only for DBPNamedObject

### LINKED ISSUE #21723: Redundant copy option in context menu
### Description

dbeaver_pH97ezQ9Iv

### DBeaver Version

DBeaver 23.2.3

### Operating System

windows 10

### Database and driver

_No response_

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by brunodmartins**
Closes #21723

[Screencast from 2023-11-15 19-13-20.webm](https://github.com/dbeaver/dbeaver/assets/7273952/683f36dd-0fe5-4cf1-b718-cc606e01fd3e)

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution!

**Review by E1izabeth — COMMENTED** [review]
According to the `NavigatorHandlerCopyAbstract::copySelection` the copy action is also possible for `DBPNamedObject`

**Comment by brunodmartins** [comment]
@E1izabeth as `DBNodes` implements `DBPNamedObject` , I changed the implementation to target the interface =) Thanks for the help!

**Review by E1izabeth — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Comment by uslss** [comment]
verified

**Pull request merged**
