### PR TITLE
dbeaver/dbeaver#23362 erd composite fk representation

### LINKED ISSUE #23362: ER diagram foreign key
### Description

Since the version 24.0, in ER Diagram, the foreign key are not well designed.
When you select the link between two tables, all the foreign key columns are not underlined, as they were previously.

**Example**
>Version 24.0.1: 
2024-04-09_09h47_20

>Version 23.3.2:
2024-04-09_09h49_56

Script to reproduce:
```
CREATE TABLE Customers (
	customer_id int NOT NULL,
	name varchar(50) NOT NULL,
	CONSTRAINT PK_Customers PRIMARY KEY (customer_id,name)
);

CREATE TABLE Orders (
	order_id int NOT NULL,
	amount decimal(10,2) NULL,
	customer_id int NULL,
	name varchar(50) NULL,
	CONSTRAINT PK_Orders PRIMARY KEY (order_id),
	CONSTRAINT FK_Orders_Customers FOREIGN KEY (customer_id,name) REFERENCES Customers(customer_id,name)
);
```

### DBeaver Version

Community edition: Version 24.0.1

### Operating System

Windows 10

### Database and driver

Data base: SQL Server
Driver	Microsoft JDBC Driver 9.2 for SQL Server [9.2.0.0]

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by serjiokov**

### CODE REVIEW

**Comment by serjiokov** [comment]
image

**Comment by serjiokov** [comment]
Should be tested 
  ONLY ORTHO		
  1 primary key  - single attribute  
   should be drawn as one-by-one  by **attribute** connection  [attribute - attribute]
    
  2 primary key  - composite attributes
   should be drawn as one-by-one  by primary keys section to attribute [ keys section to attribute] 
  
  SHORT+ORTHO 
  
  1 Highlight complex keys by clicking on the field (attribute)  
  2 Highlight complex keys by clicking on the connection 
    
 PLS check VQB just to be sure

**Comment by MashaKorax** [comment]
verified

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
