### PR TITLE
#15763 Fix bug Oralce  MV changes are not saved

### PR DESCRIPTION
**Pull request by Bitros**
Any changes in Oracle MV can not be saved when switch to DDL Compact Format. But it works well when switch to Full DDL Format.

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Hello @Bitros 

Thanks for the contribution!

2022-03-09 11_23_46-DBeaver  F__Java Projects_dbeaver_dbeaver-workspace-idea  - F__Java Projects_dbe

I think that class cast operation is not necessary here.

**Comment by Bitros** [comment]
> Hello @Bitros
> 
> Thanks for the contribution!
> 
> 2022-03-09 11_23_46-DBeaver F__Java Projects_dbeaver_dbeaver-workspace-idea - F__Java Projects_dbe
> 
> I think that class cast operation is not necessary here.

@LonwoLonwo Thanks for your reminder. I just code it in raw editor and will delete that.

**Comment by LonwoLonwo** [comment]
I think that you can delete this entire block.

```java
if (CommonUtils.isEmpty(command.getObject().getObjectDefinitionText(monitor, options))) {
            throw new DBException("View definition cannot be empty"); //$NON-NLS-1$
}
```

As we did in the OracleViewManager class

No validation here - no problems with the update of the source.

And I will fix other issues after merging.

**Comment by Bitros** [comment]
Hi @LonwoLonwo Please help to review and merge

**Pull request merged**
