### PR TITLE
#20416 statistics tab

### LINKED ISSUE #20416: Show statistics panel for single query
### Description

Prior to 23.1.1 dBeaver would always show a statistics panel with the results of the run query, elapsed time, etc.
In the latest version it is missing.
Not only doesn't it appear with the results, there doesn't appear to be a listing in any of the context menus nor in the window manager.

How do I get this panel back?
thanks.

### DBeaver Version

Community Edition 23.1.1

### Operating System

Windows 10

### Database and driver

Problem apparent across both Oracle and PostgreSQL drivers.

### Steps to reproduce

1. connect to database
2. run query
3. marvel at the now missing statistics panel.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by E1izabeth**
### PR for TWO issues: #20416 #20976

image

image

Please check lots of different queries combination in a script.

### CODE REVIEW

**Comment by serge-rider** [comment]
Let's relayout pref page to avoid big empty gaps

**Comment by E1izabeth** [comment]
image

**Comment by uslss** [comment]
image

**Comment by E1izabeth** [comment]
Renamed `Never` to `When no data`
image

**Comment by uslss** [comment]
verified

**Pull request merged**
