### PR TITLE
Corrected Translation of 'QuoteChar' in Japanese Localization

### PR DESCRIPTION
**Pull request by doew**
### Description
This PR addresses the mistranslation of the term 'QuoteChar' in the Japanese localization of DBeaver. The original translation '見積もり文字' (estimation characters) has been corrected to '引用文字' (quotation characters), which more accurately reflects the intended meaning in the context of database software.
FYI: https://dictionary.cambridge.org/ja/dictionary/english-japanese/quote

### Changes
- Updated the translation of 'QuoteChar' in all properties where it was previously mistranslated.

### Justification
The term 'QuoteChar' typically refers to characters used for quoting in SQL queries and database contexts. The corrected translation will enhance understanding and clarity for Japanese-speaking users of DBeaver.

Looking forward to the review and hoping this contributes to improving DBeaver's usability for the Japanese community.

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Hello @doew 

Thanks for your contribution and a good explanation.

The first question - you said the translation was incorrect, and you fixed two strings. But how about 4 others? Are they correct?

dataTransfer.processor.csv.property.quoteChar.name=見積もり文字
**dataTransfer.processor.csv.property.quoteChar.description=文字列を引用するのに使用される文字（スペースは引用符を意味しない）
dataTransfer.processor.csv.property.quoteAlways.name=常に引用符
dataTransfer.processor.csv.property.quoteAlways.description=すべてのセル値を引用します。 "quoteNever"と一緒に使うことはできません**
dataTransfer.processor.csv.property.quoteNever.name=見積もりはありません
**dataTransfer.processor.csv.property.quoteNever.description=セルの値を引用しないでください。 "quoteAlways"と一緒に使うことはできません**

Second one. Google Translate says to me, that the `引用文字はありません` - means `There are no quoted characters`.
But it sounds incorrect to me. Not like - "Never quote characters". Like action. 
You can see it in the description:
`dataTransfer.processor.csv.property.quoteNever.description=Do not quote cell values.`

**Comment by doew** [comment]
Hi @LonwoLonwo 

Thank you for your response. I had only searched for the term "見積もり," so I did not check the other properties.
As you suggested, these other properties also seem to be inaccurately translated, so I will correct any that are wrong.
It appears that the existing code already uses "引用符" as the translation for QuoteChar, and this seems to be correct, so I will standardize on this.

```
dataTransfer.processor.csv.property.quoteChar.name=引用符
dataTransfer.processor.csv.property.quoteAlways.name=常に引用符を付ける
dataTransfer.processor.csv.property.quoteAlways.description=すべてのセル値に引用符を付与します。"quoteNever"と一緒に使うことはできません。
dataTransfer.processor.csv.property.quoteNever.name=引用符を付与しない
dataTransfer.processor.csv.property.quoteNever.description=すべてのセルの値に引用符を付与しません。"quoteAlways"と一緒に使うことはできません。
```

I am considering making these changes. Do they seem appropriate to you?

**Comment by LonwoLonwo** [comment]
Thanks, that looks better.

Also, you can change unlocalized すべてのセル値に引用符を付与します。"quoteNever"と一緒に使うことはできません。 quoteNever -> to something like 引用符を付与しない (sorry, I'm not familiar with the Japanese language)
and "quoteAlways" also.

**Comment by doew** [comment]
Thank you for your feedback.

I agreed with your points, so I have also improved the translations for these properties.
The updated translations have been pushed to the repository. Please let me know if there are any further adjustments needed.

Thank you again for your guidance and support in improving the localization.

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Thanks for your changes.
Now, we are waiting for the second reviewer and QA Team.

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
