### PR TITLE
#20952 load setting before objects and set selection to data source i…

### LINKED ISSUE #20952: Error loading database task associated with deleted database
### Description

DBeaver is unable to load database task and all task configuration is lost 
when database used in this task was deleted:

```
Error loading wizard settings

Reason:
Error loading objects configuration
```
This happens after deleting a database that was used with some database task.
All task configuration is lost if this error occurs (MAJOR ISSUE).
This is extremely inconvenient and annoying.

The work around that I found is to go to `tasks.json` file and fix database name to some existing database - then task will be loaded correctly.

Task should be loaded even if database is missing (maybe with some warning), but it should load all other configuration options in the task and should allow to select new database.

 

### DBeaver Version

Version 23.1.5.202308201919

### Operating System

Windows

### Database and driver

MariaDB

### Steps to reproduce

- Create MySQL database `db1`
- Create MySQL dump task and select `db1` as target database, also modify other options for task
- Save task
- Delete `db1` database
- Try to open saved MySQL dump task
- (ISSUE) In opened task dialog all configuration is reset to default values

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LonwoLonwo**
Load setting before objects and set selection to the data source if the task object was deleted

2023-10-10 19_17_36-DBeaver Ultimate 23 2 2 - miriam

Please check:

- [x] dump with or without task in PostgreSQL with or without deleted containers
- [x] dump with or without task in MySQL with or without deleted containers
- [x] restore with or without task in PostgreSQL with or without deleted containers
- [x] restore with or without task in MySQL with or without deleted containers
- [x] script execution with or without task in PostgreSQL with or without deleted containers
- [x] script with or without task execution in MySQL with or without deleted containers

### CODE REVIEW

**Comment by MashaKorax** [comment]
backup  in PostgreSQL, Mysql invoke NPE
```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.app.DBPProject.getDataSourceRegistry()" because "project" is null
	at org.jkiss.dbeaver.model.DBUtils.findObjectById(DBUtils.java:580)
	at org.jkiss.dbeaver.ext.postgresql.tasks.PostgreDatabaseBackupSettings.lambda$1(PostgreDatabaseBackupSettings.java:210)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

https://github.com/dbeaver/dbeaver/assets/84867187/da23f7b9-046f-4143-9a01-85e8dd6328d2

**Comment by MashaKorax** [comment]
**Postgres:**

1. Open context db menu - tools - restore db 
2. Save task **database restore** from this menu
3. Delete container 
4. Double click on task - error wizard- > edit task
5. Try to change db 
```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.postgresql.tasks.PostgreDatabaseRestoreInfo.getDatabase()" because "this.restoreInfo" is null
	at org.jkiss.dbeaver.ext.postgresql.tasks.PostgreDatabaseRestoreSettings.saveSettings(PostgreDatabaseRestoreSettings.java:139)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreRestoreWizard.saveTaskState(PostgreRestoreWizard.java:61)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.saveConfigurationToTask(TaskConfigurationWizard.java:320)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.saveTask(TaskConfigurationWizard.java:315)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard$2.widgetSelected(TaskConfigurationWizard.java:372)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.tasks.ui.view.TaskHandlerCreate.execute(TaskHandlerCreate.java:53)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:300)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:280)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

**Comment by LonwoLonwo** [comment]
Fixed

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
