### PR TITLE
#22449 Call the external tool when compare objects

### PR DESCRIPTION
**Pull request by plotn**
as described in issue

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Hello @plotn 

Thanks for your contribution.

Please provide more details on the main topic for our QA Team. Expected behavior, tips about external tools (which tools can be used and how). Acceptance criteria.

And, please return the product/debug/DBeaver.product.launch.

**Comment by plotn** [comment]
I added the following block:
image

Which gave us additional result:
image

**Comment by plotn** [comment]
> And, please return the product/debug/DBeaver.product.launch.

done

**Comment by LonwoLonwo** [comment]
And now, you need to remove your changes from the product/debug/DBeaver.product.launch.

Also, it is still unclear - what type of external tools do you expect. Maybe you can add some tips in the UI part?

**Comment by plotn** [comment]
> Also, it is still unclear - what type of external tools do you expect. Maybe you can add some tips in the UI part?

done

**Comment by ShadelessFox** [comment]
Thank you for your contribution. We decided we don't want to use external applications/tools to do the diffing.

Please see https://github.com/dbeaver/dbeaver/issues/22449#issuecomment-1921346976, https://github.com/dbeaver/dbeaver/issues/22449#issuecomment-1924221343

You can create a new PR that will meet the new requirements, or we can implement it ourselves in the future.

**Pull request closed without merging**
