### PR TITLE
dbeaver/pro#1428 Fix font issues

### PR DESCRIPTION
**Pull request by ShadelessFox**
Acceptance criteria:
- [x] Font is changed in the About dialog
- [x] Font is changed in the connection wizard
- [x] Font is changed in the SQL editor's toolbar, buttons, and panels
- [x] Font is changed in the main toolbar

### CODE REVIEW

**Comment by E1izabeth** [comment]
What's about this part https://github.com/dbeaver/pro/issues/1428#issuecomment-1432018484 ?

**Comment by ShadelessFox** [comment]
I haven't seen that comment. It sounds like a good opportunity to create a separate ticket for it.

**Comment by E1izabeth** [comment]
Ok, could you do it then?

**Comment by ShadelessFox** [comment]
https://github.com/dbeaver/pro/issues/1460

**Review by E1izabeth — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Comment by uslss** [comment]
Font changes are not applied for the main toolbar at the first attempt.
1. Change font from standard to bold italic - no changes in the toolbar
2. Change font from bolt italic for standard - main toolbar font becomes bold italic

https://user-images.githubusercontent.com/31996417/225276875-bf1db94f-784a-46f1-beac-14d59837dce2.mp4

**Comment by serge-rider** [comment]
Please check that 

- [ ] - font in SQL editor and results viewer is applied correctly
- [x] - it can be reset to original value
- [x] - that all shortcuts like ctrl++ ctrl+- are working

**Comment by uslss** [comment]
Issues with font changing for resultset created https://github.com/dbeaver/pro/issues/1487

**Pull request merged**
