### PR TITLE
Most of the localization work for Simplified Chinese have been completed

### PR DESCRIPTION
**Pull request by bianyun1981**
I have completed most of the localization work for Simplified Chinese which involves 52 properties files (42 files modifed, 10 files added), including mysql and oracle extension module. 

But there are still some strings are hard-coded in the code and they are not completed. I think it might be better for the module developer to build the i18n properties file first.

0_involved_properties_files

1_localized_menus

2_hardcoded_01

2_hardcoded_02

### CODE REVIEW

**Comment by ShadelessFox** [comment]
Hello @bianyun1981,

Thanks for the contribution.

I have added localization entries for previously hard-coded string literals. Please see 2ecaf3b

**Comment by bianyun1981** [comment]
Hi @ShadelessFox ,

I added all the hard-coded locations that can be found in the new issue #14964. Could you or someone else add localization entries for those hard-coded string literals too? After you commit, I will merge and then complete Simplified Chinese localization for those new entries.

Thanks.

**Comment by bianyun1981** [comment]
Hello, @ShadelessFox,

Considering that the hard-coded lines listed in issue #14964 will be revised in the 21.3.3 milestone, I think it might be better to cancel pull request #14948 first, and wait for the 21.3.3 version to be released before doing the localization of Simplified Chinese.

**Comment by ShadelessFox** [comment]
Hello,

I am looking forward to it!

**Pull request closed without merging**
