### PR TITLE
#35054 [CUBRID] Create, edit and drop Server using UI

### LINKED ISSUE #35054: [CUBRID] Create, edit and drop Server using UI
Allow an alternative option for user to create, edit and drop Server using UI.

### PR DESCRIPTION
**Pull request by longhaseng52**
Allow an alternative option for user to create, edit and drop Server using UI.

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution!

**Review by E1izabeth — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Comment by E1izabeth** [comment]
We passed your PR to our QA team for testing

**Comment by uslss** [comment]
@longhaseng52 could you provide a bit more information about what exactly was implemented?
thanks in advance

**Comment by longhaseng52** [comment]
> @longhaseng52 could you provide a bit more information about what exactly was implemented? thanks in advance
Hello @uslss, here is what I have implemented:
- Add more properties to Server
- Allow user to create, edit and delete Server using UI.

**Comment by uslss** [comment]
@longhaseng52 
Please provide some screenshots or video. Unfortunately, it is not clear at the moment how to create, edit and delete Server using UI. 
Probably some additional database settings are needed?

**Comment by longhaseng52** [comment]
@uslss
I hope this screen record below could help.

https://github.com/user-attachments/assets/5df52f8c-a823-4834-9cf7-a9566cf12f60

**Comment by E1izabeth** [comment]
@longhaseng52 please resolve conficts

**Comment by uslss** [comment]
verified (CUBRID 11.3.1.1142)
image

**Pull request merged**
