### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR:
- Improve French translations
- Adds some French translations

### CODE REVIEW

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Thanks for your contribution @Jean-BaptisteC 

We will look at it.

**Review by E1izabeth — APPROVED** [review]

**Comment by Jean-BaptisteC** [comment]
With pleasure, I want to contribute to translations because I use Dbeaver everyday in my job.
I have planned to doing other PR to improve french translations in others modules. Is it possible to reorganize translations in files to simplify compare?

**Comment by LonwoLonwo** [comment]
It will be great to see more French localization!

About reorganization - did you read this article? https://github.com/dbeaver/dbeaver/wiki/Localization

**Comment by MashaKorax** [comment]
verified

**Comment by Jean-BaptisteC** [comment]
Thanks for localization article.
I have planned to back in few weeks with french translations for all plugins :)
Did you prefere small changes to review more easily?

**Comment by LonwoLonwo** [comment]
> Did you prefere small changes to review more easily?

All options are manageable for us :)

**Pull request merged**
