### PR TITLE
Add unit tests for org.jkiss.utils.SecurityUtils

### PR DESCRIPTION
**Pull request by JohnLBergqvist**
Hi,

Further to my initial PRs for the `utils` module, I have written tests that cover the `org.jkiss.utils.SecurityUtils` class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Once again, these tests should help you detect any regressions caused by future code changes.

### CODE REVIEW

**Comment by serge-rider** [comment]
These tests really make sense, thanks

**Comment by serge-rider** [comment]
Unfortunately I had to disable latest tests. They were dependent on powermock and we can't use it.
Despite the fact that Powermock is evil by itself it doesn't work well on Java 11 (at least with default Maven settings). So I've commented all tests which depend on Powermock.
Maybe this can be done with base junit and Mockito?

**Comment by JohnLBergqvist** [comment]
@serge-rider Unfortunately there is no way to mock the static classes used here such as `System`, `INetAddress`, `MessageDigest`, or to mock the constructors of `Random`/`SecureRandom`, with just Mockito, hence why Powermock was used. Is there a different mocking framework such as EasyMock or Jmockit, that you would consider instead?

**Comment by serge-rider** [comment]
I can't say for sure as I'm not fluent in different testing frameworks. 
We could try it on Java 12 to see how it goes.

@tchibatron WDYT?

**Comment by tchibatron** [comment]
Maybe just simple refactor this class? :)

**Pull request merged**
