### PR TITLE
dbeaver/dbeaver#20917 add support for view ddl

### LINKED ISSUE #20917: [Trino] Add support for displaying view ddl
**Is your feature request related to a problem? Please describe.**
Currently DBeaver does not support showing view ddl for Trino sources. It just displays the text "-- View definition not available".

**Describe the solution you'd like**
View ddl is displayed as usual.

**Additional context**
The view ddl could be read from the catalog's information_schema or as the result of the "show create view" -  command.

I already had a look at it and would be willing to implement that myself :)

### PR DESCRIPTION
**Pull request by EinWesen**
Closes dbeaver/dbeaver#20917

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Thanks for the contribution @EinWesen 

It looks ok for now from the code style and logic sides. But we need to test it on our Trino database instance.

**Comment by EinWesen** [comment]
@LonwoLonwo 
Thanks for taking a look at it. Just let me know if you find anything.

As a sidenote. In the meantime i noticed that the table ddl ist not complete for certain connectors, It would be better to create that with the help of trinos "Show create table" - command. I would like to fix that too. Would you prefer a new pull request and/or issue for that?

**Comment by LonwoLonwo** [comment]
Could you provide a code snippet here, and then I will tell you - will it be ok to add it to the main code? To avoid reverts.

**Comment by EinWesen** [comment]
Sure. (It will affect the delta and hive connector for example, showing the with-clause for the create table)

```java
   @Override
    public String getTableDDL(DBRProgressMonitor monitor, GenericTableBase sourceObject, Map<String, Object> options) throws DBException {
        GenericDataSource dataSource = sourceObject.getDataSource();
        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read trino table DDL")) {
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
                    "SHOW CREATE TABLE " +
                            DBUtils.getQuotedIdentifier(sourceObject.getCatalog()) + "." +
                            DBUtils.getQuotedIdentifier(sourceObject.getSchema()) + "." +
                            DBUtils.getQuotedIdentifier(sourceObject) + "\n")) {
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                    if (dbResult.next()) {
                        return dbResult.getString(1);
                    } else {
                        // Trino uses multiple sources, just in case there is one that does not provide a result
                        return "-- Generated generic DDL \n" +
                                DBStructUtils.generateTableDDL(monitor, sourceObject, options, false);
                    }
                }
            }
        } catch (SQLException e) {
            throw new DBException(e, dataSource);
        }
    }
```

**Comment by LonwoLonwo** [comment]
Yeah, it also looks great. 

You can add it to your code.

But please change 

```
"SHOW CREATE TABLE " +
                            DBUtils.getQuotedIdentifier(sourceObject.getCatalog()) + "." +
                            DBUtils.getQuotedIdentifier(sourceObject.getSchema()) + "." +
                            DBUtils.getQuotedIdentifier(sourceObject) + "\n")) {
```

on the

```
"SHOW CREATE TABLE " + sourceObject.getFullyQualifiedName(DBPEvaluationContext.DDL))) {
```

And use the capital letter "T" for Trino in DBUtils.openMetaSession for both methods.

**Comment by EinWesen** [comment]
I added the commit.

fyi, there is also a "show create view" command. I decided initially against it, because i prefered using parameters to using a quoted sql string. Since i needed the show command for table anyway now, we could do the same for the view if you want them to work in a similiar way.

**Comment by LonwoLonwo** [comment]
Yeah, it will probably be easier to read with the "show create view" command in the code. You can change it.

**Comment by EinWesen** [comment]
Done.

**Comment by EinWesen** [comment]
@LonwoLonwo 
I don't wanna be that guy, but do you know when you will be able to test?

**Comment by LonwoLonwo** [comment]
Hello @EinWesen 

We are still waiting for the test environment with views from our teammates. When they finish this part, the QA Team will test this PR.

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
