### PR TITLE
#21038 refactor Oceanbase model code - remove extra code, read routin…

### LINKED ISSUE #21038: [OceanBase] Foreign key/references disappear from table properties
### Description

Foreign key disappears from table properties after creation

### DBeaver Version

23.2.0

### Operating System

Any

### Database and driver

MySQL 5.7.25
MySQL Connector Java mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )

### Steps to reproduce

1. Start creating a new table
2. Add a foreign key
3. Save changes
4. Click refresh button

**Expected:** Foreign key is shown
**Actual:** Right after creation foreign key is colored green like it's not saved and disappears after refresh. The only way to see it again is to refresh the whole database

### Additional context

https://github.com/dbeaver/dbeaver/assets/82543000/e03d9180-a2ad-4ff8-a2e1-6f95c9546972

### LINKED ISSUE #21039: [OceanBase] Can't create view through UI
### Description

Dbeaver doesn't allow creating view through UI because it thinks the view with this name already exists (temporary view appears in Navigator during creation process)

### DBeaver Version

23.2.0

### Operating System

Any

### Database and driver

MySQL 5.7.25
MySQL Connector Java mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )

### Steps to reproduce

1. Right-click on views folder and select `create new view`
2. Type anything into source tab and click save, then persist

**Expected:** View is created
**Actual:** DDL query isn't even sent and error shows that the view with this name already exists

### Additional context

```
org.jkiss.dbeaver.model.exec.DBCException: View with name 'NewView123342' already exists. Choose another name
	at org.jkiss.dbeaver.ext.mysql.edit.MySQLViewManager$1.beforeExecute(MySQLViewManager.java:141)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistAction(DBExecUtils.java:357)
	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:40)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:206)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:122)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:384)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:382)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1253)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### LINKED ISSUE #21061: [OceanBase] Hyperlink in SQL editor works only for fully-qualified names
### Description

Ctrl+left click won't open the data editor for the table if the name doesn't contain database name

### DBeaver Version

23.2.0

### Operating System

Any

### Database and driver

MySQL 5.7.25
MySQL Connector Java mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )

### Steps to reproduce

1. Type a table name in the SQL editor
2. Ctrl+click on the name

**Expected:** Table is opened in the new tab
**Actual:** Nothing happens

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LonwoLonwo**
remove extra code, read routines correctly; read functions parameters correctly

Please check the following:

- [x] compare navigator tree nodes for Oceanbase with the previous DBeaver version - the nodes list must be the same (no extra triggers, procedures are in the list, etc.)
- [x] create and check in the navigator list some procedures and functions with and without parameters
- [x] check functions parameters list reading (if no IN parameters - only Return parameter in the list)
- [x] working with metadata nodes - tables, views, databases, columns - ability to create/edit/delete
- [x] metadata objects refreshing on the node level and on the container level

### CODE REVIEW

**Review by E1izabeth — COMMENTED** [review]
I believe the classes you deleted were created for some purpose. Are they really doesn't bring something new comparing to MySQL's classes?

**Comment by LonwoLonwo** [comment]
Nope.

OceanbaseValueHandlerProvider was empty
OceanbaseMySQLDatabaseManager had the same methods as MySQLDatabaseManager
OceanbaseMySQLProcedure, OceanbaseMySQLView, OceanbaseMySQLTable nothing new here and incorrect cache

Probably all these classes exist because the contributor didn't know about `treeInjection` and didn't use the correct cache for objects (not inherited)

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
Refresh hides procedures/functions from the navigator until reconnect


https://github.com/dbeaver/dbeaver/assets/82543000/01539b6d-d28f-409d-a419-435258dcb87f

**Comment by LonwoLonwo** [comment]
Refresh procedures fixed.

**Comment by Matvey16** [comment]
Verified

**Comment by LuckyPickleZZ** [comment]
@LonwoLonwo 
I am very sorry for the increase in your workload. 
If there are any future usage issues, you can directly contact me to fix them. 🙏

**Comment by LonwoLonwo** [comment]
Hello @LuckyPickleZZ 

We are open to contributions. If you have any ideas on how to enhance Oceanbase in DBeaver - please, welcome :)

**Pull request merged**
