### PR TITLE
#16887 Expand/collapse individual cells

### LINKED ISSUE #16887: Allow to expand grid cells that contain collections in them
Add expand single cell 
And expand to a row

### PR DESCRIPTION
**Pull request by ShadelessFox**
https://user-images.githubusercontent.com/35821147/176406400-2e0d03d7-8ece-4763-918e-0aaf86333be4.mp4

Please ensure that both normal and record views work against relational and document databases.

### CODE REVIEW

**Comment by uslss** [comment]
NPE appears in case of an attempt to expand a row in Record mode
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Jun 30 14:25:46 CEST 2022
NullPointerException

java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.toggleRowExpand(LightGrid.java:3431)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.toggleCellValue(SpreadsheetPresentation.java:1314)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.toggleCellValue(Spreadsheet.java:364)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.navigateLink(SpreadsheetPresentation.java:1269)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.lambda$1(Spreadsheet.java:350)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:270)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```
RebbJAoNRj

**Comment by uslss** [comment]
Custom data types elements in pg are shown as n/a for now and cannot be expanded in record mode

dbeaver_oPN5kg7Nbz

Also, custom data types are broken in Oracle and mongodb
dbeaver_k9HLT87iND

image

**Comment by uslss** [comment]
for now, custom types cannot be expanded in Record mode
image

**Comment by ShadelessFox** [comment]
Only arrays can be expanded at the moment

**Pull request merged**
