### PR TITLE
#11345 Boolean text presentation configurator

### PR DESCRIPTION
**Pull request by ShadelessFox**
image

Please note that this PR **does not** include:
1. Image checkbox colorization support
2. Assertions against malicious input in text mode

To do list:
- [x] ~Rewrite configuration page code because event system is ugly~
- [x] ~Checkboxes in property tree viewer are aligned to the left while resting ignoring the user-defined configuration~
- [x] ~Verify user input before saving (avoid having empty values)~
- [x] ~Localize strings~

### CODE REVIEW

**Review by LonwoLonwo — APPROVED** [review]

**Comment by ghYura** [comment]
Any custom text input available?

**Comment by ghYura** [comment]
No **bold text** option?

**Comment by ShadelessFox** [comment]
Current implementation does not have such option. See to-do note: https://github.com/dbeaver/dbeaver/issues/11345#issuecomment-920173213

**Comment by ghYura** [comment]
> Current implementation does not have such option. See to-do note: [#11345 (comment)](https://github.com/dbeaver/dbeaver/issues/11345#issuecomment-920173213)

Got it. Deleted my comment here as soon as I saw your edited comment there. (A)synchronous user-Github-developer interaction :) But ~~relink~~ mention to my deleted comment here in issue 11345 still there (was). A bug of Github(?)

**Comment by ShadelessFox** [comment]
You mean the mention? It will persist because that's how GitHub works :^)

**Pull request merged**
