### PR TITLE
dbeaver/pro#1263 Use drop-down menu with ordering and filters on colu…

### PR DESCRIPTION
**Pull request by serge-rider**
…mn click

### CODE REVIEW

**Review by ShadelessFox — CHANGES_REQUESTED** [review]
This icon looks terrible due to having huge margins. Can we use a smaller one?

Before:
d8Qq53uGKA

After:
image

Notice how stretched it looks 😟

**Comment by uslss** [comment]
The sorting icon isn't visible until it was used
dbeaver_6vcwfHlQ3s

**Comment by serge-rider** [comment]
We removed sorting arrow on purpose (to reduce amount of icons on the screen).

Maybe we shouldn't leave empty space as well (it is supposed to use drop-down icon + ordering selection)). However it may look not very good..

**Comment by serge-rider** [comment]
We disabled order by single click (now you need to click menu, then order asc/desc).
Menu and sort icons were swaped.

**Review by ShadelessFox — APPROVED** [review]

**Pull request merged**
