### PR TITLE
#18999 Treat composite as null if its data is null

### LINKED ISSUE #18999: Regression in 22.3.4: can't edit composite type fields in data editor when initial value is NULL
### Description

When using the data editor to edit a field of a composite type, the new values are only registered if the field is NOT NULL before the edition. Otherwise, the cell doesn't retain the input value. It does work when the initial value of the field is a record containing only NULL values.

Possibly introduced in #18866?

Log entries from trying to edit a NULL composite field (see steps to reproduce below):
```
!ENTRY org.jkiss.dbeaver.model 2 0 2023-02-07 17:37:29.405
!MESSAGE Null owner value for 'supplier_id', row 8

!ENTRY org.jkiss.dbeaver.model 2 0 2023-02-07 17:37:53.614
!MESSAGE Null owner value for 'price', row 8

!ENTRY org.jkiss.dbeaver.model 2 0 2023-02-07 17:38:22.942
!MESSAGE Null owner value for 'name', row 8
```

### DBeaver Version

Community Edition 22.3.4

### Operating System

Windows 10

### Database and driver

PostgreSQL 12.10
PostgreSQL JDBC Driver 42.5.0

### Steps to reproduce

1. Create testing set:
```pgsql
CREATE TYPE inventory_item AS (
	name text,
	supplier_id integer,
	price numeric(5,2)
);

CREATE TABLE test (
	id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	item inventory_item
);

INSERT INTO test (item)
VALUES
	(('Item 1', 1, 1.99)),
	(('Item 2', 2, NULL)),
	(('Item 3', NULL, 3.5)),
	(('Item 4', NULL, NULL)),
	((NULL, 3, 0.87)),
	((NULL, 4, NULL)),
	((NULL, NULL, 2.34)),
	((NULL, NULL, NULL)),
	(NULL);
```

2. Open table `test` in the data editor. Note the last 2 rows appear the same way, but in row 8 `item` is a record of NULLs, while in row 9 it's just a NULL.

3. Try to update any of the subfields from column `item` in the last row. The cells shouldn't retain the inserted values.

4. Try to update any of the subfields from column `item` in any of the other rows, including the second-to-last. It should work as expected.

### Additional context

No tunnels or proxy
Extensions installed: Office support, git support, Debug and SVG

### PR DESCRIPTION
**Pull request by ShadelessFox**
Also, please check #16822, #15698, and #14113.

### CODE REVIEW

**Comment by serge-rider** [comment]
I'm afraid it may cause regression as it changes model behavior. 
Probably we need unit tests here.

**Comment by ShadelessFox** [comment]
Unit tests for what exactly?

**Comment by serge-rider** [comment]
For NULL composite types. How we hanle them and how we handle composites with all fields set to NULL.
It may be not easy to implement though..

**Comment by DariaMarkaryan** [comment]
can't save added data to NULL-record if 'Show compex columns structure' is off.
checked another tickets - they're OK

https://user-images.githubusercontent.com/43252954/221949539-ac01020c-9bd9-4b75-b298-1e79c62eb125.mp4

**Comment by DariaMarkaryan** [comment]
Verified

**Pull request merged**
