### PR TITLE
Add main eclipse nl fragments to nls.feature and  move all l10n properties file to core.nls

### PR DESCRIPTION
**Pull request by liuyuanyuan**
Add main eclipse nl fragments to org.jkiss.dbeaver.runtime.nls.feature for eclipse standard parts,
and  move all l10n properties file from org.jkiss.dbeaver.core to org.jkiss.dbeaver.core.nls .

### CODE REVIEW

**Review by ruspl-afed — CHANGES_REQUESTED** [review]
Default *.properties resource bundles should be kept inside the host bundle
1) bundle.properties should be kept on original location
2) CoreResources.properties should be kept on original location

The eclipse platform nl fragments should be a part of another feature that we didn't introduced yet, now the fragments you refernced are not available during build
3) please revert the changes for feature.xml

**Comment by liuyuanyuan** [comment]
I'll move default *.properties resource bundles back and restore feature.xml.

But Eclipse platform nl fragments just need to install eclipse babel, their host plug-ins are already in DBeaver :)

**Review by ruspl-afed — APPROVED** [review]

**Comment by ruspl-afed** [comment]
Thanks for contribution!
You are right regarding Eclipse nl fragments - the host part is already inside DBeaver. But we need to tune our build scripts before we can include Babel fragments. This why I asked you to revert feature.xml for now.

**Comment by liuyuanyuan** [comment]
OK, ruspl-afed~ Thanks for your reply~
When you include Babel, please inform me and I'll add the fragments then ^_^

**Pull request merged**
