### PR TITLE
#19866 Find node with missing nodes in-between

### PR DESCRIPTION
**Pull request by ShadelessFox**
Test cases:
- [x] Toggle from Advanced to Simple view (will find node)
- [x] Toggle from Simple to Advanced view (will not find node)

image

### CODE REVIEW

**Comment by E1izabeth** [comment]
Why can't we always find the node?

**Comment by MashaKorax** [comment]
Cant toggle from Custom to Advanced


https://github.com/dbeaver/dbeaver/assets/84867187/cf2b5313-fd4c-4a3c-b99c-110de0e19948

**Comment by ShadelessFox** [comment]
@E1izabeth Node path is not unique, it's based on the folder structure in the navigator.

In the simple view, we can have:
```
DataSource1
    Table1
    Table2
    Table3
```

But in the advanced view, we can have:
```
DataSource1
    Database1
        Schema1
            Table1
        Schema2
            Table2
    Database2
        Schema3
            Table3
```

If we have the path `DataSource1/Database1/Schema1/Table1`, it's possible to find `Table1` even if `Database1` and `Schema1` are missing. In the opposite case when we have just `DataSource/Table1`, it's impossible to determine where that `Table1` is stored. It might be `Database1/Schema2`, `Database1/Schema2`, or `Database2/Schema3`. That's why this only works when switching from the advanced view to the simple view.

**Comment by ShadelessFox** [comment]
@MashaKorax custom view's parameters match the advanced view's parameters. This is expected.

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
