### PR TITLE
dbeaver/pro#1245 Detach result tabs

### PR DESCRIPTION
**Pull request by ShadelessFox**
image

### CODE REVIEW

**Comment by E1izabeth** [comment]
Do queries and results still come to sql terminal from such result set?

**Comment by ShadelessFox** [comment]
You can't detach the SQL terminal.

**Comment by E1izabeth** [comment]
Do SQL Terminal still get updates when you detached tab and press Refresh?

**Comment by ShadelessFox** [comment]
No. The detached tab behaves like it was disposed, so the terminal is no longer listening for its updates.

**Comment by E1izabeth** [comment]
Can't we subscribe on these events for the detached tab?

**Comment by ShadelessFox** [comment]
I don't think it's necessary. Why?

**Comment by E1izabeth** [comment]
For me it looks like the functionality of fetching results for the concrete tab by SQL Terminal becomes broken after tab detaching.

**Comment by serge-rider** [comment]
I think we should detach results to the bottom placeholder, not in editors tab. Thus it should be a view, not an editor.

**Comment by ShadelessFox** [comment]
Views can't be dirty, and we must manually close them upon exiting the application. Not sure if it's a good trade-off.

**Comment by MashaKorax** [comment]
Verified

**Pull request merged**
