### PR TITLE
dbeaver/pro#2451 Remove unnecessary default table model from CTE handling common for different SQL statements (not only select, but delete, update, insert)

### PR DESCRIPTION
**Pull request by E1izabeth**

### CODE REVIEW

**Review by Destrolaric — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Now column names in any DDL or DML are highlighted in dark blue if they are quoted
image

**Comment by E1izabeth** [comment]
It is expected behavior. We haven't implemented any validation for create/delete/update/insert statements. Now only fallback is implemented to make it work as before.

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
