### PR TITLE
#21442 #21443 Fix create schema with the existing schema's name.

### LINKED ISSUE #21442: [Dameng] Error appears on attempt to change default schema with name in lowercase
### Description

Error appears on attempt to change default schema with name in lowercase

https://github.com/dbeaver/dbeaver/assets/31996417/23119586-905b-4efe-af24-98b9fbcc01e3

### DBeaver Version

23.2.2

### Operating System

win10

### Database and driver

Dameng

### Steps to reproduce

_No response_

### Additional context

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Dziyana\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Oct 05 17:07:33 CEST 2023
Error in line: 1
Invalid schema name [TEST1]

dm.jdbc.driver.DMException: Error in line: 1
Invalid schema name [TEST1]
	at dm.jdbc.driver.DBError.throwException(DBError.java:711)
	at dm.jdbc.a.b.o.x(MSG.java:591)
	at dm.jdbc.a.b.o.C(MSG.java:526)
	at dm.jdbc.a.b.o.B(MSG.java:507)
	at dm.jdbc.a.a.a(DBAccess.java:245)
	at dm.jdbc.a.a.a(DBAccess.java:729)
	at dm.jdbc.driver.DmdbStatement.executeInner(DmdbStatement.java:730)
	at dm.jdbc.driver.DmdbStatement.do_execute(DmdbStatement.java:190)
	at dm.jdbc.driver.DmdbStatement.do_execute(DmdbStatement.java:182)
	at dm.jdbc.util.DriverUtil.execute(DriverUtil.java:309)
	at dm.jdbc.driver.DmdbConnection.do_setSchema(DmdbConnection.java:1227)
	at dm.jdbc.driver.DmdbConnection.setSchema(DmdbConnection.java:2110)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.setSchema(JDBCConnectionImpl.java:578)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:325)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:313)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.changeDefaultObject(DBExecUtils.java:447)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.setExecutionContextDefaults(DBExecUtils.java:406)
	at org.jkiss.dbeaver.ui.actions.datasource.SelectActiveSchemaHandler$2.run(SelectActiveSchemaHandler.java:210)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```

### LINKED ISSUE #21443: [Dameng] It is possible to create schema with the existing schema's name.
### Description

It is possible to create a schema with the existing schema's name.

Schema duplicates already existing schema and disappear after refresh

https://github.com/dbeaver/dbeaver/assets/31996417/56b02b20-f7b6-4872-beeb-e31f43301d2f

### DBeaver Version

23.2.2

### Operating System

win10

### Database and driver

dameng

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Stkai**

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Hello @Stkai 

Thanks for the contribution.

I'm not sure that it can help with the case #21442


And about this one.

We already have code to check the object's persistent status. If I try to create a schema with an existing name in PostgreSQL, I will get the following:

```
org.jkiss.dbeaver.DBException: Object 'dc' already exists
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectCreateCommand.validateCommand(SQLObjectEditor.java:357)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:99)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$CreateJob.run(NavigatorHandlerObjectCreateBase.java:230)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Why is it not happening for DamengSchema?
Because it always have status:

```java
public boolean isPersisted() {
        return true;
}
```

From the GenericObjectContainer.

You can override this method for the DamengSchema class and add a boolean `persist` and a new constructor or setter for DamengSchemaManager (because on the creation step in the manager - the object does not persist already).

Like in the PostgreSchema.

**Comment by Stkai** [comment]
I know this,Now I have changed to this method,but it is always case sensitive. Can I determine whether it is case sensitive based on the database configuration?

**Comment by LonwoLonwo** [comment]
I will take a look at it.

**Comment by LonwoLonwo** [comment]
Okey, I checked.

And it is always correct for the schema "test" and schema "TEST".
And it is working for the default schema changing.

2023-10-27 15_17_18-DBeaver Ultimate 23 2 3 - gpadmin

2023-10-27 15_20_04-DBeaver Ultimate 23 2 3 - gpadmin

So, what is the question? Because it is working

**Review by LonwoLonwo — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
