### PR TITLE
#17919 add shortcut for create new database object

### PR DESCRIPTION
**Pull request by SiyaoIsHiding**
Implementing the feature requested in #17919 

There is a challenge I met:
The commands to create new database objects, including a new column and a new index, are grouped in one command `org.jkiss.dbeaver.core.object.create`. Therefore, it is hard to create a shortcut for a new column only, unless we split the commands or do not use the RCP built-in bindings extension. But I think a shortcut for other new database objects, including a new index, is also a good idea.

### CODE REVIEW

**Comment by Matvey16** [comment]
Verified

**Comment by arhayka** [comment]
Thank you for your contribution! There are some notes:
1. This `Cmd+ | Ctrl+` shortcut conflicts with the standard Windows that enables zooming.  It's better to use the one [used in Data Editor ](https://github.com/dbeaver/dbeaver/wiki/Shortcuts#result-set)(`Alt+Insert`).
2. This shortcut does nothing when you can add multiple objects. It should open a list with available options.

**Comment by E1izabeth** [comment]
Would you correct your PR according to the [mentioned issues](https://github.com/dbeaver/dbeaver/pull/19963#issuecomment-1611215677)?

**Comment by SiyaoIsHiding** [comment]
Sorry that we no longer work on this project :)

**Pull request closed without merging**
