### PR TITLE
#21441 Fix Dameng sequence cannot be edited on its creation via UI

### LINKED ISSUE #21441: [Dameng] Sequence cannot be edited on its creation via UI
### Description

Cannot change any data for sequence on its creation via UI

image

### DBeaver Version

23.2.2

### Operating System

win10

### Database and driver

Dameng

### Steps to reproduce

1. Connect to Dameng
2. Try to create new Sequnce using context menu in DB Navigator - Only Sequence name could be set. Other values are read-only

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Stkai**

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Hello @Stkai 

But why did you change the path to the "damengSequences"? You already read sequences in the DamengMetaModel#prepareSequencesLoadStatement and createSequenceImpl. 

You can change these methods and not create a new cache.

**Comment by LonwoLonwo** [comment]
Hello @Stkai 

This is a small reminder, that I still waiting an answer for https://github.com/dbeaver/dbeaver/pull/22474#issuecomment-1894083249

**Comment by LonwoLonwo** [comment]
I implemented part of your logic here: https://github.com/dbeaver/dbeaver/pull/22988

Thanks for your contribution!

**Comment by Stkai** [comment]
Thank you, very good, I'm very sorry I didn't reply recently

**Pull request closed without merging**
