### PR TITLE
#17654 #17064 SQL Terminal

### LINKED ISSUE #17064: Add option to include server output in console view
It would be useful to include the "database server output" in the console view, so that those server messages are collated with the rowset data.

This could be toggled via a config setting:
image

Consider a (MSSQL) script like this (from [comment on #667](https://github.com/dbeaver/dbeaver/issues/667#issuecomment-565182905)):
```sql
print 'Explanation for data set 1';
select ... from ...;

print `Explanation for data set 2`;
select ... from ...;

. . . etc . . .
```

Behavior as of 22.1.2.202207091909 puts printed messages only in the server output window.
image

Desired output (query text removed for clarity):
```txt
Explanation for data set 1

| # | v |
+---+---+
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |

3 row(s) fetched.

Explanation for data set 2

| # | v |
+---+---+
| 1 | a |
| 2 | b |
| 3 | c |

3 row(s) fetched.
```
> See #17014 for discussion on including query text in the console view

### LINKED ISSUE #17654: Refactor SQL Terminal
We need to remove early startup from data.console plugin and create new extension point for sql terminal to let sql editor somehow  handle such contributions.

### PR DESCRIPTION
**Pull request by E1izabeth**
- Refactoring
- Preference to add query text
- Preference to add server output

### CODE REVIEW

**Comment by uslss** [comment]
1. Looks like Terminal opens more than once
dbeaver_nEFRXjBMyK

**Comment by uslss** [comment]
2. Output data is shown after the sql query result even if it was executed before query
dbeaver_YoA5UQxlNY

**Comment by uslss** [comment]
3. Focus is set on the statistics tab instead of resultset (probably, another issue is needed)

dbeaver_AFigEClXxF

**Comment by E1izabeth** [comment]
2. That's how the server output is fetched. We discussed and don't want to change it for now.
3. I guess it's this issue #17763

**Comment by uslss** [comment]
verified

**Pull request merged**
