### PR TITLE
dbeaver/dbeaver#20817 Execution plan load fix (was broken in dbeaver/…

### LINKED ISSUE #20817: [MySQL] Load execution plan not working
### Description

loading of saved execution plan opens empty result tab
image

tested for simple select query. the same plan correctly works in previous DBeaver version

### DBeaver Version

23.1.3

### Operating System

win10

### Database and driver

_No response_

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by serge-rider**
…pro#1526)

### CODE REVIEW

**Comment by serge-rider** [comment]
Please test it in MySQL, PostgreSQL, Vertica, SQL Server

**Comment by Matvey16** [comment]
Execution plan is hidden until any query is executed

https://github.com/dbeaver/dbeaver/assets/82543000/c300ff27-f231-4ba5-ad75-a41b9964cbca

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
