### PR TITLE
#18550 supports RisingWave database

### LINKED ISSUE #18550: Support for RisingWave Streaming Database
**Is your feature request related to a problem? Please describe.**
Support [RisingWave](https://www.risingwave.com/) Streaming Database in DBeaver

**Describe the solution you'd like**
RisingWave is an open-source cloud-native streaming database compatible with PostgreSQL. We only need to enable a subset of DBeaver PostgreSQL features supported by RisingWave so we will have a RisingWave implementation for `PostgreServerExtensionBase`.

**Describe alternatives you've considered**
Using native PostgreSQL driver doesn't work since the default port/user/database are different and there are some PostgresSQL features that not supported in RisingWave (e.g. trigger, tablespace, ...).

### PR DESCRIPTION
**Pull request by LonwoLonwo**
2024-01-24 18_28_33-DBeaver Ultimate 23 3 3 - taxi_trips

2024-01-24 18_29_28-Connect to a database

No triggers
No sequences
No foreign keys
No languages
No encodings
Table DDL from database
View/Materialized view DDL from database
No NULL/NOT NULL column modifiers (please check PostgreSQL, that NULL/NOT NULL still there)
Also, please check the constraints reading (we need a separate ticket for PK reading for RisingWave) and check constraints reading in any PostgreSQL

Note for developers - changes in PostgreSchema are intentional.

PS: I'm not sure about local clients support. Leaved as is for now.

### CODE REVIEW

**Comment by uslss** [comment]
- [x] No triggers
- [x] No sequences
- [x] No foreign keys
- [x] No languages
- [x] No encodings
- [x] Table DDL from database
- [x] View/Materialized view DDL from database
- [x] No NULL/NOT NULL column modifiers (please check PostgreSQL, that NULL/NOT NULL still there)
- [x] Also, please check the constraints reading (we need a separate ticket for PK reading for RisingWave) and check constraints reading in any PostgreSQL

**Comment by uslss** [comment]
1. Table DDL reading doesn't working
image

**Comment by LonwoLonwo** [comment]
Added fix for tables/views reading

**Comment by uslss** [comment]
verified

**Pull request merged**
