### PR TITLE
#18701 Fix editor area node drag-n-drop

### PR DESCRIPTION
**Pull request by ShadelessFox**
Please make sure the fix works on **all platforms!!!**

Acceptance criteria:
- [ ] Dragging resource nodes (scripts, etc) to the desktop copies them
- [ ] Dragging database nodes (tables, views, etc) to the editor area opens them
- [ ] Dragging any navigator nodes to the text editor inserts their names
- [ ] #17415

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Comment by MashaKorax** [comment]
Fix doesnt work on Mac and Linux.

**Comment by MashaKorax** [comment]
https://user-images.githubusercontent.com/84867187/231438605-dcadd677-086e-470f-9f90-0b6d3fb60c2f.mp4

everything below the node with connections does not open (bookmarks, scripts etc.)

**Comment by MashaKorax** [comment]
https://user-images.githubusercontent.com/84867187/231689340-13f119de-cfb7-4898-901a-bcb7c8cc7b8c.mp4

now only scripts can be opened (on mac and windows behavior is the same)


**event loop exception** -error
`
org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at org.eclipse.ui.internal.ide.EditorAreaDropAdapter.asyncDrop(EditorAreaDropAdapter.java:130)
	at org.eclipse.ui.internal.ide.EditorAreaDropAdapter.lambda$0(EditorAreaDropAdapter.java:87)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:297)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
`

**Comment by ShadelessFox** [comment]
The issue is that the DND mechanism picks the first appropriate transfer and proceeds with it, ignoring all other potential transfer candidates. Let's imagine the following situation:

1. We told Eclipse that the navigator could provide these transfers: files and editor inputs
2. If we drag a database node, it would pick file transfer because it was first, yet the node doesn't represent a resource

Do you see the issue? And we can't do anything about it.

I was thinking about manually constructing `FileEditorInput`s for all files that represent resources. It might do the job.

**Pull request closed without merging**
