### PR TITLE
fixed small issue with if-condition

### PR DESCRIPTION
**Pull request by GiantCrocodile**
if-condition was always true

### CODE REVIEW

**Comment by serge-rider** [comment]
Can't figure out does this have any special meaning.
Andrew should check this..

**Comment by AndrewKhitrin** [comment]
Clemens,

Thank for your review and comments.
I apologize for the delay in replying.

Can you clarify please - why condition  root.waitThis().size() > 0  (....not OR EQUAL)?

LockGraphManager placed graph nodes on levels, calculate level "width" for visualisation and so on.

The source of nodes is the plugin of specific databases, at this moment - Postgres, Oracle and Exasol but this is not a final list (I hope) and in the future for other DBs there may be a situation of a "degenerated" graph that will consist of only one root node. In this case condition "root.waitThis().size() >= 0" cant be replaced with "root.waitThis().size() > 0". In other words I guess condition "root.waitThis().size() >= 0" now is not necessary at all - because its always true :) This is a legacy of LockGraphManager version of the manager that could not build degenerate graphs.

Can you fix your PR or I can create patch too.

Thanks again for the review.
Andrew.

**Comment by GiantCrocodile** [comment]
Hello @AndrewKhitrin,

feel free to add a patch to make it appropriate. I'm busy for some time and I'm not sure I know how you would like to see this patched :). You are welcome!

Best Regards!

**Comment by AndrewKhitrin** [comment]
Hello, Clemens

Ive try to push cahnges but I have no access to  GiantCrocodile/dbeaver.git :

remote: Permission to GiantCrocodile/dbeaver.git denied to AndrewKhitrin.
fatal: unable to access 'https://github.com/GiantCrocodile/dbeaver.git/': The requested URL returned error: 403

Can you give me permission for completing PR ?

**Comment by GiantCrocodile** [comment]
I've invited you to the repository @AndrewKhitrin! Sorry for missing this :).

**Comment by AndrewKhitrin** [comment]
Nevermind.

I've commit patch and rebase to devel branch.

Everything ready for merge.

Thanks for review.
Andrew.

**Pull request merged**
