### PR TITLE
Add support for DolphinDB

### LINKED ISSUE #35405: DolphinDB support
This ticket is created to track external PR that adds support for DolphinDB (version>=3.0).

DolphinDB is a distributed time-series database. It supports distributed computing and storage，real-time data processing and offers a comprehensive suite of built-in functions for statistical analysis.

Additionally, DolphinDB’s community version is free to use and test.

Details: https://github.com/dbeaver/dbeaver/pull/34990

### PR DESCRIPTION
**Pull request by peeyee**
This pull request adds support for DolphinDB(version>=3.0), enabling users to access DolphinDB more conveniently and user-friendly.

DolphinDB is a distributed time-series database. It supports distributed computing and storage，real-time data processing and offers a comprehensive suite of built-in functions for statistical analysis.

Additionally, DolphinDB’s community version is free to use and test.

image

image

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
Thank you for contribution!

**Review by serjiokov — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Hello @peeyee 

Do you have the ability to use a transparent background for your icons? We also need to support the dark theme.
You can take a look at the MachBase icon as an example.

**Comment by peeyee** [comment]
> Hello @peeyee
> 
> Do you have the ability to use a transparent background for your icons? We also need to support the dark theme. You can take a look at the MachBase icon as an example.

Okay, I will change to transparent icons in the next PR.

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
Thank you for updating icons. We passed your PR to our QA team for testing

**Comment by peeyee** [comment]
Okay, thanks. You can use the following links to deploy DolphinDB and test:
[Standalone Deployment](https://docs.dolphindb.com/en/Tutorials/standalone_deployment.html)
[Database Catalog](https://docs.dolphindb.com/en/Database/Catalog.html)

**Comment by uslss** [comment]
Verified.
Related issues created:
#35620 #35621 #35622

**Comment by arhayka** [comment]
Hello @peeyee!
Thank you for being with DBeaver! We appreciate your support and want to send you a compliment. Please write to an email [anna.pozdeeva@dbeaver.com](mailto:anna.pozdeeva@dbeaver.com) and provide your nickname in GitHub and shipping details: Name and Surname, Email, Contact phone, Full Address (apt, street, city, state, country, post code).

**Pull request merged**
