### PR TITLE
Create feature for eclipse nl fragments. 

### PR DESCRIPTION
**Pull request by liuyuanyuan**
Create feature named org.jkiss.dbeaver.eclipse.nl.feature to manage eclipse nl fragments, and add it to org.jkiss.dbeaver.rcp.feature.

### CODE REVIEW

**Comment by serge-rider** [comment]
I've already fixed import - so it can't be merged without conflict.
Not sure about inclusion of this fragment in rcp (rcp is for standard Eclipse stuff). 
org.jkiss.dbeaver.core looks as a better place..

**Comment by liuyuanyuan** [comment]
Serge, thanks~
org.jkiss.dbeaver.eclipse.nl.feature is feature, it cannot be added to org.jkiss.dbeaver.core, and its inclusion are Eclipse language fragments, so I add to org.jkiss.dbeaver.rcp.feature.
Although you have fixed import, the PR shows no conflicts but check failed. I'm not sure about this, how about close this and PR again?
Thanks and regards.

**Comment by ruspl-afed** [comment]
The failed CI indicates that you need to perform several extra actions to include the new feature\fragment to the distribution. Let me do that for you, then you can move translations to the corresponding fragments.

**Comment by liuyuanyuan** [comment]
Thanks ruspl-afed~ Possiablly because I didn't create pom.xml file for org.jkiss.dbeaver.eclipse.nl.feature.
Notes: org.jkiss.dbeaver.eclipse.nl.feature is a feature, it' will include the eclipse standard language fragments  for the eclipse standard part in DBeaver.

**Comment by ruspl-afed** [comment]
I created NLS feature https://github.com/serge-rider/dbeaver/tree/devel/features/org.jkiss.dbeaver.runtime.nls.feature
and NLS fragment https://github.com/serge-rider/dbeaver/tree/devel/bundles/org.jkiss.dbeaver.core.nls for https://github.com/serge-rider/dbeaver/tree/devel/plugins/org.jkiss.dbeaver.core
Please use it.

I moved *_ru* resources to NLS fragment to give you an example

**Comment by liuyuanyuan** [comment]
OK~

**Pull request closed without merging**
