### PR TITLE
dbeaver/pro#1951 Fix broken quotes

### PR DESCRIPTION
**Pull request by ShadelessFox**

### CODE REVIEW

**Review by E1izabeth — COMMENTED** [review]
Could you try renaming database in mysql? Does your changes fix this too?
image

**Comment by ShadelessFox** [comment]
Yes:
image

**Review by E1izabeth — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Comment by Matvey16** [comment]
There are many places like this, where we now have double quote
chrome_1o5KG6NHIw
y0syHA6ZGm

**Review by E1izabeth — APPROVED** [review]

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
