### PR TITLE
dbeaver/pro#1759 update icons

### PR DESCRIPTION
**Pull request by Destrolaric**
Closes dbeaver/pro#1759

### CODE REVIEW

**Comment by E1izabeth** [comment]
Please provide screenshots

**Comment by Destrolaric** [comment]
image

**Review by ShadelessFox — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Please create a list of changed database icons/logos for testers.

Like 

- [ ] DB2
- [ ] Pervasive
- [ ] H2

etc.

**Comment by Destrolaric** [comment]
## Icons
- [ ] - DB2
- [ ] - H2(except h2GIS)
- [ ] - MSACCESS
- [ ] - neo4j
- [ ] - nuodb
- [ ] - omnisci
- [ ] - openedge
- [ ] - opensearch
- [ ] - orientdb
- [ ] - pervasive
- [ ] - phoenix
- [ ] - presto
- [ ] - salesforce
- [ ] - sapmaxdb
- [ ] - snappy
- [ ] - solr
- [ ] - spark
- [ ] - sqlite
- [ ] - sqream
- [ ] - tdendine
- [ ] - trino
- [ ] - virtuoso
- [ ] - sap_hana
- [ ] - sybase
- [ ] - MSSQL
- [ ] - sybase
- [ ] - mariadb
- [ ] - mysql
- [ ] - oceanbase
- [ ] - opendistro
- [ ] - oracle
- [ ] - postgresql
- [ ] - redshift
- [ ] - timescale
- [ ] - yellowbrick
- [ ] - yugabyte
- [ ] - tidb
- [ ] - vertica
- [ ] - wmi

### Enterprise Edition
- [ ] - cassandra

## Logos
- [ ] - DB2
- [ ] - H2
- [ ] - MSAccess
- [ ] - neo4j
- [ ] - omnisci
- [ ] - orientdb
- [ ] - pervasive
- [ ] - phoenix
- [ ] - presto
- [ ] - salesforce
- [ ] - sapmaxdb
- [ ] - snappy 
- [ ] - solr
- [ ] - spark hive
- [ ] - sqlite
- [ ] - sqream
- [ ] - trino
- [ ] - virtuoso
- [ ] - sap hana
- [ ] - sybase
- [ ] - mariadb
- [ ] - mysql
- [ ] - oceanbase
- [ ] - oracle
- [ ] - postgresql
- [ ] - redshift
- [ ] - timescale
- [ ] - yellowbrick
- [ ] - yugabyte
- [ ] - snowflake
- [ ] - vertica

### Enterprise Edition
- [ ] - cassandra

**Review by LonwoLonwo — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Pull request closed without merging**
