### PR TITLE
dbeaver/pro#2144 VQB checkbox layout fixed

### PR DESCRIPTION
**Pull request by serjiokov**
VQB checkbox layout fixed
image

### CODE REVIEW

**Comment by serjiokov** [comment]
image
just to be sure

**Review by E1izabeth — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Comment by MashaKorax** [comment]
Please delete routing from VQB
Снимок экрана 2023-11-22 в 13 15 49

**Comment by MashaKorax** [comment]
Compare entity in PR and release version https://github.com/dbeaver/pro/wiki/Sample-databases#postgresql-10 

Снимок экрана 2023-11-22 в 13 28 40




Снимок экрана 2023-11-22 в 13 34 10

**Comment by serjiokov** [comment]
Looks good for me 
image

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
