### PR TITLE
dbeaver/dbeaver#22305 Added Functions support for Snowflake SQL Editor

### LINKED ISSUE #22305: [Snowflake] add more SQL functions words
### Description

datediff() and getdate() functions are not recognized by Dbeaver

### DBeaver Version

Community version 23.3.0

### Operating System

Win 11 PRO 23H2

### Database and driver

Snowflake, snowflake jdbc driver

### Steps to reproduce

1. Make a connection
2. Write `select getdate()` 
3. See that it doesn't change color

### Additional context

image

### PR DESCRIPTION
**Pull request by sarveshhiwase**
Added functions support for Snowflake SQL Editor [Issue Link](https://github.com/dbeaver/dbeaver/issues/22305)

The functions that are added are all referenced from [https://docs.snowflake.com/en/sql-reference/functions-all](https://docs.snowflake.com/en/sql-reference/functions-all)
- There are lot of functions present in the documentation, but I have only added support which where present in dbeaver repository at time of making this PR (Reason - Already present functions were all generic and mostly covers all scenarios for developers)
- In future, we can surely add the functions in file, whenever needed.

### Before - 
[https://github.com/dbeaver/dbeaver/issues/22305#issue-2062742622](https://github.com/dbeaver/dbeaver/issues/22305#issue-2062742622)
### After -
Screenshot from 2024-01-19 15-00-07
Screenshot from 2024-01-19 14-31-47
Screenshot from 2024-01-19 14-27-03

### CODE REVIEW

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Thanks for your contribution @sarveshhiwase 

It looks good to me.

Now, we are waiting for a second reviewer and QA Team.

**Comment by sarveshhiwase** [comment]
> Thanks for your contribution @sarveshhiwase
> 
> It looks good to me.
> 
> Now, we are waiting for a second reviewer and QA Team.

Thanks @LonwoLonwo for the review 🧪.
Surely will wait ⏳️ and will be contributing more 🚀.

Happy Coding👨‍💻!

**Comment by LonwoLonwo** [comment]
Hello again @sarveshhiwase 

Could you please change the formatting and set keywords in one column, not in two?
Like here https://github.com/dbeaver/dbeaver/blob/4584687584ef1e8379100afa028fec87852fd415/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDialect.java

**Comment by sarveshhiwase** [comment]
> Hello again @sarveshhiwase 
> 
> 
> 
> Could you please change the formatting and set keywords in one column, not in two?
> 
> Like here https://github.com/dbeaver/dbeaver/blob/4584687584ef1e8379100afa028fec87852fd415/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDialect.java

@LonwoLonwo sure i can do that, but don't you think that will make the file like really long?

**Comment by LonwoLonwo** [comment]
> that will make the file like really long?

It is just our code style. So it's ok, yes.

**Comment by sarveshhiwase** [comment]
> > that will make the file like really long?
> 
> It is just our code style. So it's ok, yes.

Sure, understood 📙, will do the changes.

**Comment by sarveshhiwase** [comment]
@LonwoLonwo Please check ✅ now, hope you find it good! 🤞
Thanks for your help 💁.

**Comment by LonwoLonwo** [comment]
Looks much better now, thanks!

And, I do not see the `getdate` in the list of functions (https://docs.snowflake.com/en/sql-reference/functions-all). Probably, we can't add it.

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
It is PRO compatible now, I've checked (no duplicates)

**Comment by E1izabeth** [comment]
@LonwoLonwo I believe we'd like to remove enumerated in this PR keywords from SnowflakeSQLDialectExt class to prevent keywords definition duplication. It requires PR to the private repository from our side.

**Comment by LonwoLonwo** [comment]
Thanks again for your contribution.

This implementation will be available in the next DBeaver version, 23.3.4, on 05-02-2024.

**Comment by sarveshhiwase** [comment]
Thank you @LonwoLonwo for accepting the PR, and for all the help 💁🏻‍♀️ you did which helped me understanding the whole workflow.
Would be contributing more.
Happy Coding! 👨🏻‍💻

**Pull request merged**
