### PR TITLE
Changes for performance of Redshift multirow insert

### PR DESCRIPTION
**Pull request by deepaksenthilkumar**
The following issue didn't get fixed properly for Redshift 
https://github.com/dbeaver/dbeaver/issues/11425

The problem is in the Redshift JDBC Driver class PGEscaper which becomes exponentially slow with the number of question marks in the INSERT statement. 

Added RedshiftValueHandlers that implement DBDValueBinder that prevents the use of ? in the code.

This gives a huge performance improvement in Redshift for 1 M records with 3 columns. 

It took 17 hours (with multirow insert--Only possible setting is batch size 100 anything more hangs and commit every 100k records) to 4 mins now (batch size 10k, commit every 100k records).

### CODE REVIEW

**Comment by deepaksenthilkumar** [comment]
In the regression of dbeaver#13482
Noticed fff7f is the hexstring returned by Redshift for geometry.

Added code to handle that scenario.

**Comment by ShadelessFox** [comment]
Thanks for the contribution, but unfortunately we can't accept it.

**Please create a new PR that will contain code that is related to the issue itself.**

1. Instead of creating a bunch of dummy classes and a separate method `getRedshiftValueHandler` in [`PostgreValueHandlerProvider`](https://github.com/dbeaver/dbeaver/pull/13482/files#diff-4229eeda6249bc37a298ada521202bde5681285d186e26300b738e8034800101R131), you can achieve the same result using  `PostgreDialect#escapeScriptValue`, which is more convenient.
2. What's the point of modifying `JDBCTable` [here](https://github.com/dbeaver/dbeaver/pull/13482/files#diff-ec8c005fda2c83e87dd065ef3de7def455f6254f6aecf327ead339b27d199671R367-R373)? By doing that, you broke multirow insert in SQL Server.
3. The issue with geometry type is unrelated, so it must not be included here. Although you can provide more information about the problem in #13283

Also, looks like something went wrong with the formatting, fix it too. We use spaces instead of tabs, please follow our code style.

**Comment by ShadelessFox** [comment]
My eye can't catch a particular change that led to this improvement in performance. Can you highlight me the key changes so we can help cooperate with you?

**Comment by deepaksenthilkumar** [comment]
The key change is to not use ? and ind variables directly (it's a redshift Postgres version bug). If we bind it directly then it caused issue in Data viewer insert (JDBC table). 

@ShadelessFox -Do you mean we can get the dialect and edit PostgreStringValueHandler instead of adding a RedshiftStringValueHandler? This bug is specific to Redshift. So, I thought it's better to just handle it for Redshift classes.

**Comment by ShadelessFox** [comment]
What do you mean by the bug? The issue was in a poor performance of multirow insert. Have you tried installing different driver versions? Is the performance the same?

I don't get what you mean by `bind values directly`, isn't `?` the only way to achieve that in prepared statements?

**Comment by deepaksenthilkumar** [comment]
The issue is when you use multi row inserts, the number of question marks increase in the prepared statement and the Redshift driver (Postgres flavor) becomes terribly slow (exponentially proportional to the number of question marks) at handling a regex check they have. 

The biggest problem is we can’t use 2.x drivers as the current implementation of DBeaver is reliant on Postgres flavor of the driver that has this performance issue. Using  2.x redshift driver breaks many other things like navigator, generation of DDL, etc. And even in the 1.x version, DBeaver has currently recommended to stop upgrade due to other issues.

Based on what I have tested I could see performance of 1M inserts is extremely fast (4 mins vs 17 hours) by directly setting the values in the insert instead of using the ? and binding prepared statement. I didn’t want to change anything for Postgres, as the issue is specific to Redshift. I can change my fix to use Postgres dialect and the value handler classes for redshift which will skip the use of bind variables. I assume that’s why DBDBinder exists? 

Can we do this just for multi row insert of Redshift without impacting any other database?

Pasting my comments that I posted last week last week in https://github.com/dbeaver/dbeaver/issues/11425
 
I checked further and noticed the problem is in the Redshift JDBC Driver class PGEscaper which becomes exponentially slow with the number of question marks in the INSERT statement. I made a couple of crude changes (just to confirm that) and noticed now I am able to insert 1M records in 8 mins. (with a setting of 10k multi-row insert batch size and commit after 10k records)

In `ExecuteInsertBatchImpl` hardcode the string (should handle it better)
```java
if (valueHandler instanceof DBDValueBinder) {
    valuesPart.append(((DBDValueBinder) valueHandler).makeQueryBind(attribute, attributeValues[i]));
} else if (useMultiRowInsert) {
    valuesPart.append(attributeValues[i] == null ? null : "'" + attributeValues[i].toString() + "'");
} else {
    valuesPart.append("?"); //$NON-NLS-1$
}
```

Avoided binding in `ExecuteBatchWithMultipleInsert`:
```java
private void bindAndFlushStatement(DBDValueHandler[] handlers, DBCStatistics statistics, DBCStatement batchStatement, Object[] allMultiInsertValues) throws DBCException {
    statistics.setQueryText(batchStatement.getQueryString());
    statistics.addStatementsCount();
    if (batchStatement.getQueryString().contains("?")) {
        bindStatement(handlers, batchStatement, allMultiInsertValues);
    }
    batchStatement.addToBatch();
    flushBatch(statistics, batchStatement);
}
```

Any suggestion on how we make this fix proper would be helpful. Thanks for your help in introducing this feature.

**Comment by ShadelessFox** [comment]
The main problem with manual binding is SQL injection. For example, string value may contain some malicious payload, and we don't want to allow user to shoot himself in the foot. I don't think we want to follow Redshift approach and invent our own version of `PGescaper` just to escape values. This is the primary reason of my concern.

The idea of passing values directly without binding them first is a great, since bind operation is expensive and it can drastically improve data transfer performance not just for Redshift but for other databases too.

I can suggest you to provide a new option in Data Transfer Wizard (so user can toggle it) to bypass binding values. You can pass this option in `prepareQueryForStatement` and if it is set, then pass values directly (or at least use `SQLDialect#escapeScriptValue` to somehow escape values) without binding them. And this option must be exposed in the UI with descriptive tip with its cons and pros.

You can create a separate feature request and work on it.

**Comment by deepaksenthilkumar** [comment]
Thank @ShadelessFox that makes total sense. I will do that.

**Pull request closed without merging**
