### PR TITLE
dbeaver/dbeaver#18383 Native script execute config UI fixes

### LINKED ISSUE #18383: Make field for path to postgres script editable
This field isn't editable, unlike all of the other places where we should choose path to file
image

### PR DESCRIPTION
**Pull request by serge-rider**

### CODE REVIEW

**Comment by E1izabeth** [comment]
Shouldn't we validate that the path is correct and not empty?

**Comment by ShadelessFox** [comment]
It would be a nice addition, indeed. Now it's working just as before, but now you can enter whatever you want in that field.

**Comment by Matvey16** [comment]
Clicking on input field opens OS explorer to pick a file, which makes editing impossible

dbeaver_KeUCSYVJ9w

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
