### PR TITLE
InterSystems IRIS latest stable - 2024.1

### PR DESCRIPTION
**Pull request by isc-rsingh**
Updated InterSystems IRIS JDBC driver location to point to latest stable version - 2024.1.

### CODE REVIEW

**Review by Imran-imtiaz48 — COMMENTED** [review]
The pull request updates the path to the JDBC driver from version 3.6.1 to 3.8.4. This change is crucial for ensuring the application uses the latest version of the driver, which might include important bug fixes, performance improvements, and new features.
Improvements:
1.	Compatibility Check: Ensure that the new JDBC driver version 3.8.4 is compatible with the existing codebase and does not introduce any breaking changes.
2.	Testing: Perform thorough testing to verify that the application behaves as expected with the new driver. This includes running existing test suites and possibly adding new tests to cover any new features or changes in behavior introduced by the updated driver.
3.	Documentation: Update any relevant documentation to reflect the change in the JDBC driver version. This ensures that other developers and stakeholders are aware of the update and its implications.
4.	Dependency Management: Consider adding a process for regular reviews and updates of dependencies to keep the project up-to-date with the latest versions and security patches.

**Review by E1izabeth — APPROVED** [review]

**Comment by isc-rsingh** [comment]
I have tested this version of the driver with DBeaver built from this repo

**Comment by E1izabeth** [comment]
We passed your PR to our QA team for testing

**Comment by E1izabeth** [comment]
Thank you for contribution

**Comment by uslss** [comment]
verified

**Pull request merged**
