### PR TITLE
#14669 Add missing Babelfish queries

### PR DESCRIPTION
**Pull request by okeuday**
@serge-rider Would it be possible to put this into 21.3.0 ?

### CODE REVIEW

**Comment by serge-rider** [comment]
Unfortunately no, we are in the code freeze stage now.
New changes will be available in the 21.3.1 and in the Early Access version.

It also may be included in DBeaver EE 21.3.0.

**Comment by Matvey16** [comment]
@okeuday I can't see sequences in Navigator or schema properties
dodHTssXLq
TZeEebidic

**Comment by okeuday** [comment]
@Matvey16 That is normal due to Babelfish currently lacking `sys.sequences`.  The [query used instead](https://github.com/dbeaver/dbeaver/blob/425cf111277372253a6cc6d98b01a99e7e1f986d/plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/SQLServerUtils.java#L179) uses `TOP 0` to provide the column types without rows.  When `sys.sequences` is added on the server-side, the client-side query can be removed.

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
