### PR TITLE
#17700 Fix parsing of statements with if for Snowflake

### LINKED ISSUE #17700: Create Snowflake Procedure
### Description

This produces an error

CREATE OR REPLACE PROCEDURE testproc()
RETURNS varchar
LANGUAGE SQL AS 
$$
DECLARE 
	i int;
BEGIN 
	i:=1;
	IF (i=1) THEN
		i:=2;
	END IF;
	IF (i=2) THEN
		i:=3;
	END IF;	
END
$$;

SQL Error [1003] [42000]: SQL compilation error:
parse error line 14 at position 7 near '<EOF>'.
syntax error line 4 at position 1 unexpected '$'.
syntax error line 14 at position 7 unexpected '<EOF>'.

If i remove the second if/then block, it succeeds.
If i use Snowflake's web interface, it will succeed as is.

it looks as if DBeaver is not submitting the whole script; the red highlight lines stop before the last END

### DBeaver Version

Version 22.2.0.202209051344

### Operating System

Windows 10 64bit

### Database and driver

Snowflake jdbc Driver

### Steps to reproduce

1.

CREATE OR REPLACE PROCEDURE testproc()
RETURNS varchar
LANGUAGE SQL AS 
$$
DECLARE 
	i int;
BEGIN 
	i:=1;
	IF (i=1) THEN
		i:=2;
	END IF;
	IF (i=2) THEN
		i:=3;
	END IF;	
END
$$;

get error

2.   remove second if/then block  process succeeds

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by E1izabeth**
Query from issue should be correctly parsed now.

### CODE REVIEW

**Review by ShadelessFox — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Comment by uslss** [comment]
verified

**Comment by jdechter** [comment]
This issue is back in version [DBeaver 23.0.5]

**Comment by E1izabeth** [comment]
The query from your example in the issue still works for me. If you have another example of the query that doesn't work now, please, provide it.

**Comment by jdechter** [comment]
Here is an example;

EXECUTE IMMEDIATE 
$$
DECLARE
	P_ACCOUNT VARCHAR DEFAULT 'X';
	P_TIN VARCHAR DEFAULT 'Y';
	P_NAME VARCHAR DEFAULT 'Z';
	P_CLAIM VARCHAR DEFAULT 'Z';
	P_DOS DATE DEFAULT '9/7/2022';
	p_ALLOWED number default 290;
	CLEANFNAME VARCHAR;
	CLEANLNAME VARCHAR;
	CLEANCLAIM VARCHAR;
	SOUNDEXFNAME VARCHAR;
	SOUNDEXLNAME VARCHAR;
	V_BU VARCHAR;
	res RESULTSET;
BEGIN
	V_BU := 'DX';

	CLEANFNAME := CAST(UPPER(REGEXP_REPLACE(SPLIT_PART(:P_NAME, ' ', 1), '[^[:alpha:]]', '')) AS VARCHAR(50));
	CLEANLNAME := CAST(UPPER(REGEXP_REPLACE(SPLIT_PART(:P_NAME, ' ', 2), '[^[:alpha:]]', '')) AS VARCHAR(50));
	CLEANCLAIM := CAST(REGEXP_REPLACE(:P_CLAIM, '[^[:alnum:]]', '') AS VARCHAR(50));
	SOUNDEXFNAME := SOUNDEX(UPPER(REGEXP_REPLACE(SPLIT_PART(:P_NAME, ' ', 1), '[^[:alpha:]]', '')));
	SOUNDEXLNAME := SOUNDEX(UPPER(REGEXP_REPLACE(SPLIT_PART(:P_NAME, ' ', 2), '[^[:alpha:]]', '')));

CREATE OR REPLACE
TEMP TABLE results ( BU varchar,
	INV_NUM varchar,
	CLEANLNAME varchar,
	CLEANFNAME varchar,
	SOUNDEXF varchar,
	CLEANCLAIM varchar,
	DOS date,
	BILLED_AMT number,
	PAID_AMT number,
	ADJ_AMT number,
	 BALANCE number ,
	MATCH_TYPE varchar,
PF_MATCH number);

if (V_BU = 'PT') then 
insert into results
SELECT
	BU,
	INVOICEHEADER_ID INV_NUM,
	CLEANLNAME,
	CLEANFNAME,
	SOUNDEXF,
	CLEANCLAIM,
	DOS ,
	SUM(AMTALIGNBILL) BILLED_AMT,
	SUM(AMTPAYMENT) PAID_AMT,
	SUM(AMTADJUSTMENT)ADJ_AMT,
	SUM(BALANCE) BALANCE,
	MATCH_TYPE, PF_MATCH
FROM
	(
SELECT
		IH.INVOICEHEADER_ID,
		ID.INVOICEDETAIL_ID,
		UPPER(REGEXP_REPLACE(R.PATIENTNAMELAST, '[^[:alpha:]]', '')) CLEANLNAME,
		UPPER(REGEXP_REPLACE(R.PATIENTNAMEFIRST, '[^[:alpha:]]', '')) CLEANFNAME,
		SOUNDEX(REGEXP_REPLACE(R.PATIENTNAMEFIRST, '[^[:alpha:]]', '')) SOUNDEXF,
		REGEXP_REPLACE(IFNULL(CF.CLAIMNUMBER, R.CLAIMNUMBER ) , '[^[:alnum:]]') CLEANCLAIM,
		CAST(ID.SERVICEDATETIME AS DATE) AS DOS,
		ID.CPTCODE,
		ID.AMTALIGNBILL,
		ID.AMTPAYMENT,
		ID.AMTADJUSTMENT,
		ID.AMTALIGNBILL - ( ID.AMTPAYMENT + ID.AMTADJUSTMENT + ID.AMTREFUND + ID.AMTCHARGEBACK ) BALANCE ,
		CASE
			WHEN RD.INVOICEDETAIL_ID IS NULL THEN 'PT'
			ELSE 'PT-R'
		END BU,
		'ACCOUNT' MATCH_TYPE,0 PF_MATCH
	FROM
		PROD_ENT_WAREHOUSE.ALIGN_DBO.INVOICEHEADER IH
	JOIN PROD_ENT_WAREHOUSE.ALIGN_DBO.INVOICEDETAIL ID
                              ON
		IH.INVOICEHEADER_ID = ID.INVOICEHEADER_ID
	JOIN PROD_ENT_WAREHOUSE.ALIGN_DBO.REFERRAL R
                              ON
		IH.REFERRAL_ID = R.REFERRAL_ID
	LEFT JOIN PROD_ENT_WAREHOUSE.CLAIMFEED_DBO.CLAIMFEED_ENTERPRISE CF
                              ON
		R.ALIGNCLAIMFEEDID = CF.ALIGNCLAIMFEEDID
		AND R.CLAIMFEEDCOMPANYID = CF.ALIGNPAYORID
	LEFT JOIN PROD_ENT_WAREHOUSE.REVENUECYCLE_DBO.RETROCLAIMDTL_HISTORY RD
                              ON
		RD.INVOICEDETAIL_ID = ID.INVOICEDETAIL_ID
		AND RD.ALIGNLINESTATUS = 'A'
	WHERE
		IH.INVOICEHEADER_ID =try_to_number( :P_ACCOUNT)
		AND DOS = :P_DOS 
union
	SELECT
		IH.INVOICEHEADER_ID,
		INVOICEDETAIL_ID,
		UPPER(REGEXP_REPLACE(RRM.PATIENTNAMELAST, '[^[:alpha:]]', '')) CLEANLNAME,
		UPPER(REGEXP_REPLACE(RRM.PATIENTNAMEFIRST, '[^[:alpha:]]', '')) CLEANFNAME,
		SOUNDEX(REGEXP_REPLACE(RRM.PATIENTNAMEFIRST, '[^[:alpha:]]', '')) SOUNDEXF,
		REGEXP_REPLACE(IFNULL(CF.CLAIMNUMBER, R.CLAIMNUMBER), '[^[:alnum:]]') CLEANCLAIM,
		CAST(ID.SERVICEDATETIME AS DATE) AS DOS,
		ID.CPTCODE,
		ID.AMTALIGNBILL,
		ID.AMTPAYMENT,
		ID.AMTADJUSTMENT,
		ID.AMTALIGNBILL - ( ID.AMTPAYMENT + ID.AMTADJUSTMENT + ID.AMTREFUND + ID.AMTCHARGEBACK ) BALANCE,
		'PT' BU,
		'NAME' MATCH_TYPE,0 PF_MATCH
	FROM
		PROD_ENT_WAREHOUSE.ALIGN_DBO.INVOICEHEADER IH 	
		JOIN PROD_ENT_WAREHOUSE.ALIGN_DBO.REFERRAL RRM ON IH.REFERRAL_ID = RRM.REFERRAL_ID
	JOIN PROD_ENT_WAREHOUSE.ALIGN_DBO.INVOICEDETAIL ID ON IH.INVOICEHEADER_ID = ID.INVOICEHEADER_ID
	JOIN PROD_ENT_WAREHOUSE.ALIGN_DBO.REFERRAL R ON IH.REFERRAL_ID = R.REFERRAL_ID
	LEFT JOIN PROD_ENT_WAREHOUSE.CLAIMFEED_DBO.CLAIMFEED_ENTERPRISE CF ON R.ALIGNCLAIMFEEDID = CF.ALIGNCLAIMFEEDID AND R.CLAIMFEEDCOMPANYID = CF.ALIGNPAYORID
	WHERE
		CLEANLNAME = :CLEANLNAME
		AND CLEANFNAME = :CLEANFNAME 
		AND ID.SERVICEDATETIME = :P_DOS
UNION
	SELECT
		id.INVOICEHEADER_ID,
		ID.INVOICEDETAIL_ID,
		UPPER(REGEXP_REPLACE(RH.PATIENTLNAME, '[^[:alpha:]]', '')) CLEANLNAME,
		UPPER(REGEXP_REPLACE(RH.PATIENTFNAME, '[^[:alpha:]]', '')) CLEANFNAME,
		SOUNDEX(REGEXP_REPLACE(RH.PATIENTFNAME, '[^[:alpha:]]', '')) SOUNDEXF,
		REGEXP_REPLACE(RH.CLAIMNUMBER, '[^[:alnum:]]') CLEANCLAIM,
		CAST(ID.SERVICEDATETIME AS DATE) AS PT_DOS,
		ID.CPTCODE,
		ID.AMTALIGNBILL,
		ID.AMTPAYMENT,
		ID.AMTADJUSTMENT,
		ID.AMTALIGNBILL - ( ID.AMTPAYMENT + ID.AMTADJUSTMENT + ID.AMTREFUND + ID.AMTCHARGEBACK ) BALANCE,
		'PT-R' BU,
		'NAME' MATCH_TYPE,0 PF_MATCH
	FROM
		PROD_ENT_WAREHOUSE.REVENUECYCLE_DBO.RETROCLAIMHDR_HISTORY RH
		JOIN  PROD_ENT_WAREHOUSE.REVENUECYCLE_DBO.RETROCLAIMDTL_HISTORY RD ON RD.RETROCLAIMHISTORYID = RH.RETROCLAIMHISTORYID AND RD.ALIGNLINESTATUS = 'A'
		JOIN PROD_ENT_WAREHOUSE.ALIGN_DBO.INVOICEDETAIL ID ON RD.INVOICEDETAIL_ID = ID.INVOICEDETAIL_ID
		--JOIN PROD_ENT_WAREHOUSE.ALIGN_DBO.INVOICEHEADER IH ON IH.INVOICEHEADER_ID = ID.INVOICEHEADER_ID
	WHERE
		CLEANLNAME = :CLEANLNAME
		AND CLEANFNAME = :CLEANFNAME
		AND PT_DOS = :P_DOS
)
GROUP BY
	INVOICEHEADER_ID,
	CLEANLNAME,
	CLEANFNAME,
	SOUNDEXF,
	CLEANCLAIM,
	DOS,
	BU,
	MATCH_TYPE ;
END IF;
END;
$$;

**Comment by jdechter** [comment]
If I remove the semicolon at line 156  (make "END IF;" = just "END IF" It will compile 
If I switch $$ quotes from code block to Sting literal, it will compile.

So Snowflake has no problem with the code,  DBeaver is not parsing correctly again

**Comment by E1izabeth** [comment]
I see. Thanks. Could you create a new issue with this example, please?
As a workaround you can highlight the whole your query and press run. Then the whole selected text will be send to the database as is and it will work.

**Pull request merged**
