### PR TITLE
#34887 [TRINO] Enable SQL based row limits for trino

### LINKED ISSUE #34887: Data preview forces full table Scan in Trino
### Description

If a trino cluster is configured with fault tolerant execution, queries are run to completion before results are returned. This means previewing a table in dbeaver ends up scanning the whole table and taking a lot of time, and potentially a huge amount of resources and storage for large tables.

Trino supports SQL limit statement, so we can enable SQL based row limiting in the plugin and make it the default for trino connections.

### DBeaver Version

Community Edition 24.1.2

### Operating System

Linux

### Database and driver

Default trino JDBC driver

### Steps to reproduce

1) Configure a trino cluster with TASK or QUERY retry policy and an exchange manager for fault tolerance
2) Preview any large table with DBeaver. The whole table contents will be read and the contents spooled to the exchange manager storage.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by schaffino**
When trino is configured with fault tolerant execution, queries are run to completion before results are returned. This means previewing a table in dbeaver ends up scanning the whole table and taking a lot of time, and potentially a huge amount of resources if its a very large table. Trino supports SQL limit statement, so enable SQL based row limiting in the plugin and make it the default for connections.

Fixes #34887

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
Thank you for contribution

**Review by HocKu7 — APPROVED** [review]

**Comment by E1izabeth** [comment]
We passed your PR to our QA team for testing

**Comment by schaffino** [comment]
@E1izabeth Any update on this PR?

**Comment by E1izabeth** [comment]
This PR is awaiting in a queue for testing.

**Comment by uslss** [comment]
verified

**Pull request merged**
