### PR TITLE
Ability to set remote host and port in ssh tunnel configuration

### PR DESCRIPTION
**Pull request by bsv798**
This patch allows advanced ssh tunnel configuration:

- tunnel through jump server: `ssh -L 5432:pg.example.com:5432 jump.example.com`
- remote port specification (if DBMS is runnning on non-default port): `ssh -L 5432:127.0.0.1:15432 pg.example.com`
- bind address specification (if DBMS is listening on specific interface): `ssh -L 192.168.5.11:5432:192.168.5.11:5432 pg.example.com`

I have added several fields in SSHTunnelConfiguratorUI.java and set default values in case these fields are not set in SSHImplementationAbstract.java:

- Local host (bind address). Default value: 127.0.0.1
- Local port. Default value: any free port with number > 10000
- Remote host. Default value: value of local host field
- Remote port. Default value: JDBC driver default port

Also, resource translations to german, french and chinese was made via google translate and may require manual correction.

### CODE REVIEW

**Comment by serge-rider** [comment]
Interesting. I'll try to test it.

**Comment by serge-rider** [comment]
Customizing localhost makes much sense. No questions here.

But jump server is questionable.
We will have 3 host/port pairs:
1. SSH server
2. Jump server
3. Database server

I'm not quite understand how jump server works. Is it a kind of second tunnel between ssh server and database server?

Like this: Client -> SSH Server -> Jump Server -> Database Server.

**Comment by p91paul** [comment]
Corporate security experts will never get tired of adding hops for people to jump through. Just add another layer of indirection they said, it will solve all your problems they said. :grin:

**Comment by bsv798** [comment]
@serge-rider 
Consider following diagram:
servers-diagram
All three servers are in the same network and **manager** server is the only one than can be accessed through the internet. You do not have direct access to **db** server through the internet. So you will have to establish ssh connection to **manager** server first and then use it to "jump" to **db** server (hence the name) and forward port from there to your host.
Configuration in dbeaver that allows you to do so is like this:
dbeaver-config
And appropriate ssh command: `ssh -L superuser@222.223.224.225 5432:192.168.5.3:5432`.

"Jump server" is just a fancy name. Such advanced tunnel can be configured with local host/port and remote host/port pairs.
And, of course, if your DBMS is on the same host that ssh daemon is, then you do not have to specify remote host/port values in dbeaver (they will be configured automatically anyway).

**Comment by bsv798** [comment]
Accidently closed PR. Sorry :)

**Comment by serge-rider** [comment]
This makes sense. And sources look good, thanks for contribution.
I will probably update UI a bit (as there are too many different options) after the merge.

BTW I think this PR will resolve ticket #4516. At least partially.

**Comment by serge-rider** [comment]
I've fixed a couple of bugs (NPE in parsing existing SSH config) and a couple of labels.
Unfortunately I can't fix labels in languages I don't know (de, fr, zh). Could you fix them?

`Remote port for tunnel. If set to <=0 then default port of JDBC driver will be acquired` is not exactly correct. It is database server port, not JDBC driver port.

**Comment by bsv798** [comment]
> Unfortunately I can't fix labels in languages I don't know (de, fr, zh). Could you fix them?
No, I do not know these languages either.

**Comment by yash3492** [comment]
@bsv798 
I have exactly same use-case like you described here. But for some reason it doesn't work with dbeaver Version 7.1.4.202008021649.

Below is command line version which is working for me:
```
ssh -L 54321:pg-rds.example.com:5432 deploy@jump-ec2-server.example.com
psql -h localhost -p 54321 -U deploy db_name
```
Within dbeaver SSH tunnel connection check is returning success, but thereafter DB connection test is timing out.

Many thanks in advance!

**Pull request merged**
