### PR TITLE
l10n: Update Spanish translation, part 1

### PR DESCRIPTION
**Pull request by adamantike**
Translations made using wiki's [Localization guide](https://dbeaver.com/docs/wiki/Localization/).

Part 1 of many, which I will be adding in separate PRs.

### CODE REVIEW

**Comment by serge-rider** [comment]
Thanks for the contribution!

I rill review it after 7.3.2 release.

**Comment by serge-rider** [comment]
Merge it now to avoid future merge conflicts as we going to do several refactorings.

I'll make Early Access version later today. Please verify the translation in UI.

**Comment by adamantike** [comment]
@serge-rider, are you pushing a new Early Access version for the Community Edition? I can see a new Enterprise Edition version was submitted in https://dbeaver.com/files/ea/update/dbeaver/, but not yet for the Community Edition in https://dbeaver.io/files/ea/.

**Comment by kseniiaguzeeva** [comment]
@adamantike Please check CE EA now https://dbeaver.io/files/ea/.

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen if something was not applied

**Comment by adamantike** [comment]
Everything looks good, thank you!

**Pull request merged**
