### PR TITLE
#17061 Allow hiding columns whose values within loaded rows are NULL

### LINKED ISSUE #17061: Hiding a column when all the rows matching this columns are empty or NULL
Hi,

I would like to know if there is a way to hide **dynamically** empty columns (all rows are empty on this column).
It is very time consuming searching for empty columns every query and display only usefull infos.

image

Thanks in advance for your answer.

### PR DESCRIPTION
**Pull request by ShadelessFox**
image

### CODE REVIEW

**Review by LonwoLonwo — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by uslss** [comment]
Column is hide even if there is data in a row that is not fetched for now
dbeaver_sJDGdxlFTt

**Comment by ShadelessFox** [comment]
This is an expected behavior. We don't want to reset visibility after fetching new data

**Comment by uslss** [comment]
verified

**Comment by deft01** [comment]
Its amazing thank you so much. Great job

**Pull request merged**
