### PR TITLE
dbeaver#18312 Complete some Simplified Chinese localization work

### PR DESCRIPTION
**Pull request by bianyun**
The missing properties files mentioned in issue #18312 haven't been created yet (PR #20464 did this, but haven't been merged yet), so localization in those places still doesn't work.

Therefore, based on the current latest version, I have localized Simplified Chinese for places that can be localized.

The list of modified or newly added property files is as follows:
<details>

```
  modified:   plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_zh.properties
  modified:   plugins/org.jkiss.dbeaver.data.transfer.ui/OSGI-INF/l10n/bundle_zh.properties
  modified:   plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/internal/DTUIMessages_zh.properties
  modified:   plugins/org.jkiss.dbeaver.data.transfer/OSGI-INF/l10n/bundle_zh.properties
  modified:   plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/internal/DTMessages_zh.properties
  modified:   plugins/org.jkiss.dbeaver.tasks.ui/OSGI-INF/l10n/bundle_zh.properties
  modified:   plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/internal/CoreApplicationMessages_zh.properties
  modified:   plugins/org.jkiss.dbeaver.ui.editors.data/OSGI-INF/l10n/bundle_zh.properties
  modified:   plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages_zh.properties
  modified:   plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/editors/data/internal/DataEditorsResources_zh.properties
  modified:   plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_zh.properties
  modified:   plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_zh.properties
  modified:   plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_zh.properties
  new file:   plugins/org.jkiss.dbeaver.ext.sample.database/src/org/jkiss/dbeaver/ext/sample/database/SampleDatabaseResources_zh_CN.properties
  new file:   plugins/org.jkiss.dbeaver.ui.editors.sql.terminal/OSGI-INF/l10n/bundle_zh_CN.properties
```
</details>

### CODE REVIEW

**Comment by bianyun** [comment]
@E1izabeth 
Hello, E1izabeth

I see a message saying `“E1izabeth linked an issue 2 hours ago that may be closed by this pull request”`, but this PR doesn't fix issue #18312, it's just to satisfy the format for submitting a PR (must specify an issue number). Issue #18312 should only be closed if PR #20464 is successfully merged.

**Comment by E1izabeth** [comment]
Thank you for explanation, we haven't reviewed your PR yet. I'll unlink it from that issue.

**Comment by E1izabeth** [comment]
Could you rename `zh_CN` files to just `zh`?

**Comment by bianyun** [comment]
@E1izabeth Of course, I will change it now.

**Review by E1izabeth — APPROVED** [review]

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
