### PR TITLE
Update GaussDB JDBC driver package - Synchronize with Huawei Cloud official website.

### PR DESCRIPTION
**Pull request by GaussDB-Fans**
Update GaussDB JDBC driver package - Synchronize with Huawei Cloud official website.

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Comment by MashaKorax** [comment]
verified

**Comment by GaussDB-Fans** [comment]
Do I need to manually resolve conflicts in my branch? thank you. @E1izabeth

**Comment by E1izabeth** [comment]
@GaussDB-Fans yes, could you do it, please?

**Comment by E1izabeth** [comment]
Thank you

**Pull request merged**
