### PR TITLE
dbeaver/dbeaver#21396 fix datasource and project variable resolver for shell commands

### LINKED ISSUE #21396: ${datasource} has a value in "Shell Command" settings but it is blank in embedded "SSH" tunnel settings
### Description

By opening the "variables" window in embedded "SSH" tunnel settings, you can see `${datasource}` doesn't show anything

### DBeaver Version

Community Edition 23.1.4

### Operating System

Manjaro 23.0

### Steps to reproduce

1. Create a connection and assign a "some random name" in `General > Connection name`
2. Save and click on `Connection Settings > SSH > You can use variables...` in the edit page to see "some random name" in front of `${datasource} `
3. You won't. It's blank.

### Additional context

This bug prevents creating new connections only by copying the earlier ones, and only changing the connection name, for use-cases such as in [my previous feature request](https://github.com/dbeaver/dbeaver/issues/21394).
(btw I use shell commands instead of embedded ssh settings but fixing this bug will be needed after adding the mentioned feature)

### PR DESCRIPTION
**Pull request by kgns**
`${datasource}` `${project.name}` `${project.path}` variables are not being resolved for Shell Commands even if they are listed (and resolved properly) on the UI as available variables that can be used.

The variable resolver the actual event processor uses (`DataSourceDescriptor.getVariablesResolver`) differs from the one UI uses (`DataSourceVariableResolver`), and it lacks these variables.

### CODE REVIEW

**Review by Destrolaric — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
For QA team - please also take a look on this case: https://github.com/dbeaver/dbeaver/issues/23041

**Comment by Matvey16** [comment]
Verified

**Comment by serge-rider** [comment]
We'd better use DataSourceVariableResolver instead.
I will look into it..

**Comment by kgns** [comment]
@serge-rider have you looked into it yet?

**Comment by LonwoLonwo** [comment]
Hello @kgns 

You can create a new PR with DataSourceVariableResolver.
Or you can wait for our team to solve this issue. But I will not promise that it will be soon.

**Comment by kgns** [comment]
If the better way is not ready yet (and seems like it will not be here anytime soon), I believe merging this fix (as it is just fixing how it is actually designed at the moment) now, and working on making it better whenever the team has the time for it would be a better way to move forward. Not merging this does not accomplish much other than making users not being able to use these variables as advertised and also make them create new GitHub issues about it making their and DBeaver team's lives worse

**Comment by serge-rider** [comment]
@kgns In fact existing variable resolver already provides variables you added in the previous PR.
Could you just check how it works in the new version o0f DBeaver? It is already included in 24.0.1.

**Comment by kgns** [comment]
Yes, I found the changes in this mega commit: https://github.com/dbeaver/dbeaver/commit/c4a9caf3a86219c2c6a2e12d3120fda9ef682fc7

It seems to be fixed, but not released with 24.0.1 yet, I believe it will be out with the release of 24.0.2

@LonwoLonwo "the better way" is already in, #21396 can be closed with 24.0.2 release

**Comment by LonwoLonwo** [comment]
Ok, thanks for noticing!

**Pull request closed without merging**
