### PR TITLE
#18747 update SQL Server, Babelfish and Azure drivers to version 11.2.3

### LINKED ISSUE #18747: Update Microsoft JDBC Driver version to 11.2.3
### Description

I am running DBeaver Version 22.3.2.202301060755 on MacOS 13.1 (M1 Pro)

I am running the same DBeaver Version on my Windows Machine. 

When I try to establish a connection to an AZURE SQL Server instance, the MacOS DBeaver fails to login, the Windows DBeaver does it perfectly. 

Error message on MacOS is: `Login failed for user '*********'. ClientConnectionId:79f5a76c-261d-46d7-88d9-f04b3539358b` (the ClientConnectionId naturaly changes every time)

### DBeaver Version

22.3.2.202301060755

### Operating System

MacOS 13.1 (M1 Pro)

### Database and driver

1. Azure MSSQL Server 
2. Microsoft JDBC Driver for SQL Server (MSSQL)
3. com.microsoft.sqlserver:mssql-jdbc:RELEASE 11.2.2.jre17

### Steps to reproduce

_No response_

### Additional context

No tunnels, no custom driver settings, factory settings

### PR DESCRIPTION
**Pull request by LonwoLonwo**
Please check the connections:

- [x] SQL Server
- [x] Azure
- [x] Babelfish
- [x] SQL Server (old)
- [x] SQL Server EE
- [x] Azure EE
- [x] Babelfish EE
- [x] SQL Server (old) EE
- [x] Sybase connection page
- [x] Sybase connection

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Comment by Matvey16** [comment]
The connection that worked before, now can't connect with this error

image

**Comment by LonwoLonwo** [comment]
https://github.com/microsoft/mssql-jdbc/issues/1775#issuecomment-1079371583

> 

> For security reasons, starting in [10.1.0 release](https://github.com/microsoft/mssql-jdbc/releases/tag/v10.1.0) there was a breaking change (thus the version bump) which defaulted the encrypt option to true (previously false) thus the driver will look for a certificate to validate unless trustServerCertificate is set to true (i.e. do not validate, trust all when encrypt option is enabled). It is recommended to to supply a certificate for validation for security reasons however if you want to revert back to the old pre-10.1.0 behavior you can just set encrypt=false in your connection string.

**Comment by ShadelessFox** [comment]
Can this option be disabled by default, then?

**Comment by LonwoLonwo** [comment]
2023-02-13 13_29_07-Window

Option moved from the SSL page to the main page. Checked by default.

**Comment by E1izabeth** [comment]
I don't think we should propose user to turn off server certificate validation on the main page.
I propose to do the following _"if you want to revert back to the old pre-10.1.0 behavior you can just set encrypt=false in your connection string"_

**Comment by LonwoLonwo** [comment]
I'm not sure because encrypt property is more confusing.

2023-02-13 14_09_27-Window

**Comment by E1izabeth** [comment]
Ok.

**Review by E1izabeth — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Pull request merged**
