### PR TITLE
outlook plugin + office plugin change + htmlcopypaste plugin

### PR DESCRIPTION
**Pull request by Arty68**
Office change: only selected rows and columns are displayed in excel if nothing selected everything is exported to excel
Outlook : open the selected rows in an new Outlook mail.
This need the powershell script (CopyHtml.ps1) in the main dbeaver directory
+ New Plugin htmlcopypaste

### CODE REVIEW

**Comment by serge-rider** [comment]
There are still pretty many *.prefs there.  Generally we don't need any new .settings/* files.
I could delete them all by myself but the problem is that PR is too huge, it is very hard to validate it.

**Comment by Arty68** [comment]
Hi thanks, I started yesterday to remove them. But I don't know git very well yet. I am still learning the basics so it took me look of time and couldn't remove all. Thanks for removing them.
What does PR mean ?
Thanks

**Comment by p91paul** [comment]
@Arty68 you can remove them with your favourite file manager, then commit all the removals together with `git commit -a`

Also you can add .settings to your gitignore and then git rm --cached the offending folders. This would remove the files from git but not from your filesystem! You don't need to commit after every removal, just at the end.

PR means Pull Request!

**Comment by Arty68** [comment]
@p91paul Thanks for Answer
@serge-rider I can submit another pull request for each plugin if needed

**Comment by Arty68** [comment]
@serge-rider Ok I will try to do it. But unfortunatly you will have to wait. I am very busy those days

**Comment by serge-rider** [comment]
No problem. 
We are making bug release on this week, so everyone is busy :)

**Comment by Arty68** [comment]
Hi

I've close the big pull request.
And started with the little pull request with the office plugin.
Once you accept the merge I will continue with the other pull request.


Le ven. 7 déc. 2018 à 17:09, Serge Rider <notifications@github.com> a
écrit :

**Pull request closed without merging**
