### PR TITLE
#16826 Metadata editor improvements

### LINKED ISSUE #16826: Table name column is empty in detail index of table
- Operating system : Mac os 12.3.1
- DBeaver version : 22.1.0

- Database name and version : postgres 11 

Table name column is empty in detail index of table.

CREATE TABLE public.table1 (
	id_table1 bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
	code text NULL,
	label text NULL,
	CONSTRAINT table1_pk PRIMARY KEY (id_table1)
);
CREATE INDEX table1_code_idx ON sg_reftech.table1 (code);

image

### PR DESCRIPTION
**Pull request by ShadelessFox**
#### Show comma-separated list of index columns:
java_J62p75VggC

#### Show em-dash over invalid (not applicable) cells:
java_2YR1vzKo5E

### CODE REVIEW

**Comment by uslss** [comment]
the column name isn't shown for db's like sqlite, mysql
image

**Comment by uslss** [comment]
still reproducible for, eg, ms sql, mysql, maria
image

**Comment by ShadelessFox** [comment]
Fixed for mssql, mysql, oracle and postgresql

**Comment by uslss** [comment]
verified

**Pull request merged**
