### PR TITLE
Update DataExporterHTML.java

### PR DESCRIPTION
**Pull request by Arty68**
For a prettyer html copy

image

### CODE REVIEW

**Comment by serge-rider** [comment]
Code looks good.
Please attach screenshot of final html (in browser).

**Comment by Arty68** [comment]
image

**Comment by Arty68** [comment]
> Code looks good.
> Please attach screenshot of final html (in browser).

Done

**Comment by serge-rider** [comment]
👍

**Comment by serge-rider** [comment]
I've fixed th/td styles, otherwise table with many columns looked quite strange.

**Comment by Arty68** [comment]
Thann you. I will check how I can change thé outlook plug in.

**Pull request merged**
