### PR TITLE
#17016 Fix struct expanding in record mode

### LINKED ISSUE #17016: Custom data types cannot be expanded in record mode
#### System information: 
- Operating system (distribution) and version win10 
- DBeaver version 22.1.2

#### Connection specification:
- Database name and version Postgres

#### Describe the problem you're observing:
Custom data types cannot be expanded in record mode
#### Steps to reproduce, if exist:
image

### LINKED ISSUE #17248: Array expand items doesn't work for NoSQL databases
### Description

https://user-images.githubusercontent.com/28875055/182627551-1e25807c-8ba7-405f-909a-0c23f744bdae.mp4

### Steps to reproduce

_No response_

### DBeaver Version

DBeaver 22.1.4

### Operating System

_No response_

### PR DESCRIPTION
**Pull request by ShadelessFox**
Structs are now expandable in record mode:
java_E6EI2zgLhx

Collections are now expandable in document-oriented DBs:
java_nC997PLAtF

### CODE REVIEW

**Comment by ShadelessFox** [comment]
Needs to be tested against PostgreSQL, MongoDB, and DynamoDB in various cases, including record mode.

**Comment by Matvey16** [comment]
Incorrect value panel for composite types in recor mode

dbeaver_VXagfo2Lzq

**Comment by Matvey16** [comment]
Sometimes value is not displayed for structs
dbeaver_vFhqsLEvug
dbeaver_9H8DfnYvmL

**Comment by Matvey16** [comment]
Two new tickets opened for above mentioned bugs

https://github.com/dbeaver/pro/issues/1133
https://github.com/dbeaver/pro/issues/1134

**Pull request merged**
