### PR TITLE
#12430 Shared SSH sessions

### LINKED ISSUE #12430: Shared SSH Tunnel Connection
**Is your feature request related to a problem? Please describe.**
Each database connection open a new SSH Tunnel even though they share the same SSH Tunnel, this need multiple authentication of the said SSH connection

**Describe the solution you'd like**
If database connections share the same SSH Tunnel and we have an active connection to the said SSH Tunnel then all subsequent database connection should use the same tunnel connection instead of opening another connection.

**Describe alternatives you've considered**
The alternative is to invoke the SSH tunnel externally (like using Putty) and point all the connections in DBeaver to localhost

### PR DESCRIPTION
**Pull request by ShadelessFox**
Test cases:
- Connect to multiple databases on different hosts simultaneously
- Do the same but with the same hosts
- Do the same but mix different and same hosts
- Try invaliding a connection with a shared session
- Do the same but with a connection without a shared session
- Try disconnecting a connection with a shared session
- Do the same but with a connection without a shared session
- Do all of the above with a different SSH implementation (JSCH, SSHJ)
- Blend all together and try your best to break everything 🙂 

To disable session sharing, use the following JVM property:
```
-Ddbeaver.ssh.disableSessionSharing=true
```

### CODE REVIEW

**Comment by Matvey16** [comment]
Thre is a problem with transactions. It gets rolled back without any warning if you invalidate another connection with the same tunnel. Maybe we shoudn't invalidate all of the connections with the same tunnel at the same time

STR
1. Create two connections with the same ssh tunnel
2. Connect to both
3. Open a transaction in one of them
4. Invalidate the other

Expected: Transaction is either still open or there is a pop-up asking for action with that transaction
Actual: Transaction is closed without any warning

**Comment by serge-rider** [comment]
I think we need to show warning message (e.g. `Transactions will be rolled back in the following connections:` )

**Comment by Matvey16** [comment]
There is an NPE when in tunnel connection in Cloud beaver
```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.DBPDataSourceContainer.getName()" because "container" is null
	at org.jkiss.dbeaver.model.net.ssh.AbstractSessionController$ShareableSession.connect(AbstractSessionController.java:423)
	at org.jkiss.dbeaver.model.net.ssh.AbstractSessionController$WrapperSession.connect(AbstractSessionController.java:336)
	at org.jkiss.dbeaver.model.net.ssh.AbstractSessionController$DirectSession.connect(AbstractSessionController.java:301)
	at org.jkiss.dbeaver.model.net.ssh.AbstractSessionController.acquireSession(AbstractSessionController.java:64)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initTunnel(SSHTunnelImpl.java:219)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:99)
	at io.cloudbeaver.service.core.impl.WebServiceCore.testNetworkHandler(WebServiceCore.java:765)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

chrome_fEK9r5anTy

**Comment by Matvey16** [comment]
Now there is another NPE in the same place

```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.DBPDataSourceContainer.getPreferenceStore()" because the return value of "org.jkiss.dbeaver.model.net.DBWHandlerConfiguration.getDataSource()" is null
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.closeTunnel(SSHTunnelImpl.java:191)
	at io.cloudbeaver.service.core.impl.WebServiceCore.testNetworkHandler(WebServiceCore.java:778)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
