### PR TITLE
#34552 [CUBRID] Create and edit Serial using UI

### LINKED ISSUE #34552: [CUBRID] Create and Edit Serial using UI
Allow an alternative option for user to create and edit Serial (aka. Sequence) using UI.
Noted: Serial is supported from version 11.2 up.

### PR DESCRIPTION
**Pull request by longhaseng52**
Allow an alternative option for user to create and edit Serial (aka. Sequence) using UI.

**Noted: Serial is supported from version 11.2 up.**

### CODE REVIEW

**Review by E1izabeth — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Comment by E1izabeth** [comment]
We passed your PR to our QA team for testing

**Comment by MashaKorax** [comment]
Hello @longhaseng52 
I can see in the interface parameter called **Last Value**
I suppose it should be called **START WITH** according to the documentation https://www.cubrid.org/manual/en/10.0/sql/schema/serial_stmt.html
dbeaver_Qaj2yjzpSI

**Comment by longhaseng52** [comment]
Hello @MashaKorax,

I have fixed an interface parameter called **Last Value** to **Start With** according to the documentation. Thank you.

**Comment by MashaKorax** [comment]
verified

**Pull request merged**
