### PR TITLE
#18628(trivial) Db2 naming/capitalization and consistency

### LINKED ISSUE #18628: (trivial) Update branding for IBM Db2
**Is your feature request related to a problem? Please describe.**

No functional problem, but the names of the Db2 connectors are not fully correct.
- IBM DB2 got renamed (relowercased?) to "IBM Db2" with a lowercase 'b' 🤷‍♂️
- IBM iSeries and AS/400 systems were replaced by IBM i nearly15 years ago. (the wire protocol is compatible so the same drivers are used for all of IBM i, iSeries, and AS/400 systems)

**Describe the solution you'd like**

Correct usage of "Db2" and consistent naming across the three Db2 options. Proposed:
- "Db2 for LUW"
- "Db2 for z/OS"
- "Db2 for IBM i"

**Describe alternatives you've considered**

Nothing. People can deal with it.

**Additional context**

I'll plan to ready a PR

### PR DESCRIPTION
**Pull request by ThePrez**
Fixes #18628

(not tested with a full DBeaver development build but the scope is trivial)

### CODE REVIEW

**Comment by ThePrez** [comment]
Verified with full build. Screenshots:

image

image

The screenshot made me realize the icon is technically out of date. I believe the proper replacement (if we care enough) is the Plex-style icon that can be found [here](https://www.ibm.com/design/language/iconography/app-icons/library). Screenshot for reference: 
image
Any preference on replacing the icon set with derivatives of this one, or keep the older, perhaps-more-familiar black and green?

**Comment by ThePrez** [comment]
pushed up a new logo set. I figure we might as well go with the new IBM Plex theme, but we can revert if needed

**Comment by E1izabeth** [comment]
Thank you for contribution.

**Comment by LonwoLonwo** [comment]
Renaming is ok, but logo changing - is not. Please revert it.

**Comment by ThePrez** [comment]
> Renaming is ok, but logo changing - is not. Please revert it.

No problem. Reverted.

**Review by E1izabeth — APPROVED** [review]

**Review by ShadelessFox — APPROVED** [review]

**Comment by uslss** [comment]
verified

**Pull request merged**
