### PR TITLE
dbeaver/pro#1409 Pass source document instead of resolved attribute

### PR DESCRIPTION
**Pull request by ShadelessFox**
Please test data transfer with transformed attributes **from**:
- [ ] CouchDB
- [ ] Couchbase
- [ ] DynamoDB
- [x] MongoDB
- [x] Redis

Also, please ensure that the transformed column contains different values in the source and, after transform, target tables.

### CODE REVIEW

**Review by LonwoLonwo — APPROVED** [review]

**Review by E1izabeth — APPROVED** [review]

**Comment by serge-rider** [comment]
Very risky change

**Comment by ShadelessFox** [comment]
I was unable to find any other solution.

I mentioned all databases affected by this change, so that's a matter of testing.

If tested thoughtfully, we might find any introduced bugs before the users.

**Comment by uslss** [comment]
mongo - pg: simple export to new table ends with an error
```

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Feb 28 15:51:42 CET 2023
Can't find target attribute [test!]

org.jkiss.dbeaver.model.exec.DBCException: Can't find target attribute [test!]
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchStart(DatabaseTransferConsumer.java:235)
	at com.dbeaver.db.mongodb.model.MGCollection.readData(MGCollection.java:293)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:126)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by uslss** [comment]
mongo - maria export to new table ends with an error

```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Feb 28 15:55:42 CET 2023
(conn=7700) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL,
	value VARCHAR NULL,
	`type` VARCHAR NULL,
	a VARCHAR NULL,
	ActorI...' at line 2

java.sql.SQLSyntaxErrorException: (conn=7700) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL,
	value VARCHAR NULL,
	`type` VARCHAR NULL,
	a VARCHAR NULL,
	ActorI...' at line 2
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
	at org.mariadb.jdbc.Statement.execute(Statement.java:1061)
	at org.mariadb.jdbc.Statement.execute(Statement.java:452)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistAction(DBExecUtils.java:334)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistActions(DBExecUtils.java:316)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferUtils.executeDDL(DatabaseTransferUtils.java:477)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetTable(DatabaseTransferConsumer.java:690)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetDatabaseObjects(DatabaseTransferConsumer.java:651)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.startTransfer(DatabaseTransferConsumer.java:618)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.lambda$1(DTTaskHandlerTransfer.java:123)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by uslss** [comment]
couchdb - maria, export to new table

```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Feb 28 15:58:25 CET 2023
(conn=7700) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL,
	`_rev` VARCHAR NULL,
	debug VARCHAR NULL,
	title VARCHAR NULL,
	na...' at line 2

java.sql.SQLSyntaxErrorException: (conn=7700) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL,
	`_rev` VARCHAR NULL,
	debug VARCHAR NULL,
	title VARCHAR NULL,
	na...' at line 2
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
	at org.mariadb.jdbc.Statement.execute(Statement.java:1061)
	at org.mariadb.jdbc.Statement.execute(Statement.java:452)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistAction(DBExecUtils.java:334)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistActions(DBExecUtils.java:316)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferUtils.executeDDL(DatabaseTransferUtils.java:477)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetTable(DatabaseTransferConsumer.java:690)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetDatabaseObjects(DatabaseTransferConsumer.java:651)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.startTransfer(DatabaseTransferConsumer.java:618)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.lambda$1(DTTaskHandlerTransfer.java:123)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by uslss** [comment]
couchdb-pg, export, new table

```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Feb 28 16:00:37 CET 2023
Can't find target attribute [couchdb]

org.jkiss.dbeaver.model.exec.DBCException: Can't find target attribute [couchdb]
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchStart(DatabaseTransferConsumer.java:235)
	at com.dbeaver.db.couchdb.model.CouchDBDatabase.readData(CouchDBDatabase.java:237)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:126)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by uslss** [comment]
cannot perform case from the ticket (mongo - maria) due to an error.

```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Feb 28 16:41:47 CET 2023
Row not fetched

org.jkiss.dbeaver.model.exec.DBCException: Row not fetched
	at com.dbeaver.db.mongodb.exec.MGResultSet.checkRowFetched(MGResultSet.java:125)
	at com.dbeaver.db.mongodb.exec.MGResultSet.getAttributeValue(MGResultSet.java:131)
	at com.dbeaver.db.mongodb.data.handlers.MongoBaseValueHandler.fetchValueObject(MongoBaseValueHandler.java:46)
	at com.dbeaver.db.mongodb.data.handlers.MongoDocumentValueHandler.fetchValueObject(MongoDocumentValueHandler.java:102)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchStart(DatabaseTransferConsumer.java:304)
	at com.dbeaver.db.mongodb.model.MGCollection.readData(MGCollection.java:293)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by uslss** [comment]
for now, issue from the ticket is reproducible

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Feb 28 19:37:20 CET 2023
BigInteger coercion: org.jkiss.dbeaver.model.impl.data.DBDValueError:(org.jkiss.dbeaver.model.exec.DBCException: 63bd3ee27dd8c0182f562d6b
	at org.jkiss.dbeaver.model.data.DBDAttributeBindingType.extractNestedValue(DBDAttributeBindingType.java:165)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeValue(DBUtils.java:832)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeValue(DBUtils.java:788)
	at org.jkiss.dbeaver.tools.transfer.transformers.DataTransferTransformerExpression$VariablesContext.get(DataTransferTransformerExpression.java:77)
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:922)
	at org.apache.commons.jexl3.parser.ASTIdentifier.jjtAccept(ASTIdentifier.java:61)
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:315)
	at org.apache.commons.jexl3.parser.ASTDivNode.jjtAccept(ASTDivNode.java:18)
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:892)
	at org.apache.commons.jexl3.parser.ASTJexlScript.jjtAccept(ASTJexlScript.java:55)
	at org.apache.commons.jexl3.internal.Interpreter.interpret(Interpreter.java:186)
	at org.apache.commons.jexl3.internal.Script.execute(Script.java:178)
	at org.apache.commons.jexl3.internal.Script.evaluate(Script.java:170)
	at org.jkiss.dbeaver.tools.transfer.transformers.DataTransferTransformerExpression.transformAttribute(DataTransferTransformerExpression.java:46)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:360)
	at com.dbeaver.db.mongodb.model.MGCollection.readData(MGCollection.java:300)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
)

java.lang.ArithmeticException: BigInteger coercion: org.jkiss.dbeaver.model.impl.data.DBDValueError:(org.jkiss.dbeaver.model.exec.DBCException: 63bd3ee27dd8c0182f562d6b
	at org.jkiss.dbeaver.model.data.DBDAttributeBindingType.extractNestedValue(DBDAttributeBindingType.java:165)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeValue(DBUtils.java:832)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeValue(DBUtils.java:788)
	at org.jkiss.dbeaver.tools.transfer.transformers.DataTransferTransformerExpression$VariablesContext.get(DataTransferTransformerExpression.java:77)
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:922)
	at org.apache.commons.jexl3.parser.ASTIdentifier.jjtAccept(ASTIdentifier.java:61)
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:315)
	at org.apache.commons.jexl3.parser.ASTDivNode.jjtAccept(ASTDivNode.java:18)
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:892)
	at org.apache.commons.jexl3.parser.ASTJexlScript.jjtAccept(ASTJexlScript.java:55)
	at org.apache.commons.jexl3.internal.Interpreter.interpret(Interpreter.java:186)
	at org.apache.commons.jexl3.internal.Script.execute(Script.java:178)
	at org.apache.commons.jexl3.internal.Script.evaluate(Script.java:170)
	at org.jkiss.dbeaver.tools.transfer.transformers.DataTransferTransformerExpression.transformAttribute(DataTransferTransformerExpression.java:46)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:360)
	at com.dbeaver.db.mongodb.model.MGCollection.readData(MGCollection.java:300)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
)
	at org.apache.commons.jexl3.JexlArithmetic.toBigInteger(JexlArithmetic.java:1320)
	at org.apache.commons.jexl3.JexlArithmetic.divide(JexlArithmetic.java:684)
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:319)
	at org.apache.commons.jexl3.parser.ASTDivNode.jjtAccept(ASTDivNode.java:18)
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:892)
	at org.apache.commons.jexl3.parser.ASTJexlScript.jjtAccept(ASTJexlScript.java:55)
	at org.apache.commons.jexl3.internal.Interpreter.interpret(Interpreter.java:186)
	at org.apache.commons.jexl3.internal.Script.execute(Script.java:178)
	at org.apache.commons.jexl3.internal.Script.evaluate(Script.java:170)
	at org.jkiss.dbeaver.tools.transfer.transformers.DataTransferTransformerExpression.transformAttribute(DataTransferTransformerExpression.java:46)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:360)
	at com.dbeaver.db.mongodb.model.MGCollection.readData(MGCollection.java:300)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by uslss** [comment]
verified for checked databases and for example in ticket.

blocked by https://github.com/dbeaver/pro/issues/1459 for couchdb and couchbase

**Comment by uslss** [comment]
https://user-images.githubusercontent.com/31996417/225334913-000a22d8-458b-4a18-9809-b10db02af46a.mp4

**Comment by uslss** [comment]
Fails for DynamoDB with transformers
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Mar 21 15:30:29 CET 2023
org.jkiss.dbeaver.model.virtual.DBVUtils.parseExpression@1:1 undefined variable Sotr

org.apache.commons.jexl3.JexlException$Variable: org.jkiss.dbeaver.model.virtual.DBVUtils.parseExpression@1:1 undefined variable Sotr
	at org.jkiss.dbeaver.tools.transfer.transformers.DataTransferTransformerExpression.transformAttribute(DataTransferTransformerExpression.java:46)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:359)
	at com.dbeaver.db.dynamodb.model.DynamoTable.readData(DynamoTable.java:333)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:126)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by uslss** [comment]
verified

**Pull request merged**
