### PR TITLE
Tanslation korean

### PR DESCRIPTION
**Pull request by dorbae**
Hi. I'm Seongbae.
I added the Korean option in language setting. And I also added/updated bundle.ko.properties files.
I'm doing just a tiny thing. Nevertheless, it is a very exciting thing to contribute to your project. 
Thank you.

### CODE REVIEW

**Comment by serge-rider** [comment]
Thanks!
Generally Korean translation looks good.
One thing - you have modified English resource file (bundle.properties in navigator plugin) and it is incorrect. It looks like a mess of ui.editors.data bundle and ui.navigator bundle. Please remove these changes from PR.

**Comment by dorbae** [comment]
Sorry, it was my mistake.
Have a good day :)

**Comment by dorbae** [comment]
I replaced my bundle.properties in org.jkiss.dbeaver.ui.navigator with bundle.properties in devel branch a few minutes ago. Thank you!

**Comment by dorbae** [comment]
> Thanks!
> Generally Korean translation looks good.
> One thing - you have modified English resource file (bundle.properties in navigator plugin) and it is incorrect. It looks like a mess of ui.editors.data bundle and ui.navigator bundle. Please remove these changes from PR.

I replaced my bundle.properties in org.jkiss.dbeaver.ui.navigator with bundle.properties in devel branch a few minutes ago. Thank you!

**Comment by serge-rider** [comment]
Thanks, merging.

I'll also add Korean localization of all standard controls and preferences (it comes from Babel package automatically). And will add korean in the list of languages in Windows installer.

**Pull request merged**
