### PR TITLE
dbeaver/pro#2296 SQL Editor Outline

### PR DESCRIPTION
**Pull request by E1izabeth**
image

To open outline you can use default eclipse shortcut `Alt+Shift+Q, O`, sql editor bottom toolbar command or SQL Editor->Panels context menu
image

Tree selection follows the cursor movement in the SQL Editor. Also you can click outline tree item to select the corresponding fragment of the sql query in the editor.

image

### CODE REVIEW

**Review by ShadelessFox — COMMENTED** [review]
Tabs are no-no :(

**Comment by E1izabeth** [comment]
Tabs?

**Comment by ShadelessFox** [comment]
All added lines are indented with tabs instead of spaces

**Comment by E1izabeth** [comment]
Ohh...

**Review by LonwoLonwo — APPROVED** [review]

**Review by Destrolaric — APPROVED** [review]

**Comment by uslss** [comment]
script isn't correctly detected in new sql editor

https://github.com/dbeaver/dbeaver/assets/31996417/037010dc-206a-4698-b011-c63d6e54bb40

**Pull request merged**
