### PR TITLE
Initial support for RisingWave streaming database

### LINKED ISSUE #18550: Support for RisingWave Streaming Database
**Is your feature request related to a problem? Please describe.**
Support [RisingWave](https://www.risingwave.com/) Streaming Database in DBeaver

**Describe the solution you'd like**
RisingWave is an open-source cloud-native streaming database compatible with PostgreSQL. We only need to enable a subset of DBeaver PostgreSQL features supported by RisingWave so we will have a RisingWave implementation for `PostgreServerExtensionBase`.

**Describe alternatives you've considered**
Using native PostgreSQL driver doesn't work since the default port/user/database are different and there are some PostgresSQL features that not supported in RisingWave (e.g. trigger, tablespace, ...).

### PR DESCRIPTION
**Pull request by hzxa21**
#18550

- Implement `PostgreServerExtensionBase` for RisingWave
- Add RisingWave logos and driver default configurations

Tested on my local linux environment

### CODE REVIEW

**Comment by E1izabeth** [comment]
Thank you for contribution.

**Review by E1izabeth — APPROVED** [review]

**Review by LonwoLonwo — APPROVED** [review]

**Review by Destrolaric — APPROVED** [review]

**Comment by neverchanje** [comment]
Hi dbeaver folks! May I ask what's the status of this PR? Given that all checks have passed and there are 3 approvals here, will we merge it in our next release?

**Comment by E1izabeth** [comment]
The PR should be tested by our QA team before merge. It's waiting for testing.

**Comment by neverchanje** [comment]
@E1izabeth Thanks for your information!

**Comment by hzxa21** [comment]
Hi @E1izabeth, can you share some information about the testing plan? If you need anything from our side, feel free to reach out.

**Comment by E1izabeth** [comment]
We didn't have RisingWave database for testing, so the setting up took some time. Recently devops team confirmed that the environment is ready for testing. I hope your PR will be checked soon.

**Comment by uslss** [comment]
-incorrect ddl for new tables are generated - blocks table creation/changing using UI + datatransfer
image

-refresh doesn't work in db navigator. new objects are shown after reconnect only.
-ERD for tables node, Schemas, Materialized views, functions, aggregate functions  folder cannot be opened in Metadata Editor due to an error
image
-permissions cannot be granted to user using UI

https://user-images.githubusercontent.com/31996417/226311298-b5285bc6-b57a-4d9d-8b4d-2983cee5ba52.mp4
-error is shown for almost all tab in table properties. incorrect DDL

https://user-images.githubusercontent.com/31996417/226311771-6490e00d-138f-419d-919e-67325b40ebc3.mp4

-roles aren't supported - but node is shown. The same situation for jobs
image

-session manager isn't working

**Comment by Destrolaric** [comment]
@hzxa21 Hi, there are issues described above by the @uslss. Could you take a look and see if they could be fixed?

**Comment by hzxa21** [comment]
> @hzxa21 Hi, there are issues described above by the @uslss. Could you take a look and see if they could be fixed?

I will take a look. May I know which version of RisingWave you are using and how did you deploy RisingWave? @uslss @Destrolaric

**Comment by Destrolaric** [comment]
@hzxa21 `risingwavelabs/risingwave:latest` Docker instance was used for testing.

**Comment by fuyufjh** [comment]
Hi, @Destrolaric, are there any updates? We hope to release DBeaver support for RisingWave (https://github.com/risingwavelabs/risingwave/issues/6878) asap but it's blocked here.

**Comment by E1izabeth** [comment]
We can't merge this PR, untill the [listed issues](https://github.com/dbeaver/dbeaver/pull/18551#issuecomment-1475976796) aren't solved

**Comment by E1izabeth** [comment]
@hzxa21 please let us know if you need some help while resolving the described issues.

**Comment by hzxa21** [comment]
@E1izabeth Sorry for my late reply and thanks for the effeorts on reviewing/testing this PR. Recently, we have added more supports on the pg system tables and functions in RisingWave so now DBeaver users are able to use the standard postgres connector to connect to RisingWave and explore the basic functionalities in DBeaver. Therefore, there is no need to introduce the RisingWave DBeaver plugin for now. 

Feel free to close this PR.

**Comment by E1izabeth** [comment]
Thank you for update.

**Pull request closed without merging**
