### PR TITLE
#17537 Switch to JSCH fork

### LINKED ISSUE #17537: SSH tunnel not connect from DBeaver to latest linux distros.
#### System information: 
- Linux, macOS
- DBeaver *

#### Connection specification:
- SSH tunnel 

#### Describe the problem you're observing:
SSH tunnel not connect from DBeaver to latest linux distros.

#### Steps to reproduce, if exist:
Install latest version of any linux distro (ubuntu22,fedora36,redhat8) and update it
Try to setup ssh tunnel from dbeaver connection with rsa key

#### Include any warning/errors/backtraces from the logs
```
2022-08-31 21:36:47.642 - pageant connect exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.connector.PageantConnector$User32
        at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:68)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:110)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:257)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:603)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2022-08-31 21:36:47.643 - SSH: Connected with ssh-agent
2022-08-31 21:36:47.643 - Creating identity repository
2022-08-31 21:36:47.643 - Configure tunnel
2022-08-31 21:36:47.706 - Connect to tunnel host
2022-08-31 21:36:47.707 - SSH INFO: Connecting to -.-.-.- port 22
2022-08-31 21:36:47.740 - SSH INFO: Connection established
2022-08-31 21:36:47.782 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
2022-08-31 21:36:47.782 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2022-08-31 21:36:47.782 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2022-08-31 21:36:47.783 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2022-08-31 21:36:47.792 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2022-08-31 21:36:47.792 - SSH INFO: SSH_MSG_KEXINIT sent
2022-08-31 21:36:47.811 - SSH INFO: SSH_MSG_KEXINIT received
2022-08-31 21:36:47.811 - SSH INFO: kex: server: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
2022-08-31 21:36:47.811 - SSH INFO: kex: server: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
2022-08-31 21:36:47.811 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
2022-08-31 21:36:47.811 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
2022-08-31 21:36:47.811 - SSH INFO: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2022-08-31 21:36:47.811 - SSH INFO: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2022-08-31 21:36:47.811 - SSH INFO: kex: server: none,zlib@openssh.com
2022-08-31 21:36:47.812 - SSH INFO: kex: server: none,zlib@openssh.com
2022-08-31 21:36:47.812 - SSH INFO: kex: server: 
2022-08-31 21:36:47.812 - SSH INFO: kex: server: 
2022-08-31 21:36:47.812 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2022-08-31 21:36:47.812 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2022-08-31 21:36:47.812 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2022-08-31 21:36:47.812 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2022-08-31 21:36:47.812 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2022-08-31 21:36:47.812 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2022-08-31 21:36:47.812 - SSH INFO: kex: client: none
2022-08-31 21:36:47.812 - SSH INFO: kex: client: none
2022-08-31 21:36:47.812 - SSH INFO: kex: client: 
2022-08-31 21:36:47.812 - SSH INFO: kex: client: 
2022-08-31 21:36:47.812 - SSH INFO: kex: server->client aes128-ctr hmac-sha1 none
2022-08-31 21:36:47.812 - SSH INFO: kex: client->server aes128-ctr hmac-sha1 none
2022-08-31 21:36:47.813 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2022-08-31 21:36:47.813 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2022-08-31 21:36:47.847 - SSH INFO: Host '-.-.-.-' is known and matches the ECDSA host key
2022-08-31 21:36:47.847 - SSH INFO: SSH_MSG_NEWKEYS sent
2022-08-31 21:36:47.847 - SSH INFO: SSH_MSG_NEWKEYS received
2022-08-31 21:36:47.847 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2022-08-31 21:36:47.879 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2022-08-31 21:36:47.916 - SSH INFO: Authentications that can continue: publickey,keyboard-interactive,password
2022-08-31 21:36:47.916 - SSH INFO: Next authentication method: publickey
2022-08-31 21:36:47.953 - SSH INFO: Disconnecting from -.-.-.- port 22
2022-08-31 21:36:48.055 - Auth fail
com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:519)
        at com.jcraft.jsch.Session.connect(Session.java:183)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:116)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:133)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:257)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:603)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
2022-08-31 21:23:04.152 - pageant connect exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.connector.PageantConnector$User32
        at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:68)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:110)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:257)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:603)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2022-08-31 21:23:04.152 - SSH: Connected with ssh-agent
2022-08-31 21:23:04.152 - Creating new SecureRandom.
2022-08-31 21:23:04.153 - No such algorithm: IDEA/CBC/NoPadding
2022-08-31 21:23:04.154 - No such algorithm: IDEA/CTR/NoPadding
2022-08-31 21:23:04.156 - Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
2022-08-31 21:23:04.242 - Client identity string: SSH-2.0-SSHJ_0.33.0
2022-08-31 21:23:04.293 - Server identity string: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
2022-08-31 21:23:04.569 - Exhausted available authentication methods
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:110)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:133)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:257)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:603)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2022-08-31 21:25:04.331 - Dying because - Broken transport; encountered EOF
2022-08-31 21:25:04.331 - Disconnected - UNKNOWN
```

### LINKED ISSUE #18654: Migrate to alive jsch fork
https://github.com/mwiede/jsch
It's a fork of jsch with a good support. We've found a bug and created PR which has been merged mwiede/jsch#257. Also some other bugs might be fixed. Let's switch our dependency to this fork.

### PR DESCRIPTION
**Pull request by ShadelessFox**

### CODE REVIEW

**Comment by Destrolaric** [comment]
@ShadelessFox Could you also link the tickets associated with JSCH fork migration? I think we have several and we possibly want to test them too.
Also, we possibly may want to enable deprecated algorithms, but it's another topic for discussion because it also has some possible downsides

**Review by E1izabeth — APPROVED** [review]
Close #18654

**Comment by E1izabeth** [comment]
I'd eliminate workaround used here https://github.com/dbeaver/dbeaver/pull/18590 as we don't need it anymore.

**Review by E1izabeth — APPROVED** [review]

**Comment by E1izabeth** [comment]
It may solve this issue #14749

**Comment by Matvey16** [comment]
Verified

**Pull request merged**
