### PR TITLE
#19365 Fix commands for foldings

### LINKED ISSUE #19365: Incorrect Command names in Preferences -> Keys
### Description

image

I wanted to add shortcuts to the Foldings Enabled, Expand All Foldings, and other options and noticed that the names are not displayed correctly.

### DBeaver Version

Community Edition 23.0.0

### Operating System

_No response_

### Database and driver

_No response_

### Steps to reproduce

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by E1izabeth**
Command names in Key settings should be fixed.

### CODE REVIEW

**Review by LonwoLonwo — APPROVED** [review]

**Comment by uslss** [comment]
still reproducible
image

**Comment by E1izabeth** [comment]
@uslss have you tried resetting ui settings?

**Comment by E1izabeth** [comment]
Please try checking Reset settings option in installer.

**Comment by uslss** [comment]
verified

**Pull request merged**
